import { getAssetUrl } from "ee/utils/airgapHelpers";
import { ASSETS_CDN_URL } from "constants/ThirdPartyConstants";
import type { MetaWidgetsReduxState } from "reducers/entityReducers/metaWidgetsReducer";

export const metaWidgetState: MetaWidgetsReduxState = {
  baowuczcgg: {
    isVisible: true,
    parentColumnSpace: 1,
    parentRowSpace: 1,
    defaultImage: getAssetUrl(`${ASSETS_CDN_URL}/widgets/default.png`),
    imageShape: "RECTANGLE",
    maxZoomLevel: 1,
    enableRotation: false,
    enableDownload: false,
    objectFit: "cover",
    image: "{{((currentItem) => currentItem.img)(Image1.currentItem)}}",
    widgetName: "Image1",
    version: 1,
    animateLoading: true,
    type: "IMAGE_WIDGET",
    hideCard: false,
    isDeprecated: false,
    displayName: "Image",
    key: "zqar6ryg82",
    iconSVG: "/static/media/icon.52d8fb963abcb95c79b10f1553389f22.svg",
    boxShadow: "none",
    dynamicBindingPathList: [
      {
        key: "image",
      },
      {
        key: "borderRadius",
      },
      {
        key: "currentItem",
      },
      {
        key: "currentView",
      },
    ],
    dynamicTriggerPathList: [],
    widgetId: "baowuczcgg",
    renderMode: "CANVAS",
    borderRadius: "{{appsmith.theme.borderRadius.appBorderRadius}}",
    isLoading: false,
    leftColumn: 0,
    rightColumn: 16,
    topRow: 0,
    bottomRow: 8,
    parentId: "xbbs7cls18",
    currentItem: "{{List1.listData[Image1.currentIndex]}}",
    currentView: "{{{}}}",
    currentIndex: 0,
    children: [],
    referencedWidgetId: "baowuczcgg",
    isMetaWidget: true,
    creatorId: "hwgin979n4",
  },
  xy20z9gxsc: {
    isVisible: true,
    parentColumnSpace: 1,
    parentRowSpace: 1,
    text: "{{((currentItem) => currentItem.name)(Text1.currentItem)}}",
    fontSize: "1rem",
    fontStyle: "BOLD",
    textAlign: "LEFT",
    textColor: "#231F20",
    truncateButtonColor: "#FFC13D",
    widgetName: "Text1",
    shouldTruncate: false,
    overflow: "NONE",
    version: 1,
    animateLoading: true,
    searchTags: ["typography", "paragraph", "label"],
    type: "TEXT_WIDGET",
    hideCard: false,
    isDeprecated: false,
    displayName: "Text",
    key: "eezvtpz4sw",
    iconSVG: "/static/media/icon.97c59b523e6f70ba6f40a10fc2c7c5b5.svg",
    textStyle: "HEADING",
    boxShadow: "none",
    dynamicBindingPathList: [
      {
        key: "text",
      },
      {
        key: "fontFamily",
      },
      {
        key: "borderRadius",
      },
      {
        key: "currentItem",
      },
      {
        key: "currentView",
      },
    ],
    dynamicTriggerPathList: [],
    widgetId: "xy20z9gxsc",
    renderMode: "CANVAS",
    fontFamily: "{{appsmith.theme.fontFamily.appFont}}",
    borderRadius: "{{appsmith.theme.borderRadius.appBorderRadius}}",
    isLoading: false,
    leftColumn: 16,
    rightColumn: 28,
    topRow: 0,
    bottomRow: 4,
    parentId: "xbbs7cls18",
    currentItem: "{{List1.listData[Text1.currentIndex]}}",
    currentView: "{{{}}}",
    currentIndex: 0,
    children: [],
    referencedWidgetId: "xy20z9gxsc",
    isMetaWidget: true,
    creatorId: "hwgin979n4",
  },
  tsdy8whhl1: {
    isVisible: true,
    parentColumnSpace: 1,
    parentRowSpace: 1,
    text: "{{((currentItem) => currentItem.id)(Text2.currentItem)}}",
    fontSize: "1rem",
    fontStyle: "BOLD",
    textAlign: "LEFT",
    textColor: "#231F20",
    truncateButtonColor: "#FFC13D",
    widgetName: "Text2",
    shouldTruncate: false,
    overflow: "NONE",
    version: 1,
    animateLoading: true,
    searchTags: ["typography", "paragraph", "label"],
    type: "TEXT_WIDGET",
    hideCard: false,
    isDeprecated: false,
    displayName: "Text",
    key: "eezvtpz4sw",
    iconSVG: "/static/media/icon.97c59b523e6f70ba6f40a10fc2c7c5b5.svg",
    textStyle: "BODY",
    boxShadow: "none",
    dynamicBindingPathList: [
      {
        key: "text",
      },
      {
        key: "fontFamily",
      },
      {
        key: "borderRadius",
      },
      {
        key: "currentItem",
      },
      {
        key: "currentView",
      },
    ],
    dynamicTriggerPathList: [],
    widgetId: "tsdy8whhl1",
    renderMode: "CANVAS",
    fontFamily: "{{appsmith.theme.fontFamily.appFont}}",
    borderRadius: "{{appsmith.theme.borderRadius.appBorderRadius}}",
    isLoading: false,
    leftColumn: 16,
    rightColumn: 24,
    topRow: 4,
    bottomRow: 8,
    parentId: "xbbs7cls18",

    currentItem: "{{List1.listData[Text2.currentIndex]}}",
    currentView: "{{{}}}",
    currentIndex: 0,
    children: [],
    referencedWidgetId: "tsdy8whhl1",
    isMetaWidget: true,
    creatorId: "hwgin979n4",
  },
  xbbs7cls18: {
    isVisible: true,
    widgetName: "Canvas2",
    version: 1,
    detachFromLayout: true,
    type: "CANVAS_WIDGET",
    hideCard: true,
    isDeprecated: false,
    displayName: "Canvas",
    key: "rhrv9ccmof",
    containerStyle: "none",
    canExtend: false,
    children: ["baowuczcgg", "xy20z9gxsc", "tsdy8whhl1"],
    minHeight: 1,
    widgetId: "xbbs7cls18",
    renderMode: "CANVAS",
    boxShadow: "none",
    borderRadius: "{{appsmith.theme.borderRadius.appBorderRadius}}",
    accentColor: "{{appsmith.theme.colors.primaryColor}}",
    isLoading: false,
    parentColumnSpace: 1,
    parentRowSpace: 1,
    leftColumn: 0,
    rightColumn: 1,
    topRow: 0,
    bottomRow: 1,
    parentId: "e3bqqc9oid",
    dynamicBindingPathList: [
      {
        key: "borderRadius",
      },
      {
        key: "accentColor",
      },
      {
        key: "currentView",
      },
    ],

    currentView: "{{{}}}",
    currentIndex: 0,
    referencedWidgetId: "xbbs7cls18",
    isMetaWidget: true,
    creatorId: "hwgin979n4",
  },
  e3bqqc9oid: {
    isVisible: true,
    parentColumnSpace: 1,
    parentRowSpace: 1,
    backgroundColor: "white",
    widgetName: "Container1",
    containerStyle: "card",
    borderColor: "#E0DEDE",
    borderWidth: "1",
    boxShadow: "{{appsmith.theme.boxShadow.appBoxShadow}}",
    animateLoading: true,
    children: ["xbbs7cls18"],
    version: 1,
    searchTags: ["div", "parent", "group"],
    type: "CONTAINER_WIDGET",
    hideCard: false,
    isDeprecated: false,
    displayName: "Container",
    key: "b33ov8lfex",
    iconSVG: "/static/media/icon.1977dca3370505e2db3a8e44cfd54907.svg",
    isCanvas: true,
    dragDisabled: true,
    isDeletable: false,
    disallowCopy: true,
    disablePropertyPane: true,
    openParentPropertyPane: true,
    widgetId: "e3bqqc9oid",
    renderMode: "CANVAS",
    borderRadius: "{{appsmith.theme.borderRadius.appBorderRadius}}",
    isLoading: false,
    leftColumn: 0,
    rightColumn: 64,
    topRow: 0,
    bottomRow: 12,
    parentId: "8ari8fii6k",
    dynamicBindingPathList: [
      {
        key: "borderRadius",
      },
      {
        key: "boxShadow",
      },
      {
        key: "data",
      },
    ],

    gap: 0,
    data: "{{\n      {\n        \n          Image1: { image: Image1.image,isVisible: Image1.isVisible }\n        ,\n          Text1: { isVisible: Text1.isVisible,text: Text1.text }\n        ,\n          Text2: { isVisible: Text2.isVisible,text: Text2.text }\n        \n      }\n    }}",
    currentIndex: 0,
    referencedWidgetId: "e3bqqc9oid",
    isMetaWidget: true,
    creatorId: "hwgin979n4",
  },
  u2jvh7h1f1: {
    parentColumnSpace: 1,
    parentRowSpace: 1,
    isVisible: true,
    defaultImage: getAssetUrl(`${ASSETS_CDN_URL}/widgets/default.png`),
    imageShape: "RECTANGLE",
    maxZoomLevel: 1,
    enableRotation: false,
    enableDownload: false,
    objectFit: "cover",
    image:
      "{{((currentItem) => currentItem.img)(List1_Image1_u2jvh7h1f1.currentItem)}}",
    widgetName: "List1_Image1_u2jvh7h1f1",
    version: 1,
    animateLoading: true,
    type: "IMAGE_WIDGET",
    hideCard: false,
    isDeprecated: false,
    displayName: "Image",
    key: "zqar6ryg82",
    iconSVG: "/static/media/icon.52d8fb963abcb95c79b10f1553389f22.svg",
    boxShadow: "none",
    dynamicBindingPathList: [
      {
        key: "image",
      },
      {
        key: "borderRadius",
      },
      {
        key: "currentItem",
      },
      {
        key: "currentView",
      },
    ],
    dynamicTriggerPathList: [],
    widgetId: "u2jvh7h1f1",
    renderMode: "CANVAS",
    borderRadius: "{{appsmith.theme.borderRadius.appBorderRadius}}",
    isLoading: false,
    leftColumn: 0,
    rightColumn: 16,
    topRow: 0,
    bottomRow: 8,
    parentId: "ze1bnh8dpw",

    currentItem: "{{List1.listData[List1_Image1_u2jvh7h1f1.currentIndex]}}",
    currentView: "{{{}}}",
    resizeDisabled: true,
    disablePropertyPane: true,
    dragDisabled: true,
    dropDisabled: true,
    ignoreCollision: true,
    disabledResizeHandles: [
      "left",
      "top",
      "right",
      "bottomRight",
      "topLeft",
      "topRight",
      "bottomLeft",
    ],
    currentIndex: 1,
    children: [],
    referencedWidgetId: "baowuczcgg",
    isMetaWidget: true,
    creatorId: "hwgin979n4",
  },
  pawh54e2lk: {
    parentColumnSpace: 1,
    parentRowSpace: 1,
    isVisible: true,
    text: "{{((currentItem) => currentItem.name)(List1_Text1_pawh54e2lk.currentItem)}}",
    fontSize: "1rem",
    fontStyle: "BOLD",
    textAlign: "LEFT",
    textColor: "#231F20",
    truncateButtonColor: "#FFC13D",
    widgetName: "List1_Text1_pawh54e2lk",
    shouldTruncate: false,
    overflow: "NONE",
    version: 1,
    animateLoading: true,
    searchTags: ["typography", "paragraph", "label"],
    type: "TEXT_WIDGET",
    hideCard: false,
    isDeprecated: false,
    displayName: "Text",
    key: "eezvtpz4sw",
    iconSVG: "/static/media/icon.97c59b523e6f70ba6f40a10fc2c7c5b5.svg",
    textStyle: "HEADING",
    boxShadow: "none",
    dynamicBindingPathList: [
      {
        key: "text",
      },
      {
        key: "fontFamily",
      },
      {
        key: "borderRadius",
      },
      {
        key: "currentItem",
      },
      {
        key: "currentView",
      },
    ],
    dynamicTriggerPathList: [],
    widgetId: "pawh54e2lk",
    renderMode: "CANVAS",
    fontFamily: "{{appsmith.theme.fontFamily.appFont}}",
    borderRadius: "{{appsmith.theme.borderRadius.appBorderRadius}}",
    isLoading: false,
    leftColumn: 16,
    rightColumn: 28,
    topRow: 0,
    bottomRow: 4,
    parentId: "ze1bnh8dpw",
    currentItem: "{{List1.listData[List1_Text1_pawh54e2lk.currentIndex]}}",
    currentView: "{{{}}}",
    resizeDisabled: true,
    disablePropertyPane: true,
    dragDisabled: true,
    dropDisabled: true,
    ignoreCollision: true,
    disabledResizeHandles: [
      "left",
      "top",
      "right",
      "bottomRight",
      "topLeft",
      "topRight",
      "bottomLeft",
    ],
    currentIndex: 1,
    children: [],
    referencedWidgetId: "xy20z9gxsc",
    isMetaWidget: true,
    creatorId: "hwgin979n4",
  },
  o6yxt84kj5: {
    parentColumnSpace: 1,
    parentRowSpace: 1,
    isVisible: true,
    text: "{{((currentItem) => currentItem.id)(List1_Text2_o6yxt84kj5.currentItem)}}",
    fontSize: "1rem",
    fontStyle: "BOLD",
    textAlign: "LEFT",
    textColor: "#231F20",
    truncateButtonColor: "#FFC13D",
    widgetName: "List1_Text2_o6yxt84kj5",
    shouldTruncate: false,
    overflow: "NONE",
    version: 1,
    animateLoading: true,
    searchTags: ["typography", "paragraph", "label"],
    type: "TEXT_WIDGET",
    hideCard: false,
    isDeprecated: false,
    displayName: "Text",
    key: "eezvtpz4sw",
    iconSVG: "/static/media/icon.97c59b523e6f70ba6f40a10fc2c7c5b5.svg",
    textStyle: "BODY",
    boxShadow: "none",
    dynamicBindingPathList: [
      {
        key: "text",
      },
      {
        key: "fontFamily",
      },
      {
        key: "borderRadius",
      },
      {
        key: "currentItem",
      },
      {
        key: "currentView",
      },
    ],
    dynamicTriggerPathList: [],
    widgetId: "o6yxt84kj5",
    renderMode: "CANVAS",
    fontFamily: "{{appsmith.theme.fontFamily.appFont}}",
    borderRadius: "{{appsmith.theme.borderRadius.appBorderRadius}}",
    isLoading: false,
    leftColumn: 16,
    rightColumn: 24,
    topRow: 4,
    bottomRow: 8,
    parentId: "ze1bnh8dpw",

    currentItem: "{{List1.listData[List1_Text2_o6yxt84kj5.currentIndex]}}",
    currentView: "{{{}}}",
    resizeDisabled: true,
    disablePropertyPane: true,
    dragDisabled: true,
    dropDisabled: true,
    ignoreCollision: true,
    disabledResizeHandles: [
      "left",
      "top",
      "right",
      "bottomRight",
      "topLeft",
      "topRight",
      "bottomLeft",
    ],
    currentIndex: 1,
    children: [],
    referencedWidgetId: "tsdy8whhl1",
    isMetaWidget: true,
    creatorId: "hwgin979n4",
  },
  ze1bnh8dpw: {
    isVisible: true,
    widgetName: "List1_Canvas2_ze1bnh8dpw",
    version: 1,
    detachFromLayout: true,
    type: "CANVAS_WIDGET",
    hideCard: true,
    isDeprecated: false,
    displayName: "Canvas",
    key: "rhrv9ccmof",
    containerStyle: "none",
    canExtend: false,
    children: ["u2jvh7h1f1", "pawh54e2lk", "o6yxt84kj5"],
    minHeight: 1,
    widgetId: "ze1bnh8dpw",
    renderMode: "CANVAS",
    boxShadow: "none",
    borderRadius: "{{appsmith.theme.borderRadius.appBorderRadius}}",
    accentColor: "{{appsmith.theme.colors.primaryColor}}",
    isLoading: false,
    parentColumnSpace: 1,
    parentRowSpace: 1,
    leftColumn: 0,
    rightColumn: 1,
    topRow: 0,
    bottomRow: 1,
    parentId: "4b5r4c3kp7",
    dynamicBindingPathList: [
      {
        key: "borderRadius",
      },
      {
        key: "accentColor",
      },
      {
        key: "currentView",
      },
    ],

    currentView: "{{{}}}",
    resizeDisabled: true,
    disablePropertyPane: true,
    dragDisabled: true,
    dropDisabled: true,
    ignoreCollision: true,
    disabledResizeHandles: [
      "left",
      "top",
      "right",
      "bottomRight",
      "topLeft",
      "topRight",
      "bottomLeft",
    ],
    currentIndex: 1,
    referencedWidgetId: "xbbs7cls18",
    isMetaWidget: true,
    creatorId: "hwgin979n4",
  },
  "4b5r4c3kp7": {
    parentColumnSpace: 1,
    parentRowSpace: 1,
    isVisible: true,
    backgroundColor: "white",
    widgetName: "List1_Container1_4b5r4c3kp7",
    containerStyle: "card",
    borderColor: "#E0DEDE",
    borderWidth: "1",
    boxShadow: "{{appsmith.theme.boxShadow.appBoxShadow}}",
    animateLoading: true,
    children: ["ze1bnh8dpw"],
    version: 1,
    searchTags: ["div", "parent", "group"],
    type: "CONTAINER_WIDGET",
    hideCard: false,
    isDeprecated: false,
    displayName: "Container",
    key: "b33ov8lfex",
    iconSVG: "/static/media/icon.1977dca3370505e2db3a8e44cfd54907.svg",
    isCanvas: true,
    dragDisabled: true,
    isDeletable: false,
    disallowCopy: true,
    disablePropertyPane: true,
    openParentPropertyPane: true,
    widgetId: "4b5r4c3kp7",
    renderMode: "CANVAS",
    borderRadius: "{{appsmith.theme.borderRadius.appBorderRadius}}",
    isLoading: false,
    leftColumn: 0,
    rightColumn: 64,
    topRow: 12,
    bottomRow: 24,
    parentId: "8ari8fii6k",
    dynamicBindingPathList: [
      {
        key: "borderRadius",
      },
      {
        key: "boxShadow",
      },
      {
        key: "data",
      },
    ],

    gap: 0,
    data: "{{\n      {\n        \n          Image1: { image: List1_Image1_u2jvh7h1f1.image,isVisible: List1_Image1_u2jvh7h1f1.isVisible }\n        ,\n          Text1: { isVisible: List1_Text1_pawh54e2lk.isVisible,text: List1_Text1_pawh54e2lk.text }\n        ,\n          Text2: { isVisible: List1_Text2_o6yxt84kj5.isVisible,text: List1_Text2_o6yxt84kj5.text }\n        \n      }\n    }}",
    resizeDisabled: true,
    dropDisabled: true,
    ignoreCollision: true,
    disabledResizeHandles: [
      "left",
      "top",
      "right",
      "bottomRight",
      "topLeft",
      "topRight",
      "bottomLeft",
    ],
    currentIndex: 1,
    referencedWidgetId: "e3bqqc9oid",
    isMetaWidget: true,
    creatorId: "hwgin979n4",
  },
  "8ari8fii6k": {
    parentRowSpace: 1,
    isVisible: true,
    widgetName: "Canvas1",
    version: 1,
    detachFromLayout: true,
    type: "CANVAS_WIDGET",
    hideCard: true,
    isDeprecated: false,
    displayName: "Canvas",
    key: "rhrv9ccmof",
    containerStyle: "none",
    dropDisabled: true,
    openParentPropertyPane: true,
    noPad: true,
    children: ["e3bqqc9oid", "4b5r4c3kp7", "3g3bxw6q2z"],
    minHeight: 400,
    widgetId: "8ari8fii6k",
    renderMode: "CANVAS",
    boxShadow: "none",
    borderRadius: "{{appsmith.theme.borderRadius.appBorderRadius}}",
    accentColor: "{{appsmith.theme.colors.primaryColor}}",
    isLoading: false,
    parentColumnSpace: 1,
    leftColumn: 0,
    rightColumn: 505.5,
    topRow: 0,
    bottomRow: 400,
    parentId: "hwgin979n4",
    dynamicBindingPathList: [
      {
        key: "borderRadius",
      },
      {
        key: "accentColor",
      },
    ],
    isMetaWidget: true,
    creatorId: "hwgin979n4",
  },
  "3vmg2xwodp": {
    parentColumnSpace: 1,
    parentRowSpace: 1,
    isVisible: true,
    defaultImage: getAssetUrl(`${ASSETS_CDN_URL}/widgets/default.png`),
    imageShape: "RECTANGLE",
    maxZoomLevel: 1,
    enableRotation: false,
    enableDownload: false,
    objectFit: "cover",
    image:
      "{{((currentItem) => currentItem.img)(List1_Image1_3vmg2xwodp.currentItem)}}",
    widgetName: "List1_Image1_3vmg2xwodp",
    version: 1,
    animateLoading: true,
    type: "IMAGE_WIDGET",
    hideCard: false,
    isDeprecated: false,
    displayName: "Image",
    key: "zqar6ryg82",
    iconSVG: "/static/media/icon.52d8fb963abcb95c79b10f1553389f22.svg",
    boxShadow: "none",
    dynamicBindingPathList: [
      {
        key: "image",
      },
      {
        key: "borderRadius",
      },
      {
        key: "currentItem",
      },
      {
        key: "currentView",
      },
    ],
    dynamicTriggerPathList: [],
    widgetId: "3vmg2xwodp",
    renderMode: "CANVAS",
    borderRadius: "{{appsmith.theme.borderRadius.appBorderRadius}}",
    isLoading: false,
    leftColumn: 0,
    rightColumn: 16,
    topRow: 0,
    bottomRow: 8,
    parentId: "gb0vgfvp68",
    currentItem: "{{List1.listData[List1_Image1_3vmg2xwodp.currentIndex]}}",
    currentView: "{{{}}}",
    resizeDisabled: true,
    disablePropertyPane: true,
    dragDisabled: true,
    dropDisabled: true,
    ignoreCollision: true,
    disabledResizeHandles: [
      "left",
      "top",
      "right",
      "bottomRight",
      "topLeft",
      "topRight",
      "bottomLeft",
    ],
    currentIndex: 2,
    children: [],
    referencedWidgetId: "baowuczcgg",
    isMetaWidget: true,
    creatorId: "hwgin979n4",
  },
  squbljzvqv: {
    parentColumnSpace: 1,
    parentRowSpace: 1,
    isVisible: true,
    text: "{{((currentItem) => currentItem.name)(List1_Text1_squbljzvqv.currentItem)}}",
    fontSize: "1rem",
    fontStyle: "BOLD",
    textAlign: "LEFT",
    textColor: "#231F20",
    truncateButtonColor: "#FFC13D",
    widgetName: "List1_Text1_squbljzvqv",
    shouldTruncate: false,
    overflow: "NONE",
    version: 1,
    animateLoading: true,
    searchTags: ["typography", "paragraph", "label"],
    type: "TEXT_WIDGET",
    hideCard: false,
    isDeprecated: false,
    displayName: "Text",
    key: "eezvtpz4sw",
    iconSVG: "/static/media/icon.97c59b523e6f70ba6f40a10fc2c7c5b5.svg",
    textStyle: "HEADING",
    boxShadow: "none",
    dynamicBindingPathList: [
      {
        key: "text",
      },
      {
        key: "fontFamily",
      },
      {
        key: "borderRadius",
      },
      {
        key: "currentItem",
      },
      {
        key: "currentView",
      },
    ],
    dynamicTriggerPathList: [],
    widgetId: "squbljzvqv",
    renderMode: "CANVAS",
    fontFamily: "{{appsmith.theme.fontFamily.appFont}}",
    borderRadius: "{{appsmith.theme.borderRadius.appBorderRadius}}",
    isLoading: false,
    leftColumn: 16,
    rightColumn: 28,
    topRow: 0,
    bottomRow: 4,
    parentId: "gb0vgfvp68",
    currentItem: "{{List1.listData[List1_Text1_squbljzvqv.currentIndex]}}",
    currentView: "{{{}}}",
    resizeDisabled: true,
    disablePropertyPane: true,
    dragDisabled: true,
    dropDisabled: true,
    ignoreCollision: true,
    disabledResizeHandles: [
      "left",
      "top",
      "right",
      "bottomRight",
      "topLeft",
      "topRight",
      "bottomLeft",
    ],
    currentIndex: 2,
    children: [],
    referencedWidgetId: "xy20z9gxsc",
    isMetaWidget: true,
    creatorId: "hwgin979n4",
  },
  zoq1nw5wke: {
    parentColumnSpace: 1,
    parentRowSpace: 1,
    isVisible: true,
    text: "{{((currentItem) => currentItem.id)(List1_Text2_zoq1nw5wke.currentItem)}}",
    fontSize: "1rem",
    fontStyle: "BOLD",
    textAlign: "LEFT",
    textColor: "#231F20",
    truncateButtonColor: "#FFC13D",
    widgetName: "List1_Text2_zoq1nw5wke",
    shouldTruncate: false,
    overflow: "NONE",
    version: 1,
    animateLoading: true,
    searchTags: ["typography", "paragraph", "label"],
    type: "TEXT_WIDGET",
    hideCard: false,
    isDeprecated: false,
    displayName: "Text",
    key: "eezvtpz4sw",
    iconSVG: "/static/media/icon.97c59b523e6f70ba6f40a10fc2c7c5b5.svg",
    textStyle: "BODY",
    boxShadow: "none",
    dynamicBindingPathList: [
      {
        key: "text",
      },
      {
        key: "fontFamily",
      },
      {
        key: "borderRadius",
      },
      {
        key: "currentItem",
      },
      {
        key: "currentView",
      },
    ],
    dynamicTriggerPathList: [],
    widgetId: "zoq1nw5wke",
    renderMode: "CANVAS",
    fontFamily: "{{appsmith.theme.fontFamily.appFont}}",
    borderRadius: "{{appsmith.theme.borderRadius.appBorderRadius}}",
    isLoading: false,
    leftColumn: 16,
    rightColumn: 24,
    topRow: 4,
    bottomRow: 8,
    parentId: "gb0vgfvp68",
    currentItem: "{{List1.listData[List1_Text2_zoq1nw5wke.currentIndex]}}",
    currentView: "{{{}}}",
    resizeDisabled: true,
    disablePropertyPane: true,
    dragDisabled: true,
    dropDisabled: true,
    ignoreCollision: true,
    disabledResizeHandles: [
      "left",
      "top",
      "right",
      "bottomRight",
      "topLeft",
      "topRight",
      "bottomLeft",
    ],
    currentIndex: 2,
    children: [],
    referencedWidgetId: "tsdy8whhl1",
    isMetaWidget: true,
    creatorId: "hwgin979n4",
  },
  gb0vgfvp68: {
    parentColumnSpace: 1,
    parentRowSpace: 1,
    isVisible: true,
    widgetName: "List1_Canvas2_gb0vgfvp68",
    version: 1,
    detachFromLayout: true,
    type: "CANVAS_WIDGET",
    hideCard: true,
    isDeprecated: false,
    displayName: "Canvas",
    key: "rhrv9ccmof",
    containerStyle: "none",
    canExtend: false,
    children: ["3vmg2xwodp", "squbljzvqv", "zoq1nw5wke"],
    minHeight: 1,
    widgetId: "gb0vgfvp68",
    renderMode: "CANVAS",
    boxShadow: "none",
    borderRadius: "{{appsmith.theme.borderRadius.appBorderRadius}}",
    accentColor: "{{appsmith.theme.colors.primaryColor}}",
    isLoading: false,
    leftColumn: 0,
    rightColumn: 1,
    topRow: 0,
    bottomRow: 1,
    parentId: "3g3bxw6q2z",
    dynamicBindingPathList: [
      {
        key: "borderRadius",
      },
      {
        key: "accentColor",
      },
      {
        key: "currentView",
      },
    ],
    currentView: "{{{}}}",
    resizeDisabled: true,
    disablePropertyPane: true,
    dragDisabled: true,
    dropDisabled: true,
    ignoreCollision: true,
    disabledResizeHandles: [
      "left",
      "top",
      "right",
      "bottomRight",
      "topLeft",
      "topRight",
      "bottomLeft",
    ],
    currentIndex: 2,
    referencedWidgetId: "xbbs7cls18",
    isMetaWidget: true,
    creatorId: "hwgin979n4",
  },
  "3g3bxw6q2z": {
    parentColumnSpace: 1,
    parentRowSpace: 1,
    isVisible: true,
    backgroundColor: "white",
    widgetName: "List1_Container1_3g3bxw6q2z",
    containerStyle: "card",
    borderColor: "#E0DEDE",
    borderWidth: "1",
    boxShadow: "{{appsmith.theme.boxShadow.appBoxShadow}}",
    animateLoading: true,
    children: ["gb0vgfvp68"],
    version: 1,
    searchTags: ["div", "parent", "group"],
    type: "CONTAINER_WIDGET",
    hideCard: false,
    isDeprecated: false,
    displayName: "Container",
    key: "b33ov8lfex",
    iconSVG: "/static/media/icon.1977dca3370505e2db3a8e44cfd54907.svg",
    isCanvas: true,
    dragDisabled: true,
    isDeletable: false,
    disallowCopy: true,
    disablePropertyPane: true,
    openParentPropertyPane: true,
    widgetId: "3g3bxw6q2z",
    renderMode: "CANVAS",
    borderRadius: "{{appsmith.theme.borderRadius.appBorderRadius}}",
    isLoading: false,
    leftColumn: 0,
    rightColumn: 64,
    topRow: 24,
    bottomRow: 36,
    parentId: "8ari8fii6k",
    dynamicBindingPathList: [
      {
        key: "borderRadius",
      },
      {
        key: "boxShadow",
      },
      {
        key: "data",
      },
    ],

    gap: 0,
    data: "{{\n      {\n        \n          Image1: { image: List1_Image1_3vmg2xwodp.image,isVisible: List1_Image1_3vmg2xwodp.isVisible }\n        ,\n          Text1: { isVisible: List1_Text1_squbljzvqv.isVisible,text: List1_Text1_squbljzvqv.text }\n        ,\n          Text2: { isVisible: List1_Text2_zoq1nw5wke.isVisible,text: List1_Text2_zoq1nw5wke.text }\n        \n      }\n    }}",
    resizeDisabled: true,
    dropDisabled: true,
    ignoreCollision: true,
    disabledResizeHandles: [
      "left",
      "top",
      "right",
      "bottomRight",
      "topLeft",
      "topRight",
      "bottomLeft",
    ],
    currentIndex: 2,
    referencedWidgetId: "e3bqqc9oid",
    isMetaWidget: true,
    creatorId: "hwgin979n4",
  },
};
