export default {
  Tabs: ".t--settings-category-list",
  generalTab: ".t--settings-category-general",
  advancedTab: ".t--settings-category-advanced",
  authenticationTab: ".t--settings-category-authentication",
  emailTab: ".t--settings-category-email",
  googleMapsTab: ".t--settings-category-google-maps",
  googleButton: ".t--settings-sub-category-google-auth",
  githubButton: ".t--settings-sub-category-github-auth",
  formloginButton: ".t--settings-sub-category-form-login",
  readMoreLink: ".t--read-more-link",
  versionTab: ".t--settings-category-version",
  backButton: ".t--admin-settings-back-button",
  saveButton: ".t--admin-settings-save-button",
  resetButton: ".t--admin-settings-reset-button",
  textInput: ".t--admin-settings-text-input input",
  instanceName: ".t--admin-settings-APPSMITH_INSTANCE_NAME input",
  adminEmails: ".t--admin-settings-APPSMITH_ADMIN_EMAILS input",
  fromAddress: ".t--admin-settings-APPSMITH_MAIL_FROM input",
  restartNotice: ".t--admin-settings-restart-notice",
  appsmithLogo: ".t--appsmith-logo",
  appsmithHeader: "[data-testid='t--appsmith-page-header']",
  loginWithGoogle: "[data-testid='login-with-Google']",
  loginWithGithub: "[data-testid='login-with-Github']",
  disconnectBtn: "[data-testid='disconnect-service-button']",
  formSignupDisabled: "[data-cy='APPSMITH_SIGNUP_DISABLED']",
  formLoginDisabled: "[data-cy='APPSMITH_FORM_LOGIN_DISABLED']",
};
