export default {
  Tabs: ".t--settings-category-list",
  generalTab: ".t--settings-category-general",
  advancedTab: ".t--settings-category-advanced",
  authenticationTab: ".t--settings-category-authentication",
  emailTab: ".t--settings-category-email",
  developerSettingsTab: ".t--settings-category-developer-settings",
  googleButton: ".t--settings-sub-category-google-auth",
  githubButton: ".t--settings-sub-category-github-auth",
  formloginButton: ".t--settings-sub-category-form-login",
  readMoreLink: ".t--read-more-link",
  versionTab: ".t--settings-category-version",
  backButton: ".t--admin-settings-back-button",
  saveButton: ".t--admin-settings-save-button",
  resetButton: ".t--admin-settings-reset-button",
  textInput: ".t--admin-settings-text-input input",
  instanceName: ".t--admin-settings-instanceName input",
  adminEmails: ".t--admin-settings-APPSMITH_ADMIN_EMAILS input",
  fromAddress: ".t--admin-settings-APPSMITH_MAIL_FROM input",
  restartNotice: ".t--admin-settings-restart-notice",
  appsmithStarting: "p:contains('Appsmith is starting')",
  appsmithLogo: ".t--appsmith-logo",
  appsmithHeader: "[data-testid='t--appsmith-page-header']",
  loginWithGoogle: "[data-testid='login-with-Google']",
  loginWithGithub: "[data-testid='login-with-Github']",
  disconnectBtn: "[data-testid='disconnect-service-button']",
  formSignupDisabled: "[data-testid='APPSMITH_SIGNUP_DISABLED']",
  formLoginDisabled: "[data-testid='APPSMITH_FORM_LOGIN_DISABLED']",
  embedSettings: ".t--admin-settings-APPSMITH_ALLOWED_FRAME_ANCESTORS",
  upgrade: "//button//span[text()='Upgrade']",
  accessControl: ".t--settings-category-access-control",
  auditLogs: ".t--settings-category-audit-logs",
  provisioning: ".t--settings-category-provisioning",
  upgrageLeftPane: "[data-testid='t--enterprise-settings-category-item-be']",
  brandingSubmitButton: ".t--settings-branding-submit-button",
  businessTag: "[data-testid='t--business-tag']",
  enterpriseTag: "[data-testid='t--enterprise-tag']",
  enableEmailVerificationInput: "[data-testid='emailVerificationEnabled']",
  adminSettingsCallout: "[data-testid='admin-settings-group-link']",
};
