export default {
  curlImage: ".t--curlImage",
  curlImportBtn: ".t--importBtn",
  createBlankApiCard: ".t--createBlankApiCard",
  eachProviderCard: ".t--eachProviderCard",
  nameOfApi: ".t--nameOfApi",
  ApiNameField: ".t--action-name-edit-field",
  addToPageBtn: ".t--addToPageBtn",
  ApiActionMenu: '[data-testid="more-action-trigger"]',
  ApiDeleteBtn: ".t--apiFormDeleteBtn",
  ApiRunBtn: ".t--apiFormRunBtn",
  addToPageBtnsId: ".t--addToPageButtons",
  ApiHomePage: ".t--apiHomePage",
  formActionButtons: ".t--formActionButtons",
  dataSourceField: ".t--dataSourceField",
  responseBody: ".CodeMirror-code  span.cm-string.cm-property",
  ApiVerb: ".t--apiFormHttpMethod",
  apiPaginationNextText: ".t--apiFormPaginationNext",
  apiPaginationPrevText: ".t--apiFormPaginationPrev",
  apiPaginationPrevTest: ".t--apiFormPaginationPrevTest",
  apiPaginationNextTest: ".t--apiFormPaginationNextTest",
  apiPaginationTab: ".t--apiFormPaginationType label:contains('Paginate with Response URL') input",
  apiTab: ".react-tabs__tab-list li",
  bodyType: ".t--apiFormPostBodyType",
  bodyTypeSelected: '[data-testid="t--api-body-tab-switch"] .t--tab-selected',
  bodyTab: "Body",
  jsonBodyTab: "[data-testid=tab--JSON]",
  headersTab: "Header",
  jsonResponseTab: "[data-value='JSON']",
  tableResponseTab: "[data-value='TABLE']",
  rawResponseTab: "[data-value='RAW']",
  datasourcesRightPane: "button[role='tab'] span:contains('Datasources')",
  connectionsRightPane: "button[role='tab'] span:contains('Connections')",
  httpDropDownOptions: ".rc-select-item",
  codeEditorWrapper: ".t--code-editor-wrapper",
  apiSearchHint: ".datasource-hint",
  slashCommandButton: ".commands-button",
};
