export default {
  gitRepoInput: ".t--git-repo-input",
  generateDeployKeyBtn: ".t--generate-deploy-key-button",
  connectSubmitBtn: ".t--connect-submit-btn",
  createNewBranchButton: ".t--create-new-branch-button",
  createNewBranchSubmitbutton: ".t--create-new-branch-submit-button",
  branchButton: ".t--branch-button",
  commitCommentInput: ".t--commit-comment-input",
  commitButton: ".t--commit-button",
  pullButton: ".t--pull-button",
  openRepoButton: ".t--open-repo-button",
  gitConfigNameInput: ".t--git-config-name-input",
  gitConfigEmailInput: ".t--git-config-email-input",
  branchSearchInput: ".t--branch-search-input",
  branchListItem: ".t--branch-item",
  closeGitSyncModal: ".t--close-git-sync-modal",
  closeRevokeModal: ".t--close-disconnect-modal",
  gitSyncModal: ".git-sync-modal",
  bottomBarCommitButton: ".t--bottom-bar-commit",
  bottomBarMergeButton: ".t--bottom-bar-merge",
  bottomBarPullButton: ".t--bottom-bar-pull",
  mergeBranchDropdownDestination: ".t--merge-branch-dropdown-destination",
  mergeCTA: ".t--git-merge-button",
  loaderQuickGitAction: ".t--loader-quick-git-action",
  copySshKey: ".t--copy-ssh-key",
  connetStatusbar: ".t--connect-statusbar",
  useGlobalGitConfig: "[data-cy=t--use-global-config-checkbox]",
  connectGitBottomBar: ".t--connect-git-bottom-bar",
  disabledConnectGitBottomBar: ".t--disabled-connect-git-bottom-bar",
  syncBranches: ".t--sync-branches",
  closeBranchList: ".t--close-branch-list",
  learnMoreDeployKey: "//a[text()='Learn More']",
  learnMoreSshUrl: ".t--learn-more-ssh-url",
  readDocument: ".t--read-document",
  gitConnectErrorLearnMore:
    ".t--git-connection-error .t--notification-banner-learn-more",
  deployPreview: ".t--git-deploy-preview",
  mergeButton: ".t--git-merge-button",
  disconnectIcon: ".t--git-disconnect-icon",
  disconnectGitModal: ".disconnect-git-modal",
  disconnectButton: ".t--git-revoke-button",
  closeDisconnectModal: ".t--close-disconnect-modal",
  disconnectAppNameInput: ".t--git-app-name-input",
  repoLimitExceededErrorModal: ".t--git-repo-limited-modal",
  contactSalesButton: ".t--contact-sales-button",
  connectedApplication: ".t--connected-app-wrapper",
  diconnectLink: ".t--disconnect-link",
  disconnectLearnMoreLink: ".t--disconnect-learn-more",
  learnMoreOnRepoLimitModal: ".t--learn-more-repo-limit-modal",
  gitSyncModalDeployTab: "[data-cy=t--tab-DEPLOY]",
  gitPullCount: ".t--bottom-bar-pull .count",
  gitConnectionContainer: "[data-test=t--git-connection-container]",
  gitRemoteURLContainer: "[data-test=t--remote-url-container]",
};
