export default {
  gitRepoInput: ".t--git-repo-input",
  generateDeployKeyBtn: ".t--generate-deploy-key-button",
  connectSubmitBtn: ".t--connect-submit-btn",
  createNewBranchButton: ".t--create-new-branch-button",
  createNewBranchSubmitbutton: ".t--create-new-branch-submit-button",
  branchButton: ".t--branch-button",
  commitButton: ".t--commit-button",
  pullButton: ".t--pull-button",
  openRepoButton: ".t--open-repo-button",
  gitConfigNameInput: ".t--git-config-name-input",
  gitConfigEmailInput: ".t--git-config-email-input",
  branchSearchInput: ".t--branch-search-input",
  branchListItem: ".t--branch-item",
  closeGitSyncModal: ".t--close-git-sync-modal",
  bottomBarMergeButton: ".t--bottom-bar-merge",
  bottomBarPullButton: ".t--bottom-bar-pull",
  mergeBranchDropdownDestination: ".t--merge-branch-dropdown-destination",
  mergeCTA: ".t--merge",
  loaderQuickGitAction: ".t--loader-quick-git-action",
  copySshKey: ".t--copy-ssh-key",
  connetStatusbar: ".t--connect-statusbar",
  useGlobalGitConfig: "[data-cy=t--use-global-config-checkbox]",
};
