import type { CanvasWidgetsReduxState } from "../reducers/entityReducers/canvasWidgetsReducer";
import { generateReactKey } from "../utils/generators";

export default (): CanvasWidgetsReduxState => {
  const tableWidgetID = generateReactKey();
  return {
    "0": {
      widgetName: "MainContainer",
      backgroundColor: "none",
      rightColumn: 4896,
      snapColumns: 64,
      detachFromLayout: true,
      widgetId: "0",
      topRow: 0,
      bottomRow: 1282,
      containerStyle: "none",
      snapRows: 124,
      parentRowSpace: 1,
      type: "CANVAS_WIDGET",
      canExtend: true,
      version: 83,
      minHeight: 1292,
      dynamicTriggerPathList: [],
      parentColumnSpace: 1,
      dynamicBindingPathList: [],
      leftColumn: 0,
      children: [tableWidgetID],
    },
    [tableWidgetID]: {
      boxShadow: "{{appsmith.theme.boxShadow.appBoxShadow}}",
      borderColor: "#E0DEDE",
      isVisibleDownload: true,
      iconSVG:
        "https://appcdn.appsmith.com/static/media/icon.e6911f8bb94dc6c4a102a74740c41763.svg",
      topRow: 7,
      isSortable: true,
      type: "TABLE_WIDGET_V2",
      inlineEditingSaveOption: "ROW_LEVEL",
      animateLoading: true,
      dynamicBindingPathList: [
        {
          key: "accentColor",
        },
        {
          key: "borderRadius",
        },
        {
          key: "boxShadow",
        },
      ],
      needsHeightForContent: true,
      leftColumn: 15,
      delimiter: ",",
      defaultSelectedRowIndex: 0,
      accentColor: "{{appsmith.theme.colors.primaryColor}}",
      isVisibleFilters: true,
      isVisible: true,
      enableClientSideSearch: true,
      version: 2,
      totalRecordsCount: 0,
      tags: ["Suggested", "Display"],
      isLoading: false,
      childStylesheet: {
        button: {
          buttonColor: "{{appsmith.theme.colors.primaryColor}}",
          borderRadius: "{{appsmith.theme.borderRadius.appBorderRadius}}",
          boxShadow: "none",
        },
        menuButton: {
          menuColor: "{{appsmith.theme.colors.primaryColor}}",
          borderRadius: "{{appsmith.theme.borderRadius.appBorderRadius}}",
          boxShadow: "none",
        },
        iconButton: {
          buttonColor: "{{appsmith.theme.colors.primaryColor}}",
          borderRadius: "{{appsmith.theme.borderRadius.appBorderRadius}}",
          boxShadow: "none",
        },
        editActions: {
          saveButtonColor: "{{appsmith.theme.colors.primaryColor}}",
          saveBorderRadius: "{{appsmith.theme.borderRadius.appBorderRadius}}",
          discardButtonColor: "{{appsmith.theme.colors.primaryColor}}",
          discardBorderRadius:
            "{{appsmith.theme.borderRadius.appBorderRadius}}",
        },
      },
      borderRadius: "{{appsmith.theme.borderRadius.appBorderRadius}}",
      columnUpdatedAt: 1691657346666,
      defaultSelectedRowIndices: [0],
      mobileBottomRow: 37,
      widgetName: "Table1",
      defaultPageSize: 0,
      columnOrder: [],
      dynamicPropertyPathList: [],
      displayName: "Table",
      bottomRow: 35,
      columnWidthMap: {},
      parentRowSpace: 10,
      hideCard: false,
      mobileRightColumn: 49,
      parentColumnSpace: 16,
      borderWidth: "1",
      primaryColumns: {},
      key: "6qom3ihd1l",
      canFreezeColumn: true,
      isDeprecated: false,
      rightColumn: 49,
      textSize: "0.875rem",
      widgetId: tableWidgetID,
      minWidth: 450,
      tableData: "",
      label: "Data",
      searchKey: "",
      parentId: "0",
      renderMode: "CANVAS",
      mobileTopRow: 9,
      horizontalAlignment: "LEFT",
      isVisibleSearch: true,
      responsiveBehavior: "fill",
      mobileLeftColumn: 15,
      isVisiblePagination: true,
      verticalAlignment: "CENTER",
    },
  } as unknown as CanvasWidgetsReduxState;
};
