create unique index if not exists config_name_key on config(name) ;
create unique index if not exists prt_email_key on password_reset_token(email);
create unique index if not exists user_email_key on "user"(email);
create unique index if not exists sequence_name_key on sequence(name);
create unique index if not exists plugin_name_package_name_version_idx on plugin(plugin_name, package_name, version) NULLS NOT DISTINCT;
create unique index if not exists user_id_key on user_data(user_id);
create unique index if not exists datasource_workspace_name_deleted_idx on datasource(workspace_id, name, deleted_at) NULLS NOT DISTINCT;
create unique index if not exists application_workspace_name_deleted_git_application_metadata_idx on application(workspace_id, name, deleted_at, (git_application_metadata ->> 'remoteUrl'), (git_application_metadata ->>'branchName')) NULLS NOT DISTINCT;
create unique index if not exists dss_datasource_env_idx on datasource_storage_structure(datasource_id, environment_id) NULLS NOT DISTINCT;
create unique index if not exists application_snapshot_application_chunkOrder_idx on application_snapshot(application_id, chunk_order) NULLS NOT DISTINCT;
