import { PluginType, PaginationType } from "entities/Action";
import {
  DataTree,
  EvaluationSubstitutionType,
  DataTreeWidget,
  DataTreeAppsmith,
  ENTITY_TYPE,
  DataTreeAction,
} from "entities/DataTree/dataTreeFactory";

export const unEvalTree = {
  MainContainer: {
    widgetName: "MainContainer",
    backgroundColor: "none",
    rightColumn: 2220,
    snapColumns: 64,
    detachFromLayout: true,
    widgetId: "0",
    topRow: 0,
    bottomRow: 640,
    containerStyle: "none",
    snapRows: 113,
    parentRowSpace: 1,
    type: "CANVAS_WIDGET",
    canExtend: true,
    version: 52,
    minHeight: 620,
    parentColumnSpace: 1,
    dynamicBindingPathList: [],
    leftColumn: 0,
    children: ["j9dpft2lpu", "l0yem4eh6l"],
    defaultProps: {},
    defaultMetaProps: [],
    logBlackList: {},
    meta: {},
    propertyOverrideDependency: {},
    overridingPropertyPaths: {},
    reactivePaths: {},
    triggerPaths: {},
    validationPaths: {},
    ENTITY_TYPE: ENTITY_TYPE.WIDGET,
    privateWidgets: {},
  },
  Button1: {
    widgetName: "Button1",
    buttonColor: "#03B365",
    displayName: "Button",
    iconSVG: "/static/media/icon.cca02633.svg",
    topRow: 15,
    bottomRow: 19,
    parentRowSpace: 10,
    type: "BUTTON_WIDGET",
    hideCard: false,
    animateLoading: true,
    parentColumnSpace: 26.421875,
    dynamicTriggerPathList: [],
    leftColumn: 20,
    dynamicBindingPathList: [],
    text: "button1",
    isDisabled: false,
    key: "r6h8y6dc8i",
    rightColumn: 36,
    isDefaultClickDisabled: true,
    widgetId: "j9dpft2lpu",
    isVisible: true,
    recaptchaType: "V3",
    version: 1,
    parentId: "0",
    renderMode: "CANVAS",
    isLoading: false,
    buttonVariant: "PRIMARY",
    placement: "CENTER",
    defaultProps: {},
    defaultMetaProps: ["recaptchaToken"],
    logBlackList: {},
    meta: {},
    propertyOverrideDependency: {},
    overridingPropertyPaths: {},
    reactivePaths: {
      recaptchaToken: EvaluationSubstitutionType.TEMPLATE,
      text: EvaluationSubstitutionType.TEMPLATE,
      tooltip: EvaluationSubstitutionType.TEMPLATE,
      googleRecaptchaKey: EvaluationSubstitutionType.TEMPLATE,
      recaptchaType: EvaluationSubstitutionType.TEMPLATE,
      isVisible: EvaluationSubstitutionType.TEMPLATE,
      isDisabled: EvaluationSubstitutionType.TEMPLATE,
      animateLoading: EvaluationSubstitutionType.TEMPLATE,
      buttonVariant: EvaluationSubstitutionType.TEMPLATE,
      placement: EvaluationSubstitutionType.TEMPLATE,
    },
    triggerPaths: {
      onClick: true,
    },
    validationPaths: {
      text: {
        type: "TEXT",
      },
      tooltip: {
        type: "TEXT",
      },
      googleRecaptchaKey: {
        type: "TEXT",
      },
      recaptchaType: {
        type: "TEXT",
        params: {
          allowedValues: ["V3", "V2"],
          default: "V3",
        },
      },
      isVisible: {
        type: "BOOLEAN",
      },
      isDisabled: {
        type: "BOOLEAN",
      },
      animateLoading: {
        type: "BOOLEAN",
      },
      buttonVariant: {
        type: "TEXT",
        params: {
          allowedValues: ["PRIMARY", "SECONDARY", "TERTIARY"],
          default: "PRIMARY",
        },
      },
      placement: {
        type: "TEXT",
        params: {
          allowedValues: ["START", "BETWEEN", "CENTER"],
          default: "CENTER",
        },
      },
    },
    ENTITY_TYPE: ENTITY_TYPE.WIDGET,
    privateWidgets: {},
  },
  Button2: {
    widgetName: "Button2",
    buttonColor: "#03B365",
    displayName: "Button",
    iconSVG: "/static/media/icon.cca02633.svg",
    topRow: 25,
    bottomRow: 29,
    parentRowSpace: 10,
    type: "BUTTON_WIDGET",
    hideCard: false,
    animateLoading: true,
    parentColumnSpace: 26.421875,
    dynamicTriggerPathList: [],
    leftColumn: 20,
    dynamicBindingPathList: [
      {
        key: "text",
      },
    ],
    text: "{{Button1.text}}",
    isDisabled: false,
    key: "r6h8y6dc8i",
    rightColumn: 36,
    isDefaultClickDisabled: true,
    widgetId: "l0yem4eh6l",
    isVisible: true,
    recaptchaType: "V3",
    version: 1,
    parentId: "0",
    renderMode: "CANVAS",
    isLoading: false,
    buttonVariant: "PRIMARY",
    placement: "CENTER",
    defaultProps: {},
    defaultMetaProps: ["recaptchaToken"],
    logBlackList: {},
    meta: {},
    propertyOverrideDependency: {},
    overridingPropertyPaths: {},
    reactivePaths: {
      recaptchaToken: EvaluationSubstitutionType.TEMPLATE,
      text: EvaluationSubstitutionType.TEMPLATE,
      tooltip: EvaluationSubstitutionType.TEMPLATE,
      googleRecaptchaKey: EvaluationSubstitutionType.TEMPLATE,
      recaptchaType: EvaluationSubstitutionType.TEMPLATE,
      isVisible: EvaluationSubstitutionType.TEMPLATE,
      isDisabled: EvaluationSubstitutionType.TEMPLATE,
      animateLoading: EvaluationSubstitutionType.TEMPLATE,
      buttonVariant: EvaluationSubstitutionType.TEMPLATE,
      placement: EvaluationSubstitutionType.TEMPLATE,
    },
    triggerPaths: {
      onClick: true,
    },
    validationPaths: {
      text: {
        type: "TEXT",
      },
      tooltip: {
        type: "TEXT",
      },
      googleRecaptchaKey: {
        type: "TEXT",
      },
      recaptchaType: {
        type: "TEXT",
        params: {
          allowedValues: ["V3", "V2"],
          default: "V3",
        },
      },
      isVisible: {
        type: "BOOLEAN",
      },
      isDisabled: {
        type: "BOOLEAN",
      },
      animateLoading: {
        type: "BOOLEAN",
      },
      buttonVariant: {
        type: "TEXT",
        params: {
          allowedValues: ["PRIMARY", "SECONDARY", "TERTIARY"],
          default: "PRIMARY",
        },
      },
      placement: {
        type: "TEXT",
        params: {
          allowedValues: ["START", "BETWEEN", "CENTER"],
          default: "CENTER",
        },
      },
    },
    ENTITY_TYPE: ENTITY_TYPE.WIDGET,
    privateWidgets: {},
  },
  pageList: [
    {
      pageName: "Page1",
      pageId: "6200d1a2b5bfc0392b959cae",
      isDefault: true,
      isHidden: false,
    },
    {
      pageName: "Page2",
      pageId: "621e22cf2b75295c1c165fa6",
      isDefault: false,
      isHidden: false,
    },
    {
      pageName: "Page3",
      pageId: "6220c268c48234070f8ac65a",
      isDefault: false,
      isHidden: false,
    },
  ],
  appsmith: {
    user: {
      email: "rathod@appsmith.com",
      organizationIds: [
        "6218a61972ccd9145ec78c57",
        "621913df0276eb01d22fec44",
        "60caf8edb1e47a1315f0c48f",
        "609114fe05c4d35a9f6cbbf2",
      ],
      username: "rathod@appsmith.com",
      name: "Rishabh",
      commentOnboardingState: "RESOLVED",
      role: "engineer",
      useCase: "personal project",
      enableTelemetry: false,
      emptyInstance: false,
      accountNonExpired: true,
      accountNonLocked: true,
      credentialsNonExpired: true,
      isAnonymous: false,
      isEnabled: true,
      isSuperUser: false,
      isConfigurable: true,
    },
    URL: {
      fullPath:
        "https://dev.appsmith.com/applications/6200d1a2b5bfc0392b959cab/pages/6220c268c48234070f8ac65a/edit?a=b",
      host: "dev.appsmith.com",
      hostname: "dev.appsmith.com",
      queryParams: {
        a: "b",
      },
      protocol: "https:",
      pathname:
        "/applications/6200d1a2b5bfc0392b959cab/pages/6220c268c48234070f8ac65a/edit",
      port: "",
      hash: "",
    },
    store: {
      textColor: "#DF7E65",
    },
    geolocation: {
      canBeRequested: true,
    },
    mode: "EDIT",
    ENTITY_TYPE: ENTITY_TYPE.APPSMITH,
  },
};

export const asyncTagUnevalTree: DataTree = {
  Api1: {
    run: {},
    clear: {},
    actionId: "6279ff0c0b47255c280c4631",
    name: "Api1",
    pluginId: "5ca385dc81b37f0004b4db85",
    pluginType: PluginType.API,
    config: {
      timeoutInMillisecond: 10000,
      paginationType: PaginationType.NONE,
      path: "/echo/get",
      queryParameters: [],
      pluginSpecifiedTemplates: [
        {
          value: true,
        },
      ],
      formData: {
        apiContentType: "none",
      },
    },
    dynamicBindingPathList: [],
    data: {
      args: {},
      url: "https://mock-api.appsmith.com/echo/get",
      headers: {
        accept: "*/*",
        authorization: "Basic dGVzdDo=",
        "cloudfront-forwarded-proto": "https",
        "cloudfront-is-desktop-viewer": "true",
        "cloudfront-is-mobile-viewer": "false",
        "cloudfront-is-smarttv-viewer": "false",
        "cloudfront-is-tablet-viewer": "false",
        "cloudfront-viewer-country": "US",
        host: "mock-api.appsmith.com",
        test: "val",
        "user-agent": "ReactorNetty/1.0.15",
        via: "1.1 290e11478c5b9149e389233998147082.cloudfront.net (CloudFront)",
        "x-amz-cf-id":
          "xKBvLoL6ObBLGeqyky6ZuXl2I9ZgQu58BKzcYvR5VDgDdKgCexv8Zg==",
        "x-amzn-trace-id": "Root=1-627ba66a-2f010d2a5dcfb14009419780",
        "x-forwarded-for": "18.223.74.85, 64.252.147.156",
        "x-forwarded-port": "443",
        "x-forwarded-proto": "https",
        "x-request-id": "2c751e3c-7d54-4f08-908a-a9c909d4f12b",
        "content-length": 0,
      },
    },
    responseMeta: {
      statusCode: "200 OK",
      isExecutionSuccess: true,
      headers: {
        "Content-Type": ["application/json; charset=utf-8"],
        Connection: ["keep-alive"],
        Date: ["Wed, 11 May 2022 12:04:58 GMT"],
        "x-amzn-RequestId": ["2c751e3c-7d54-4f08-908a-a9c909d4f12b"],
        "x-amzn-Remapped-content-length": ["802"],
        "x-amz-apigw-id": ["R9bwsHujiYcF0IQ="],
        etag: ['W/"322-KKw8fZnypLi/dqYHfS13soe8o2s"'],
        "x-powered-by": ["Express"],
        "X-Amzn-Trace-Id": [
          "Root=1-627ba66a-2f010d2a5dcfb14009419780;Sampled=0",
        ],
        "X-Cache": ["Miss from cloudfront"],
        Via: [
          "1.1 290e11478c5b9149e389233998147082.cloudfront.net (CloudFront)",
        ],
        "X-Amz-Cf-Pop": ["YTO50-C1"],
        "X-Amz-Cf-Id": [
          "xKBvLoL6ObBLGeqyky6ZuXl2I9ZgQu58BKzcYvR5VDgDdKgCexv8Zg==",
        ],
        "content-length": ["802"],
        "X-APPSMITH-DATATYPE": ["JSON"],
      },
    },
    ENTITY_TYPE: ENTITY_TYPE.ACTION,
    isLoading: false,
    bindingPaths: {
      "config.path": EvaluationSubstitutionType.TEMPLATE,
      "config.body": EvaluationSubstitutionType.SMART_SUBSTITUTE,
    },
    reactivePaths: {
      data: EvaluationSubstitutionType.TEMPLATE,
      isLoading: EvaluationSubstitutionType.TEMPLATE,
      datasourceUrl: EvaluationSubstitutionType.TEMPLATE,
      "config.path": EvaluationSubstitutionType.TEMPLATE,
      "config.body": EvaluationSubstitutionType.SMART_SUBSTITUTE,
    },
    dependencyMap: {
      "config.body": ["config.pluginSpecifiedTemplates[0].value"],
    },
    logBlackList: {},
    datasourceUrl: "",
  },
  JSObject1: {
    name: "JSObject1",
    actionId: "627217a38a368d6f1efcd0d8",
    pluginType: PluginType.JS,
    ENTITY_TYPE: ENTITY_TYPE.JSACTION,
    body:
      "export default { \n\tmyFun1: () => {\n\t\treturn JSObject2.callApi();\n\t},\n}",
    meta: {
      myFun1: {
        arguments: [],
        isAsync: false,
        confirmBeforeExecute: false,
      },
    },
    bindingPaths: {
      body: EvaluationSubstitutionType.SMART_SUBSTITUTE,
      myFun1: EvaluationSubstitutionType.SMART_SUBSTITUTE,
    },
    reactivePaths: {
      body: EvaluationSubstitutionType.SMART_SUBSTITUTE,
      myFun1: EvaluationSubstitutionType.SMART_SUBSTITUTE,
    },
    dynamicBindingPathList: [
      {
        key: "body",
      },
      {
        key: "myFun1",
      },
    ],
    variables: [],
    dependencyMap: {
      body: ["myFun1"],
    },
    myFun1: {
      data: {},
    },
  },
  JSObject2: {
    name: "JSObject2",
    actionId: "627babc60b47255c28138865",
    pluginType: PluginType.JS,
    ENTITY_TYPE: ENTITY_TYPE.JSACTION,
    body:
      "export default {\n\tcallApi: () => {\n\t\treturn Api1.run()\n\t},\n}",
    meta: {
      callApi: {
        arguments: [],
        isAsync: false,
        confirmBeforeExecute: false,
      },
    },
    bindingPaths: {
      body: EvaluationSubstitutionType.SMART_SUBSTITUTE,
      callApi: EvaluationSubstitutionType.SMART_SUBSTITUTE,
    },
    reactivePaths: {
      body: EvaluationSubstitutionType.SMART_SUBSTITUTE,
      callApi: EvaluationSubstitutionType.SMART_SUBSTITUTE,
    },
    dynamicBindingPathList: [
      {
        key: "body",
      },
      {
        key: "callApi",
      },
    ],
    variables: [],
    dependencyMap: {
      body: ["callApi"],
    },
    callApi: {
      data: {},
    },
  },
  MainContainer: ({
    widgetName: "MainContainer",
    backgroundColor: "none",
    rightColumn: 4896,
    snapColumns: 64,
    detachFromLayout: true,
    widgetId: "0",
    topRow: 0,
    bottomRow: 1320,
    containerStyle: "none",
    snapRows: 125,
    parentRowSpace: 1,
    type: "CANVAS_WIDGET",
    canExtend: true,
    version: 57,
    minHeight: 1292,
    parentColumnSpace: 1,
    dynamicBindingPathList: [],
    leftColumn: 0,
    children: [],
    defaultProps: {},
    defaultMetaProps: [],
    logBlackList: {},
    meta: {},
    propertyOverrideDependency: {},
    overridingPropertyPaths: {},
    bindingPaths: {},
    reactivePaths: {},
    triggerPaths: {},
    validationPaths: {},
    ENTITY_TYPE: ENTITY_TYPE.WIDGET,
    privateWidgets: {},
  } as unknown) as DataTreeWidget,
  pageList: [
    {
      pageName: "Page1",
      pageId: "6272179d8a368d6f1efcd0d2",
      isDefault: true,
      isHidden: false,
      slug: "page1",
    },
  ],
  appsmith: ({
    user: {
      email: "anand@appsmith.com",
      organizationIds: [
        "61431979a67ce2289d3c7c6d",
        "61431a95a67ce2289d3c7c74",
        "5f7add8687af934ed846dd6a",
        "5f9fd13993794869fdbb8dcb",
        "618b5af5da7cd651ee273112",
        "604ef1c5c046f668d7bcc051",
        "61b3389cd3e4214454c26bd1",
        "61b3389cd3e4214454c26bd2",
        "620a0d896b4b1e154a3c057a",
        "620b37296b4b1e154a3c1fd7",
        "60c1a5273535574772b6377b",
        "6066e71a034ece74b1481ad2",
        "623b36e34d9aea1b062b15b3",
        "623b37de4d9aea1b062b170f",
        "624fe51b457aa64da9e02ed3",
        "6176537b515e45415cc7fd15",
        "6206486d6b4b1e154a3be208",
      ],
      username: "anand@appsmith.com",
      name: "Anand Srinivasan",
      enableTelemetry: true,
      idToken: {
        sub: "109879730040206968321",
        email_verified: true,
        name: "Anand Srinivasan",
        given_name: "Anand",
        locale: "en",
        hd: "appsmith.com",
        family_name: "Srinivasan",
        picture:
          "https://lh3.googleusercontent.com/a-/AOh14Gi4HfYY0sKhaG93YAHB_E5-dL4BkFxdf8ZfQ2w7=s96-c",
        email: "anand@appsmith.com",
      },
      accountNonExpired: true,
      accountNonLocked: true,
      credentialsNonExpired: true,
      emptyInstance: false,
      isAnonymous: false,
      isEnabled: true,
      isSuperUser: false,
      isConfigurable: true,
    },
    URL: {
      fullPath:
        "https://app.appsmith.com/app/untitled-application-25/page1-6272179d8a368d6f1efcd0d2/edit",
      host: "app.appsmith.com",
      hostname: "app.appsmith.com",
      queryParams: {},
      protocol: "https:",
      pathname:
        "/app/untitled-application-25/page1-6272179d8a368d6f1efcd0d2/edit",
      port: "",
      hash: "",
    },
    store: {},
    geolocation: {
      canBeRequested: true,
    },
    mode: "EDIT",
    ENTITY_TYPE: ENTITY_TYPE.APPSMITH,
  } as unknown) as DataTreeAppsmith,
};

export const arrayAccessorCyclicDependency: Record<string, DataTree> = {
  initUnEvalTree: {
    Api1: ({
      run: {},
      clear: {},
      actionId: "6285d928db0f9c6e620d454a",
      name: "Api1",
      pluginId: "5ca385dc81b37f0004b4db85",
      pluginType: PluginType.API,
      config: {
        timeoutInMillisecond: 10000,
        paginationType: PaginationType.NONE,
        path: "/posts",
        queryParameters: [
          {
            key: "",
            value: "",
          },
          {
            key: "",
            value: "",
          },
        ],
        pluginSpecifiedTemplates: [
          {
            value: true,
          },
        ],
        formData: {
          apiContentType: "none",
        },
      },
      dynamicBindingPathList: [],
      responseMeta: {
        isExecutionSuccess: false,
      },
      ENTITY_TYPE: ENTITY_TYPE.ACTION,
      isLoading: false,
      bindingPaths: {
        "config.path": EvaluationSubstitutionType.TEMPLATE,
        "config.body": EvaluationSubstitutionType.SMART_SUBSTITUTE,
        "config.queryParameters[0].key": EvaluationSubstitutionType.TEMPLATE,
        "config.queryParameters[0].value": EvaluationSubstitutionType.TEMPLATE,
        "config.queryParameters[1].key": EvaluationSubstitutionType.TEMPLATE,
        "config.queryParameters[1].value": EvaluationSubstitutionType.TEMPLATE,
      },
      reactivePaths: {
        data: EvaluationSubstitutionType.TEMPLATE,
        isLoading: EvaluationSubstitutionType.TEMPLATE,
        datasourceUrl: EvaluationSubstitutionType.TEMPLATE,
        "config.path": EvaluationSubstitutionType.TEMPLATE,
        "config.body": EvaluationSubstitutionType.SMART_SUBSTITUTE,
        "config.queryParameters[0].key": EvaluationSubstitutionType.TEMPLATE,
        "config.queryParameters[0].value": EvaluationSubstitutionType.TEMPLATE,
        "config.queryParameters[1].key": EvaluationSubstitutionType.TEMPLATE,
        "config.queryParameters[1].value": EvaluationSubstitutionType.TEMPLATE,
      },
      dependencyMap: {
        "config.body": ["config.pluginSpecifiedTemplates[0].value"],
      },
      logBlackList: {},
      datasourceUrl: "https://jsonplaceholder.typicode.com",
    } as unknown) as DataTreeAction,
    MainContainer: ({
      widgetName: "MainContainer",
      backgroundColor: "none",
      rightColumn: 4896,
      snapColumns: 64,
      detachFromLayout: true,
      widgetId: "0",
      topRow: 0,
      bottomRow: 1320,
      containerStyle: "none",
      snapRows: 125,
      parentRowSpace: 1,
      type: "CANVAS_WIDGET",
      canExtend: true,
      version: 58,
      minHeight: 1292,
      dynamicTriggerPathList: [],
      parentColumnSpace: 1,
      dynamicBindingPathList: [],
      leftColumn: 0,
      children: ["1p9hcl50i8"],
      defaultProps: {},
      defaultMetaProps: [],
      logBlackList: {},
      propertyOverrideDependency: {},
      overridingPropertyPaths: {},
      bindingPaths: {},
      reactivePaths: {},
      triggerPaths: {},
      validationPaths: {},
      ENTITY_TYPE: ENTITY_TYPE.WIDGET,
      privateWidgets: {},
      meta: {},
    } as unknown) as DataTreeWidget,
    Text1: ({
      widgetName: "Text1",
      displayName: "Text",
      iconSVG: "/static/media/icon.97c59b52.svg",
      topRow: 14,
      bottomRow: 18,
      parentRowSpace: 10,
      type: "TEXT_WIDGET",
      hideCard: false,
      animateLoading: true,
      overflow: "NONE",
      fontFamily: "{{appsmith.theme.fontFamily.appFont}}",
      parentColumnSpace: 11.796875,
      dynamicTriggerPathList: [],
      leftColumn: 21,
      dynamicBindingPathList: [
        {
          key: "fontFamily",
        },
        {
          key: "borderRadius",
        },
        {
          key: "text",
        },
        {
          key: "value",
        },
      ],
      shouldTruncate: false,
      truncateButtonColor: "#FFC13D",
      text: "{{\nApi1.data[2].id\n}}",
      key: "ljtoov0cml",
      rightColumn: 37,
      textAlign: "LEFT",
      widgetId: "1p9hcl50i8",
      isVisible: true,
      fontStyle: "BOLD",
      textColor: "#231F20",
      version: 1,
      parentId: "0",
      renderMode: "CANVAS",
      isLoading: false,
      borderRadius: "{{appsmith.theme.borderRadius.appBorderRadius}}",
      fontSize: "1rem",
      value: "{{ Text1.text }}",
      defaultProps: {},
      defaultMetaProps: [],
      logBlackList: {
        value: true,
      },
      propertyOverrideDependency: {},
      overridingPropertyPaths: {},
      bindingPaths: {
        text: EvaluationSubstitutionType.TEMPLATE,
        isVisible: EvaluationSubstitutionType.TEMPLATE,
        animateLoading: EvaluationSubstitutionType.TEMPLATE,
        disableLink: EvaluationSubstitutionType.TEMPLATE,
        backgroundColor: EvaluationSubstitutionType.TEMPLATE,
        textColor: EvaluationSubstitutionType.TEMPLATE,
        borderColor: EvaluationSubstitutionType.TEMPLATE,
        borderWidth: EvaluationSubstitutionType.TEMPLATE,
        fontSize: EvaluationSubstitutionType.TEMPLATE,
        fontFamily: EvaluationSubstitutionType.TEMPLATE,
        fontStyle: EvaluationSubstitutionType.TEMPLATE,
        textAlign: EvaluationSubstitutionType.TEMPLATE,
      },
      reactivePaths: {
        value: EvaluationSubstitutionType.TEMPLATE,
        fontFamily: EvaluationSubstitutionType.TEMPLATE,
        borderRadius: EvaluationSubstitutionType.TEMPLATE,
        text: EvaluationSubstitutionType.TEMPLATE,
        isVisible: EvaluationSubstitutionType.TEMPLATE,
        animateLoading: EvaluationSubstitutionType.TEMPLATE,
        disableLink: EvaluationSubstitutionType.TEMPLATE,
        backgroundColor: EvaluationSubstitutionType.TEMPLATE,
        textColor: EvaluationSubstitutionType.TEMPLATE,
        borderColor: EvaluationSubstitutionType.TEMPLATE,
        borderWidth: EvaluationSubstitutionType.TEMPLATE,
        fontSize: EvaluationSubstitutionType.TEMPLATE,
        fontStyle: EvaluationSubstitutionType.TEMPLATE,
        textAlign: EvaluationSubstitutionType.TEMPLATE,
      },
      triggerPaths: {},
      validationPaths: {
        text: {
          type: "TEXT",
          params: {
            limitLineBreaks: true,
          },
        },
        isVisible: {
          type: "BOOLEAN",
        },
        animateLoading: {
          type: "BOOLEAN",
        },
        disableLink: {
          type: "BOOLEAN",
        },
        backgroundColor: {
          type: "TEXT",
          params: {
            regex: {},
            expected: {
              type: "string (HTML color name or HEX value)",
              example: "red | #9C0D38",
              autocompleteDataType: "STRING",
            },
          },
        },
        textColor: {
          type: "TEXT",
          params: {
            regex: {},
          },
        },
        borderColor: {
          type: "TEXT",
        },
        borderWidth: {
          type: "NUMBER",
        },
        fontSize: {
          type: "TEXT",
        },
        fontFamily: {
          type: "TEXT",
        },
        fontStyle: {
          type: "TEXT",
        },
        textAlign: {
          type: "TEXT",
        },
      },
      ENTITY_TYPE: ENTITY_TYPE.WIDGET,
      privateWidgets: {},
      meta: {},
    } as unknown) as DataTreeWidget,
    pageList: [
      {
        pageName: "Page1",
        pageId: "6285d928db0f9c6e620d4548",
        isDefault: true,
        isHidden: false,
        slug: "page1",
      },
    ],
    appsmith: ({
      user: {
        email: "anand1@appsmith.com",
        organizationIds: [
          "617150deb7de236aa183edab",
          "6171510ab7de236aa183edb0",
          "61715151b7de236aa183edb7",
          "61715172b7de236aa183edbb",
          "6171518fb7de236aa183edbf",
          "615d6680d513605e3f67af87",
          "61763f53ba7e887d03bc3575",
          "61763f74ba7e887d03bc3579",
          "6176489fba7e887d03bc359e",
          "617648bfba7e887d03bc35a2",
          "617648deba7e887d03bc35a6",
          "61764b81ba7e887d03bc35af",
          "61764bc2ba7e887d03bc35b7",
          "61764ebbba7e887d03bc35c4",
          "61764edcba7e887d03bc35c8",
          "61764efbba7e887d03bc35cc",
          "61779c0f72cacc608847695d",
          "61779d2272cacc6088476961",
          "61779d8972cacc6088476968",
          "61779e2972cacc6088476970",
          "61779ee572cacc608847697a",
          "61779fd172cacc6088476980",
          "6177a0fc72cacc608847698a",
          "6177a15a72cacc6088476991",
          "6177a1f172cacc6088476998",
          "6177a29c72cacc60884769a2",
          "6177a42372cacc60884769ac",
          "624ea76a7458462f852f108f",
        ],
        username: "anand1@appsmith.com",
        name: "anand1@appsmith.com",
        enableTelemetry: false,
        accountNonExpired: true,
        accountNonLocked: true,
        credentialsNonExpired: true,
        emptyInstance: false,
        isAnonymous: false,
        isEnabled: true,
        isSuperUser: false,
        isConfigurable: true,
      },
      URL: {
        fullPath:
          "https://dev.appsmith.com/app/untitled-application-26/page1-6285d928db0f9c6e620d4548/edit",
        host: "dev.appsmith.com",
        hostname: "dev.appsmith.com",
        queryParams: {},
        protocol: "https:",
        pathname:
          "/app/untitled-application-26/page1-6285d928db0f9c6e620d4548/edit",
        port: "",
        hash: "",
      },
      store: {},
      geolocation: {
        canBeRequested: true,
      },
      mode: "EDIT",
      theme: {
        colors: {
          primaryColor: "#16a34a",
          backgroundColor: "#F6F6F6",
        },
        borderRadius: {
          appBorderRadius: "0px",
        },
        boxShadow: {
          appBoxShadow: "none",
        },
        fontFamily: {
          appFont: "System Default",
        },
      },
      ENTITY_TYPE: ENTITY_TYPE.APPSMITH,
    } as unknown) as DataTreeAppsmith,
  },
  apiSuccessUnEvalTree: {
    // has only 3 objects in Api1.data
    Api1: {
      run: {},
      clear: {},
      actionId: "6285d928db0f9c6e620d454a",
      name: "Api1",
      pluginId: "5ca385dc81b37f0004b4db85",
      pluginType: PluginType.API,
      config: {
        timeoutInMillisecond: 10000,
        paginationType: PaginationType.NONE,
        path: "/posts",
        queryParameters: [],
        pluginSpecifiedTemplates: [
          {
            value: true,
          },
        ],
        formData: {
          apiContentType: "none",
        },
      },
      dynamicBindingPathList: [],
      data: [
        {
          userId: 1,
          id: 1,
          title:
            "sunt aut facere repellat provident occaecati excepturi optio reprehenderit",
          body:
            "quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto",
        },
        {
          userId: 1,
          id: 2,
          title: "qui est esse",
          body:
            "est rerum tempore vitae\nsequi sint nihil reprehenderit dolor beatae ea dolores neque\nfugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis\nqui aperiam non debitis possimus qui neque nisi nulla",
        },
        {
          userId: 1,
          id: 3,
          title: "ea molestias quasi exercitationem repellat qui ipsa sit aut",
          body:
            "et iusto sed quo iure\nvoluptatem occaecati omnis eligendi aut ad\nvoluptatem doloribus vel accusantium quis pariatur\nmolestiae porro eius odio et labore et velit aut",
        },
      ],
      responseMeta: {
        statusCode: "200 OK",
        isExecutionSuccess: true,
        headers: {
          Date: ["Fri, 20 May 2022 09:18:48 GMT"],
          "Content-Type": ["application/json; charset=utf-8"],
          "Transfer-Encoding": ["chunked"],
          Connection: ["keep-alive"],
          "X-Powered-By": ["Express"],
          "X-Ratelimit-Limit": ["1000"],
          "X-Ratelimit-Remaining": ["999"],
          "X-Ratelimit-Reset": ["1652916230"],
          Vary: ["Origin, Accept-Encoding"],
          "Access-Control-Allow-Credentials": ["true"],
          "Cache-Control": ["max-age=43200"],
          Pragma: ["no-cache"],
          Expires: ["-1"],
          "X-Content-Type-Options": ["nosniff"],
          Etag: ['W/"6b80-Ybsq/K6GwwqrYkAsFxqDXGC7DoM"'],
          Via: ["1.1 vegur"],
          "CF-Cache-Status": ["HIT"],
          Age: ["6791"],
          "Expect-CT": [
            'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
          ],
          "Report-To": [
            '{"endpoints":[{"url":"https:\\/\\/a.nel.cloudflare.com\\/report\\/v3?s=mL80WXGZevCRJ%2BH3N6Uq0dvpeHk%2BFLrmzIZMCcTnH10LlRna45sxEdLPMELrTur3z3Tr8ucgNQ7X%2FuIhNRTRj00%2FvML3zxIkOIZsrKf3iTIeQDts3oFwUg9b51xg0IDoperi1JchNq5muJETOeT%2B"}],"group":"cf-nel","max_age":604800}',
          ],
          NEL: ['{"success_fraction":0,"report_to":"cf-nel","max_age":604800}'],
          Server: ["cloudflare"],
          "CF-RAY": ["70e3fcb39dde18ce-SIN"],
          "alt-svc": ['h3=":443"; ma=86400, h3-29=":443"; ma=86400'],
          "X-APPSMITH-DATATYPE": ["JSON"],
        },
      },
      ENTITY_TYPE: ENTITY_TYPE.ACTION,
      isLoading: false,
      bindingPaths: {
        "config.path": EvaluationSubstitutionType.TEMPLATE,
        "config.body": EvaluationSubstitutionType.SMART_SUBSTITUTE,
      },
      reactivePaths: {
        data: EvaluationSubstitutionType.TEMPLATE,
        isLoading: EvaluationSubstitutionType.TEMPLATE,
        datasourceUrl: EvaluationSubstitutionType.TEMPLATE,
        "config.path": EvaluationSubstitutionType.TEMPLATE,
        "config.body": EvaluationSubstitutionType.SMART_SUBSTITUTE,
      },
      dependencyMap: {
        "config.body": ["config.pluginSpecifiedTemplates[0].value"],
      },
      logBlackList: {},
      datasourceUrl: "https://jsonplaceholder.typicode.com",
    },
    MainContainer: ({
      widgetName: "MainContainer",
      backgroundColor: "none",
      rightColumn: 4896,
      snapColumns: 64,
      detachFromLayout: true,
      widgetId: "0",
      topRow: 0,
      bottomRow: 1320,
      containerStyle: "none",
      snapRows: 125,
      parentRowSpace: 1,
      type: "CANVAS_WIDGET",
      canExtend: true,
      version: 58,
      minHeight: 1292,
      dynamicTriggerPathList: [],
      parentColumnSpace: 1,
      dynamicBindingPathList: [],
      leftColumn: 0,
      children: ["1p9hcl50i8"],
      defaultProps: {},
      defaultMetaProps: [],
      logBlackList: {},
      propertyOverrideDependency: {},
      overridingPropertyPaths: {},
      bindingPaths: {},
      reactivePaths: {},
      triggerPaths: {},
      validationPaths: {},
      ENTITY_TYPE: ENTITY_TYPE.WIDGET,
      privateWidgets: {},
      meta: {},
    } as unknown) as DataTreeWidget,
    Text1: ({
      widgetName: "Text1",
      displayName: "Text",
      iconSVG: "/static/media/icon.97c59b52.svg",
      topRow: 14,
      bottomRow: 18,
      parentRowSpace: 10,
      type: "TEXT_WIDGET",
      hideCard: false,
      animateLoading: true,
      overflow: "NONE",
      fontFamily: "{{appsmith.theme.fontFamily.appFont}}",
      parentColumnSpace: 11.796875,
      dynamicTriggerPathList: [],
      leftColumn: 21,
      dynamicBindingPathList: [
        {
          key: "fontFamily",
        },
        {
          key: "borderRadius",
        },
        {
          key: "text",
        },
        {
          key: "value",
        },
      ],
      shouldTruncate: false,
      truncateButtonColor: "#FFC13D",
      text: "{{\nApi1.data[2].id\n}}",
      key: "ljtoov0cml",
      rightColumn: 37,
      textAlign: "LEFT",
      widgetId: "1p9hcl50i8",
      isVisible: true,
      fontStyle: "BOLD",
      textColor: "#231F20",
      version: 1,
      parentId: "0",
      renderMode: "CANVAS",
      isLoading: false,
      borderRadius: "{{appsmith.theme.borderRadius.appBorderRadius}}",
      fontSize: "1rem",
      value: "{{ Text1.text }}",
      defaultProps: {},
      defaultMetaProps: [],
      logBlackList: {
        value: true,
      },
      propertyOverrideDependency: {},
      overridingPropertyPaths: {},
      bindingPaths: {
        text: EvaluationSubstitutionType.TEMPLATE,
        isVisible: EvaluationSubstitutionType.TEMPLATE,
        animateLoading: EvaluationSubstitutionType.TEMPLATE,
        disableLink: EvaluationSubstitutionType.TEMPLATE,
        backgroundColor: EvaluationSubstitutionType.TEMPLATE,
        textColor: EvaluationSubstitutionType.TEMPLATE,
        borderColor: EvaluationSubstitutionType.TEMPLATE,
        borderWidth: EvaluationSubstitutionType.TEMPLATE,
        fontSize: EvaluationSubstitutionType.TEMPLATE,
        fontFamily: EvaluationSubstitutionType.TEMPLATE,
        fontStyle: EvaluationSubstitutionType.TEMPLATE,
        textAlign: EvaluationSubstitutionType.TEMPLATE,
      },
      reactivePaths: {
        value: EvaluationSubstitutionType.TEMPLATE,
        fontFamily: EvaluationSubstitutionType.TEMPLATE,
        borderRadius: EvaluationSubstitutionType.TEMPLATE,
        text: EvaluationSubstitutionType.TEMPLATE,
        isVisible: EvaluationSubstitutionType.TEMPLATE,
        animateLoading: EvaluationSubstitutionType.TEMPLATE,
        disableLink: EvaluationSubstitutionType.TEMPLATE,
        backgroundColor: EvaluationSubstitutionType.TEMPLATE,
        textColor: EvaluationSubstitutionType.TEMPLATE,
        borderColor: EvaluationSubstitutionType.TEMPLATE,
        borderWidth: EvaluationSubstitutionType.TEMPLATE,
        fontSize: EvaluationSubstitutionType.TEMPLATE,
        fontStyle: EvaluationSubstitutionType.TEMPLATE,
        textAlign: EvaluationSubstitutionType.TEMPLATE,
      },
      triggerPaths: {},
      validationPaths: {
        text: {
          type: "TEXT",
          params: {
            limitLineBreaks: true,
          },
        },
        isVisible: {
          type: "BOOLEAN",
        },
        animateLoading: {
          type: "BOOLEAN",
        },
        disableLink: {
          type: "BOOLEAN",
        },
        backgroundColor: {
          type: "TEXT",
          params: {
            regex: {},
            expected: {
              type: "string (HTML color name or HEX value)",
              example: "red | #9C0D38",
              autocompleteDataType: "STRING",
            },
          },
        },
        textColor: {
          type: "TEXT",
          params: {
            regex: {},
          },
        },
        borderColor: {
          type: "TEXT",
        },
        borderWidth: {
          type: "NUMBER",
        },
        fontSize: {
          type: "TEXT",
        },
        fontFamily: {
          type: "TEXT",
        },
        fontStyle: {
          type: "TEXT",
        },
        textAlign: {
          type: "TEXT",
        },
      },
      ENTITY_TYPE: ENTITY_TYPE.WIDGET,
      privateWidgets: {},
      meta: {},
    } as unknown) as DataTreeWidget,
    pageList: [
      {
        pageName: "Page1",
        pageId: "6285d928db0f9c6e620d4548",
        isDefault: true,
        isHidden: false,
        slug: "page1",
      },
    ],
    appsmith: ({
      user: {
        email: "anand1@appsmith.com",
        organizationIds: [
          "617150deb7de236aa183edab",
          "6171510ab7de236aa183edb0",
          "61715151b7de236aa183edb7",
          "61715172b7de236aa183edbb",
          "6171518fb7de236aa183edbf",
          "615d6680d513605e3f67af87",
          "61763f53ba7e887d03bc3575",
          "61763f74ba7e887d03bc3579",
          "6176489fba7e887d03bc359e",
          "617648bfba7e887d03bc35a2",
          "617648deba7e887d03bc35a6",
          "61764b81ba7e887d03bc35af",
          "61764bc2ba7e887d03bc35b7",
          "61764ebbba7e887d03bc35c4",
          "61764edcba7e887d03bc35c8",
          "61764efbba7e887d03bc35cc",
          "61779c0f72cacc608847695d",
          "61779d2272cacc6088476961",
          "61779d8972cacc6088476968",
          "61779e2972cacc6088476970",
          "61779ee572cacc608847697a",
          "61779fd172cacc6088476980",
          "6177a0fc72cacc608847698a",
          "6177a15a72cacc6088476991",
          "6177a1f172cacc6088476998",
          "6177a29c72cacc60884769a2",
          "6177a42372cacc60884769ac",
          "624ea76a7458462f852f108f",
        ],
        username: "anand1@appsmith.com",
        name: "anand1@appsmith.com",
        enableTelemetry: false,
        accountNonExpired: true,
        accountNonLocked: true,
        credentialsNonExpired: true,
        emptyInstance: false,
        isAnonymous: false,
        isEnabled: true,
        isSuperUser: false,
        isConfigurable: true,
      },
      URL: {
        fullPath:
          "https://dev.appsmith.com/app/untitled-application-26/page1-6285d928db0f9c6e620d4548/edit",
        host: "dev.appsmith.com",
        hostname: "dev.appsmith.com",
        queryParams: {},
        protocol: "https:",
        pathname:
          "/app/untitled-application-26/page1-6285d928db0f9c6e620d4548/edit",
        port: "",
        hash: "",
      },
      store: {},
      geolocation: {
        canBeRequested: true,
      },
      mode: "EDIT",
      theme: {
        colors: {
          primaryColor: "#16a34a",
          backgroundColor: "#F6F6F6",
        },
        borderRadius: {
          appBorderRadius: "0px",
        },
        boxShadow: {
          appBoxShadow: "none",
        },
        fontFamily: {
          appFont: "System Default",
        },
      },
      ENTITY_TYPE: ENTITY_TYPE.APPSMITH,
    } as unknown) as DataTreeAppsmith,
  },
  apiFailureUnEvalTree: {
    Api1: {
      run: {},
      clear: {},
      actionId: "6285d928db0f9c6e620d454a",
      name: "Api1",
      pluginId: "5ca385dc81b37f0004b4db85",
      pluginType: PluginType.API,
      config: {
        timeoutInMillisecond: 10000,
        paginationType: PaginationType.NONE,
        path: "/pos",
        queryParameters: [],
        pluginSpecifiedTemplates: [
          {
            value: true,
          },
        ],
        formData: {
          apiContentType: "none",
        },
      },
      dynamicBindingPathList: [],
      data: {},
      responseMeta: {
        statusCode: "404 NOT_FOUND",
        isExecutionSuccess: false,
        headers: {
          Date: ["Fri, 20 May 2022 09:20:01 GMT"],
          "Content-Type": ["application/json; charset=utf-8"],
          Connection: ["keep-alive"],
          "X-Powered-By": ["Express"],
          "X-Ratelimit-Limit": ["1000"],
          "X-Ratelimit-Remaining": ["999"],
          "X-Ratelimit-Reset": ["1653038437"],
          Vary: ["Origin, Accept-Encoding"],
          "Access-Control-Allow-Credentials": ["true"],
          "Cache-Control": ["max-age=43200"],
          Pragma: ["no-cache"],
          Expires: ["-1"],
          "X-Content-Type-Options": ["nosniff"],
          Etag: ['W/"2-vyGp6PvFo4RvsFtPoIWeCReyIC8"'],
          Via: ["1.1 vegur"],
          "CF-Cache-Status": ["EXPIRED"],
          "Expect-CT": [
            'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
          ],
          "Report-To": [
            '{"endpoints":[{"url":"https:\\/\\/a.nel.cloudflare.com\\/report\\/v3?s=UkqmMMihJpG%2BIoEcVub10200FpqRPQDDipw0gOy%2B5nYRyuF6NZ4X1CoNEXk2YLHb%2FLkt%2F1rXFAJJq5xwJtRgb6%2BsXwWEAqWi5vSP5D6DMhVyP%2Fyr5Q5FQc3dfILZfmeEoCWKxlEq0AfhOOKThz%2BK"}],"group":"cf-nel","max_age":604800}',
          ],
          NEL: ['{"success_fraction":0,"report_to":"cf-nel","max_age":604800}'],
          Server: ["cloudflare"],
          "CF-RAY": ["70e3fe76b80d9f86-SIN"],
          "alt-svc": ['h3=":443"; ma=86400, h3-29=":443"; ma=86400'],
          "content-length": ["2"],
          "X-APPSMITH-DATATYPE": ["JSON"],
        },
      },
      ENTITY_TYPE: ENTITY_TYPE.ACTION,
      isLoading: false,
      bindingPaths: {
        "config.path": EvaluationSubstitutionType.TEMPLATE,
        "config.body": EvaluationSubstitutionType.SMART_SUBSTITUTE,
      },
      reactivePaths: {
        data: EvaluationSubstitutionType.TEMPLATE,
        isLoading: EvaluationSubstitutionType.TEMPLATE,
        datasourceUrl: EvaluationSubstitutionType.TEMPLATE,
        "config.path": EvaluationSubstitutionType.TEMPLATE,
        "config.body": EvaluationSubstitutionType.SMART_SUBSTITUTE,
      },
      dependencyMap: {
        "config.body": ["config.pluginSpecifiedTemplates[0].value"],
      },
      logBlackList: {},
      datasourceUrl: "https://jsonplaceholder.typicode.com",
    },
    MainContainer: ({
      widgetName: "MainContainer",
      backgroundColor: "none",
      rightColumn: 4896,
      snapColumns: 64,
      detachFromLayout: true,
      widgetId: "0",
      topRow: 0,
      bottomRow: 1320,
      containerStyle: "none",
      snapRows: 125,
      parentRowSpace: 1,
      type: "CANVAS_WIDGET",
      canExtend: true,
      version: 58,
      minHeight: 1292,
      dynamicTriggerPathList: [],
      parentColumnSpace: 1,
      dynamicBindingPathList: [],
      leftColumn: 0,
      children: ["1p9hcl50i8"],
      defaultProps: {},
      defaultMetaProps: [],
      logBlackList: {},
      propertyOverrideDependency: {},
      overridingPropertyPaths: {},
      bindingPaths: {},
      reactivePaths: {},
      triggerPaths: {},
      validationPaths: {},
      ENTITY_TYPE: ENTITY_TYPE.WIDGET,
      privateWidgets: {},
      meta: {},
    } as unknown) as DataTreeWidget,
    Text1: ({
      widgetName: "Text1",
      displayName: "Text",
      iconSVG: "/static/media/icon.97c59b52.svg",
      topRow: 14,
      bottomRow: 18,
      parentRowSpace: 10,
      type: "TEXT_WIDGET",
      hideCard: false,
      animateLoading: true,
      overflow: "NONE",
      fontFamily: "{{appsmith.theme.fontFamily.appFont}}",
      parentColumnSpace: 11.796875,
      dynamicTriggerPathList: [],
      leftColumn: 21,
      dynamicBindingPathList: [
        {
          key: "fontFamily",
        },
        {
          key: "borderRadius",
        },
        {
          key: "text",
        },
        {
          key: "value",
        },
      ],
      shouldTruncate: false,
      truncateButtonColor: "#FFC13D",
      text: "{{\nApi1.data[2].id\n}}",
      key: "ljtoov0cml",
      rightColumn: 37,
      textAlign: "LEFT",
      widgetId: "1p9hcl50i8",
      isVisible: true,
      fontStyle: "BOLD",
      textColor: "#231F20",
      version: 1,
      parentId: "0",
      renderMode: "CANVAS",
      isLoading: false,
      borderRadius: "{{appsmith.theme.borderRadius.appBorderRadius}}",
      fontSize: "1rem",
      value: "{{ Text1.text }}",
      defaultProps: {},
      defaultMetaProps: [],
      logBlackList: {
        value: true,
      },
      propertyOverrideDependency: {},
      overridingPropertyPaths: {},
      bindingPaths: {
        text: EvaluationSubstitutionType.TEMPLATE,
        isVisible: EvaluationSubstitutionType.TEMPLATE,
        animateLoading: EvaluationSubstitutionType.TEMPLATE,
        disableLink: EvaluationSubstitutionType.TEMPLATE,
        backgroundColor: EvaluationSubstitutionType.TEMPLATE,
        textColor: EvaluationSubstitutionType.TEMPLATE,
        borderColor: EvaluationSubstitutionType.TEMPLATE,
        borderWidth: EvaluationSubstitutionType.TEMPLATE,
        fontSize: EvaluationSubstitutionType.TEMPLATE,
        fontFamily: EvaluationSubstitutionType.TEMPLATE,
        fontStyle: EvaluationSubstitutionType.TEMPLATE,
        textAlign: EvaluationSubstitutionType.TEMPLATE,
      },
      reactivePaths: {
        value: EvaluationSubstitutionType.TEMPLATE,
        fontFamily: EvaluationSubstitutionType.TEMPLATE,
        borderRadius: EvaluationSubstitutionType.TEMPLATE,
        text: EvaluationSubstitutionType.TEMPLATE,
        isVisible: EvaluationSubstitutionType.TEMPLATE,
        animateLoading: EvaluationSubstitutionType.TEMPLATE,
        disableLink: EvaluationSubstitutionType.TEMPLATE,
        backgroundColor: EvaluationSubstitutionType.TEMPLATE,
        textColor: EvaluationSubstitutionType.TEMPLATE,
        borderColor: EvaluationSubstitutionType.TEMPLATE,
        borderWidth: EvaluationSubstitutionType.TEMPLATE,
        fontSize: EvaluationSubstitutionType.TEMPLATE,
        fontStyle: EvaluationSubstitutionType.TEMPLATE,
        textAlign: EvaluationSubstitutionType.TEMPLATE,
      },
      triggerPaths: {},
      validationPaths: {
        text: {
          type: "TEXT",
          params: {
            limitLineBreaks: true,
          },
        },
        isVisible: {
          type: "BOOLEAN",
        },
        animateLoading: {
          type: "BOOLEAN",
        },
        disableLink: {
          type: "BOOLEAN",
        },
        backgroundColor: {
          type: "TEXT",
          params: {
            regex: {},
            expected: {
              type: "string (HTML color name or HEX value)",
              example: "red | #9C0D38",
              autocompleteDataType: "STRING",
            },
          },
        },
        textColor: {
          type: "TEXT",
          params: {
            regex: {},
          },
        },
        borderColor: {
          type: "TEXT",
        },
        borderWidth: {
          type: "NUMBER",
        },
        fontSize: {
          type: "TEXT",
        },
        fontFamily: {
          type: "TEXT",
        },
        fontStyle: {
          type: "TEXT",
        },
        textAlign: {
          type: "TEXT",
        },
      },
      ENTITY_TYPE: ENTITY_TYPE.WIDGET,
      privateWidgets: {},
      meta: {},
    } as unknown) as DataTreeWidget,
    pageList: [
      {
        pageName: "Page1",
        pageId: "6285d928db0f9c6e620d4548",
        isDefault: true,
        isHidden: false,
        slug: "page1",
      },
    ],
    appsmith: ({
      user: {
        email: "anand1@appsmith.com",
        organizationIds: [
          "617150deb7de236aa183edab",
          "6171510ab7de236aa183edb0",
          "61715151b7de236aa183edb7",
          "61715172b7de236aa183edbb",
          "6171518fb7de236aa183edbf",
          "615d6680d513605e3f67af87",
          "61763f53ba7e887d03bc3575",
          "61763f74ba7e887d03bc3579",
          "6176489fba7e887d03bc359e",
          "617648bfba7e887d03bc35a2",
          "617648deba7e887d03bc35a6",
          "61764b81ba7e887d03bc35af",
          "61764bc2ba7e887d03bc35b7",
          "61764ebbba7e887d03bc35c4",
          "61764edcba7e887d03bc35c8",
          "61764efbba7e887d03bc35cc",
          "61779c0f72cacc608847695d",
          "61779d2272cacc6088476961",
          "61779d8972cacc6088476968",
          "61779e2972cacc6088476970",
          "61779ee572cacc608847697a",
          "61779fd172cacc6088476980",
          "6177a0fc72cacc608847698a",
          "6177a15a72cacc6088476991",
          "6177a1f172cacc6088476998",
          "6177a29c72cacc60884769a2",
          "6177a42372cacc60884769ac",
          "624ea76a7458462f852f108f",
        ],
        username: "anand1@appsmith.com",
        name: "anand1@appsmith.com",
        enableTelemetry: false,
        accountNonExpired: true,
        accountNonLocked: true,
        credentialsNonExpired: true,
        emptyInstance: false,
        isAnonymous: false,
        isEnabled: true,
        isSuperUser: false,
        isConfigurable: true,
      },
      URL: {
        fullPath:
          "https://dev.appsmith.com/app/untitled-application-26/page1-6285d928db0f9c6e620d4548/edit",
        host: "dev.appsmith.com",
        hostname: "dev.appsmith.com",
        queryParams: {},
        protocol: "https:",
        pathname:
          "/app/untitled-application-26/page1-6285d928db0f9c6e620d4548/edit",
        port: "",
        hash: "",
      },
      store: {},
      geolocation: {
        canBeRequested: true,
      },
      mode: "EDIT",
      theme: {
        colors: {
          primaryColor: "#16a34a",
          backgroundColor: "#F6F6F6",
        },
        borderRadius: {
          appBorderRadius: "0px",
        },
        boxShadow: {
          appBoxShadow: "none",
        },
        fontFamily: {
          appFont: "System Default",
        },
      },
      ENTITY_TYPE: ENTITY_TYPE.APPSMITH,
    } as unknown) as DataTreeAppsmith,
  },
  apiSuccessUnEvalTree2: {
    // has only 1 object in Api1.data
    Api1: {
      run: {},
      clear: {},
      actionId: "6285d928db0f9c6e620d454a",
      name: "Api1",
      pluginId: "5ca385dc81b37f0004b4db85",
      pluginType: PluginType.API,
      config: {
        timeoutInMillisecond: 10000,
        paginationType: PaginationType.NONE,
        path: "/posts",
        queryParameters: [],
        pluginSpecifiedTemplates: [
          {
            value: true,
          },
        ],
        formData: {
          apiContentType: "none",
        },
      },
      dynamicBindingPathList: [],
      data: [
        {
          userId: 1,
          id: 1,
          title:
            "sunt aut facere repellat provident occaecati excepturi optio reprehenderit",
          body:
            "quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto",
        },
      ],
      responseMeta: {
        statusCode: "200 OK",
        isExecutionSuccess: true,
        headers: {
          Date: ["Fri, 20 May 2022 09:18:48 GMT"],
          "Content-Type": ["application/json; charset=utf-8"],
          "Transfer-Encoding": ["chunked"],
          Connection: ["keep-alive"],
          "X-Powered-By": ["Express"],
          "X-Ratelimit-Limit": ["1000"],
          "X-Ratelimit-Remaining": ["999"],
          "X-Ratelimit-Reset": ["1652916230"],
          Vary: ["Origin, Accept-Encoding"],
          "Access-Control-Allow-Credentials": ["true"],
          "Cache-Control": ["max-age=43200"],
          Pragma: ["no-cache"],
          Expires: ["-1"],
          "X-Content-Type-Options": ["nosniff"],
          Etag: ['W/"6b80-Ybsq/K6GwwqrYkAsFxqDXGC7DoM"'],
          Via: ["1.1 vegur"],
          "CF-Cache-Status": ["HIT"],
          Age: ["6791"],
          "Expect-CT": [
            'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
          ],
          "Report-To": [
            '{"endpoints":[{"url":"https:\\/\\/a.nel.cloudflare.com\\/report\\/v3?s=mL80WXGZevCRJ%2BH3N6Uq0dvpeHk%2BFLrmzIZMCcTnH10LlRna45sxEdLPMELrTur3z3Tr8ucgNQ7X%2FuIhNRTRj00%2FvML3zxIkOIZsrKf3iTIeQDts3oFwUg9b51xg0IDoperi1JchNq5muJETOeT%2B"}],"group":"cf-nel","max_age":604800}',
          ],
          NEL: ['{"success_fraction":0,"report_to":"cf-nel","max_age":604800}'],
          Server: ["cloudflare"],
          "CF-RAY": ["70e3fcb39dde18ce-SIN"],
          "alt-svc": ['h3=":443"; ma=86400, h3-29=":443"; ma=86400'],
          "X-APPSMITH-DATATYPE": ["JSON"],
        },
      },
      ENTITY_TYPE: ENTITY_TYPE.ACTION,
      isLoading: false,
      bindingPaths: {
        "config.path": EvaluationSubstitutionType.TEMPLATE,
        "config.body": EvaluationSubstitutionType.SMART_SUBSTITUTE,
      },
      reactivePaths: {
        data: EvaluationSubstitutionType.TEMPLATE,
        isLoading: EvaluationSubstitutionType.TEMPLATE,
        datasourceUrl: EvaluationSubstitutionType.TEMPLATE,
        "config.path": EvaluationSubstitutionType.TEMPLATE,
        "config.body": EvaluationSubstitutionType.SMART_SUBSTITUTE,
      },
      dependencyMap: {
        "config.body": ["config.pluginSpecifiedTemplates[0].value"],
      },
      logBlackList: {},
      datasourceUrl: "https://jsonplaceholder.typicode.com",
    },
    MainContainer: ({
      widgetName: "MainContainer",
      backgroundColor: "none",
      rightColumn: 4896,
      snapColumns: 64,
      detachFromLayout: true,
      widgetId: "0",
      topRow: 0,
      bottomRow: 1320,
      containerStyle: "none",
      snapRows: 125,
      parentRowSpace: 1,
      type: "CANVAS_WIDGET",
      canExtend: true,
      version: 58,
      minHeight: 1292,
      dynamicTriggerPathList: [],
      parentColumnSpace: 1,
      dynamicBindingPathList: [],
      leftColumn: 0,
      children: ["1p9hcl50i8"],
      defaultProps: {},
      defaultMetaProps: [],
      logBlackList: {},
      propertyOverrideDependency: {},
      overridingPropertyPaths: {},
      bindingPaths: {},
      reactivePaths: {},
      triggerPaths: {},
      validationPaths: {},
      ENTITY_TYPE: ENTITY_TYPE.WIDGET,
      privateWidgets: {},
      meta: {},
    } as unknown) as DataTreeWidget,
    Text1: ({
      widgetName: "Text1",
      displayName: "Text",
      iconSVG: "/static/media/icon.97c59b52.svg",
      topRow: 14,
      bottomRow: 18,
      parentRowSpace: 10,
      type: "TEXT_WIDGET",
      hideCard: false,
      animateLoading: true,
      overflow: "NONE",
      fontFamily: "{{appsmith.theme.fontFamily.appFont}}",
      parentColumnSpace: 11.796875,
      dynamicTriggerPathList: [],
      leftColumn: 21,
      dynamicBindingPathList: [
        {
          key: "fontFamily",
        },
        {
          key: "borderRadius",
        },
        {
          key: "text",
        },
        {
          key: "value",
        },
      ],
      shouldTruncate: false,
      truncateButtonColor: "#FFC13D",
      text: "{{\nApi1.data[2].id\n}}",
      key: "ljtoov0cml",
      rightColumn: 37,
      textAlign: "LEFT",
      widgetId: "1p9hcl50i8",
      isVisible: true,
      fontStyle: "BOLD",
      textColor: "#231F20",
      version: 1,
      parentId: "0",
      renderMode: "CANVAS",
      isLoading: false,
      borderRadius: "{{appsmith.theme.borderRadius.appBorderRadius}}",
      fontSize: "1rem",
      value: "{{ Text1.text }}",
      defaultProps: {},
      defaultMetaProps: [],
      logBlackList: {
        value: true,
      },
      propertyOverrideDependency: {},
      overridingPropertyPaths: {},
      bindingPaths: {
        text: EvaluationSubstitutionType.TEMPLATE,
        isVisible: EvaluationSubstitutionType.TEMPLATE,
        animateLoading: EvaluationSubstitutionType.TEMPLATE,
        disableLink: EvaluationSubstitutionType.TEMPLATE,
        backgroundColor: EvaluationSubstitutionType.TEMPLATE,
        textColor: EvaluationSubstitutionType.TEMPLATE,
        borderColor: EvaluationSubstitutionType.TEMPLATE,
        borderWidth: EvaluationSubstitutionType.TEMPLATE,
        fontSize: EvaluationSubstitutionType.TEMPLATE,
        fontFamily: EvaluationSubstitutionType.TEMPLATE,
        fontStyle: EvaluationSubstitutionType.TEMPLATE,
        textAlign: EvaluationSubstitutionType.TEMPLATE,
      },
      reactivePaths: {
        value: EvaluationSubstitutionType.TEMPLATE,
        fontFamily: EvaluationSubstitutionType.TEMPLATE,
        borderRadius: EvaluationSubstitutionType.TEMPLATE,
        text: EvaluationSubstitutionType.TEMPLATE,
        isVisible: EvaluationSubstitutionType.TEMPLATE,
        animateLoading: EvaluationSubstitutionType.TEMPLATE,
        disableLink: EvaluationSubstitutionType.TEMPLATE,
        backgroundColor: EvaluationSubstitutionType.TEMPLATE,
        textColor: EvaluationSubstitutionType.TEMPLATE,
        borderColor: EvaluationSubstitutionType.TEMPLATE,
        borderWidth: EvaluationSubstitutionType.TEMPLATE,
        fontSize: EvaluationSubstitutionType.TEMPLATE,
        fontStyle: EvaluationSubstitutionType.TEMPLATE,
        textAlign: EvaluationSubstitutionType.TEMPLATE,
      },
      triggerPaths: {},
      validationPaths: {
        text: {
          type: "TEXT",
          params: {
            limitLineBreaks: true,
          },
        },
        isVisible: {
          type: "BOOLEAN",
        },
        animateLoading: {
          type: "BOOLEAN",
        },
        disableLink: {
          type: "BOOLEAN",
        },
        backgroundColor: {
          type: "TEXT",
          params: {
            regex: {},
            expected: {
              type: "string (HTML color name or HEX value)",
              example: "red | #9C0D38",
              autocompleteDataType: "STRING",
            },
          },
        },
        textColor: {
          type: "TEXT",
          params: {
            regex: {},
          },
        },
        borderColor: {
          type: "TEXT",
        },
        borderWidth: {
          type: "NUMBER",
        },
        fontSize: {
          type: "TEXT",
        },
        fontFamily: {
          type: "TEXT",
        },
        fontStyle: {
          type: "TEXT",
        },
        textAlign: {
          type: "TEXT",
        },
      },
      ENTITY_TYPE: ENTITY_TYPE.WIDGET,
      privateWidgets: {},
      meta: {},
    } as unknown) as DataTreeWidget,
    pageList: [
      {
        pageName: "Page1",
        pageId: "6285d928db0f9c6e620d4548",
        isDefault: true,
        isHidden: false,
        slug: "page1",
      },
    ],
    appsmith: ({
      user: {
        email: "anand1@appsmith.com",
        organizationIds: [
          "617150deb7de236aa183edab",
          "6171510ab7de236aa183edb0",
          "61715151b7de236aa183edb7",
          "61715172b7de236aa183edbb",
          "6171518fb7de236aa183edbf",
          "615d6680d513605e3f67af87",
          "61763f53ba7e887d03bc3575",
          "61763f74ba7e887d03bc3579",
          "6176489fba7e887d03bc359e",
          "617648bfba7e887d03bc35a2",
          "617648deba7e887d03bc35a6",
          "61764b81ba7e887d03bc35af",
          "61764bc2ba7e887d03bc35b7",
          "61764ebbba7e887d03bc35c4",
          "61764edcba7e887d03bc35c8",
          "61764efbba7e887d03bc35cc",
          "61779c0f72cacc608847695d",
          "61779d2272cacc6088476961",
          "61779d8972cacc6088476968",
          "61779e2972cacc6088476970",
          "61779ee572cacc608847697a",
          "61779fd172cacc6088476980",
          "6177a0fc72cacc608847698a",
          "6177a15a72cacc6088476991",
          "6177a1f172cacc6088476998",
          "6177a29c72cacc60884769a2",
          "6177a42372cacc60884769ac",
          "624ea76a7458462f852f108f",
        ],
        username: "anand1@appsmith.com",
        name: "anand1@appsmith.com",
        enableTelemetry: false,
        accountNonExpired: true,
        accountNonLocked: true,
        credentialsNonExpired: true,
        emptyInstance: false,
        isAnonymous: false,
        isEnabled: true,
        isSuperUser: false,
        isConfigurable: true,
      },
      URL: {
        fullPath:
          "https://dev.appsmith.com/app/untitled-application-26/page1-6285d928db0f9c6e620d4548/edit",
        host: "dev.appsmith.com",
        hostname: "dev.appsmith.com",
        queryParams: {},
        protocol: "https:",
        pathname:
          "/app/untitled-application-26/page1-6285d928db0f9c6e620d4548/edit",
        port: "",
        hash: "",
      },
      store: {},
      geolocation: {
        canBeRequested: true,
      },
      mode: "EDIT",
      theme: {
        colors: {
          primaryColor: "#16a34a",
          backgroundColor: "#F6F6F6",
        },
        borderRadius: {
          appBorderRadius: "0px",
        },
        boxShadow: {
          appBoxShadow: "none",
        },
        fontFamily: {
          appFont: "System Default",
        },
      },
      ENTITY_TYPE: ENTITY_TYPE.APPSMITH,
    } as unknown) as DataTreeAppsmith,
  },
};
