package com.appsmith.server.authentication.oauth2clientrepositories;

import com.appsmith.server.authentication.oauth2clientrepositories.ce.BaseClientRegistrationRepositoryCE;

public interface BaseClientRegistrationRepository extends BaseClientRegistrationRepositoryCE {}
