package com.appsmith.server.authentication.oauth2clientrepositories;

import com.appsmith.server.authentication.oauth2clientrepositories.ce.CustomOauth2ClientRepositoryManagerCE;

public interface CustomOauth2ClientRepositoryManager extends CustomOauth2ClientRepositoryManagerCE {}
