// Generated by CodiumAI

import { APP_MODE } from "entities/App";
import { URLBuilder } from "./URLAssembly";

describe("URLBuilder", () => {
  // correctly sets and uses currentPageId in build function
  it("should correctly set and use currentPageId in build function", () => {
    const urlBuilder = URLBuilder.getInstance();
    const testPageId = "testPageId";
    const testMode = APP_MODE.EDIT;

    urlBuilder.setCurrentPageId(testPageId);

    const builderParams = {
      suffix: "testSuffix",
      branch: "testBranch",
      hash: "testHash",
      params: { param1: "value1", param2: "value2" },
      persistExistingParams: true,
    };

    URLBuilder.prototype.generateBasePath = jest.fn((pageId, mode) => {
      expect(pageId).toBe(testPageId);
      expect(mode).toBe(testMode);
      return `mockedBasePath/${pageId}/${mode}`;
    });

    const result = urlBuilder.build(builderParams, testMode);

    expect(URLBuilder.prototype.generateBasePath).toHaveBeenCalledWith(
      testPageId,
      testMode,
    );

    expect(result).toEqual(
      "mockedBasePath/testPageId/EDIT/testSuffix?param1=value1&param2=value2&branch=testBranch#testHash",
    );
  });

  // throws an error when pageId is missing in build function
  it("should throw an error when pageId is missing in build function", () => {
    const urlBuilder = URLBuilder.getInstance();
    urlBuilder.setCurrentPageId(null);

    expect(() => {
      urlBuilder.build({}, APP_MODE.EDIT);
    }).toThrow(URIError);
  });
});
