package com.appsmith.server.services.ce;

import com.appsmith.external.models.ActionConfiguration;
import com.appsmith.external.models.ActionDTO;
import com.appsmith.external.models.Datasource;
import com.appsmith.external.models.PluginType;
import com.appsmith.external.models.Policy;
import com.appsmith.server.acl.AclPermission;
import com.appsmith.server.acl.PolicyGenerator;
import com.appsmith.server.applications.base.ApplicationService;
import com.appsmith.server.datasources.base.DatasourceService;
import com.appsmith.server.domains.NewAction;
import com.appsmith.server.domains.PermissionGroup;
import com.appsmith.server.domains.Plugin;
import com.appsmith.server.exceptions.AppsmithError;
import com.appsmith.server.exceptions.AppsmithException;
import com.appsmith.server.newactions.base.NewActionService;
import com.appsmith.server.plugins.base.PluginService;
import com.appsmith.server.repositories.NewActionRepository;
import com.appsmith.server.repositories.PermissionGroupRepository;
import com.appsmith.server.services.PermissionGroupService;
import com.appsmith.server.solutions.ActionPermission;
import com.appsmith.server.solutions.DatasourcePermission;
import com.appsmith.server.solutions.PolicySolution;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.security.test.context.support.WithUserDetails;
import org.springframework.test.context.bean.override.mockito.MockitoSpyBean;
import reactor.core.publisher.Mono;
import reactor.test.StepVerifier;

import java.util.Set;
import java.util.UUID;
import java.util.stream.Collectors;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.times;

@SpringBootTest
public class NewActionServiceSecurityTest {

    @Autowired
    NewActionService newActionService;

    @Autowired
    PolicyGenerator policyGenerator;

    @Autowired
    PermissionGroupRepository permissionGroupRepository;

    @Autowired
    NewActionRepository newActionRepository;

    @Autowired
    ActionPermission actionPermission;

    @Autowired
    DatasourcePermission datasourcePermission;

    @MockitoSpyBean
    PluginService pluginService;

    @MockitoSpyBean
    DatasourceService datasourceService;

    @MockitoSpyBean
    PermissionGroupService permissionGroupService;

    @MockitoSpyBean
    ApplicationService applicationService;

    @MockitoSpyBean
    PolicySolution policySolution;

    @BeforeEach
    public void setup() {
        Mockito.reset(pluginService, datasourceService, permissionGroupService, applicationService, policySolution);
    }

    private NewAction createActionObject(String actionName, String applicationId, AclPermission permission) {
        Set<String> permissionGroupIds = permissionGroupRepository.findAll().collectList().block().stream()
                .map(PermissionGroup::getId)
                .collect(Collectors.toSet());

        Policy testPolicy = Policy.builder()
                .permissionGroups(permissionGroupIds)
                .permission(permission.getValue())
                .build();

        NewAction newAction = new NewAction();
        newAction.setPolicies(Set.of(testPolicy));
        newAction.setApplicationId(applicationId);

        ActionDTO actionDTO = new ActionDTO();
        actionDTO.setName(actionName);
        actionDTO.setPageId(UUID.randomUUID().toString());

        newAction.setUnpublishedAction(actionDTO);
        newAction.setPublishedAction(new ActionDTO());
        return newAction;
    }

    private Datasource createDatasource(String datasourceId, String pluginId, String workspaceId) {
        Datasource datasource = new Datasource();
        datasource.setId(datasourceId);
        datasource.setName("Datasource " + datasourceId);
        datasource.setPluginId(pluginId);
        datasource.setWorkspaceId(workspaceId);
        datasource.setPolicies(Set.of());
        datasource.setIsAutoGenerated(false);
        return datasource;
    }

    private Plugin createPlugin(String pluginId) {
        Plugin plugin = new Plugin();
        plugin.setId(pluginId);
        plugin.setName("Test Plugin");
        plugin.setType(PluginType.DB);
        return plugin;
    }

    private PermissionGroup createPermissionGroup(String id) {
        PermissionGroup permissionGroup = new PermissionGroup();
        permissionGroup.setId(id);
        return permissionGroup;
    }

    private Policy createPolicy(AclPermission permission, String permissionGroupId) {
        return Policy.builder()
                .permission(permission.getValue())
                .permissionGroups(Set.of(permissionGroupId))
                .build();
    }

    /**
     * Verifies that validateAction fetches the datasource with ACL permission check,
     * not the unprotected 1-arg findById. This prevents cross-tenant datasource
     * reference injection via client-controlled datasource.id in the action DTO.
     *
     * GHSA-rqp9-r5fr-4cc8
     */
    @Test
    @WithUserDetails("api_user")
    public void validateAction_shouldFetchDatasourceWithPermissionCheck_GHSA_rqp9() {
        String pluginId = "plugin-" + UUID.randomUUID();
        String datasourceId = "ds-" + UUID.randomUUID();
        String workspaceId = "ws-" + UUID.randomUUID();
        String applicationId = "app-" + UUID.randomUUID();

        Datasource datasource = createDatasource(datasourceId, pluginId, workspaceId);
        Plugin plugin = createPlugin(pluginId);

        Mockito.doReturn(Mono.just(datasource))
                .when(datasourceService)
                .findById(eq(datasourceId), any(AclPermission.class));
        Mockito.doReturn(Mono.just(datasource)).when(datasourceService).findById(datasourceId);
        Mockito.doReturn(Mono.just(plugin)).when(pluginService).findById(pluginId);
        Mockito.doReturn(Mono.just(Set.of())).when(datasourceService).extractKeysFromDatasource(any(Datasource.class));
        Mockito.doReturn(true).when(permissionGroupService).isEntityAccessible(any(), any(), any());

        NewAction newAction = new NewAction();
        newAction.setApplicationId(applicationId);
        newAction.setWorkspaceId(workspaceId);

        ActionDTO actionDTO = new ActionDTO();
        actionDTO.setName("TestAction");
        actionDTO.setPageId(UUID.randomUUID().toString());
        actionDTO.setPluginType(PluginType.DB);
        actionDTO.setDatasource(datasource);
        actionDTO.setActionConfiguration(new ActionConfiguration());

        newAction.setUnpublishedAction(actionDTO);
        newAction.setPublishedAction(new ActionDTO());
        newAction.setPolicies(Set.of());

        StepVerifier.create(newActionService.validateAction(newAction))
                .assertNext(validatedAction -> {
                    assertThat(validatedAction).isNotNull();
                })
                .verifyComplete();

        Mockito.verify(datasourceService, times(1))
                .findById(eq(datasourceId), eq(datasourcePermission.getExecutePermission()));
        Mockito.verify(datasourceService, never()).findById(datasourceId);
    }

    /**
     * Verifies that validateAction rejects cross-workspace datasource references
     * with UNAUTHORIZED_ACCESS. An action in workspace A referencing a datasource
     * in workspace B must fail, preventing cross-tenant datasource takeover.
     *
     * GHSA-rqp9-r5fr-4cc8
     */
    @Test
    @WithUserDetails("api_user")
    public void validateAction_shouldRejectCrossWorkspaceDatasourcePolicyGrant_GHSA_rqp9() {
        String pluginId = "plugin-" + UUID.randomUUID();
        String victimDatasourceId = "ds-victim-" + UUID.randomUUID();
        String attackerWorkspaceId = "ws-attacker-" + UUID.randomUUID();
        String victimWorkspaceId = "ws-victim-" + UUID.randomUUID();
        String applicationId = "app-" + UUID.randomUUID();

        Datasource victimDatasource = createDatasource(victimDatasourceId, pluginId, victimWorkspaceId);
        Plugin plugin = createPlugin(pluginId);

        Mockito.doReturn(Mono.just(victimDatasource))
                .when(datasourceService)
                .findById(eq(victimDatasourceId), any(AclPermission.class));
        Mockito.doReturn(Mono.just(plugin)).when(pluginService).findById(pluginId);
        Mockito.doReturn(Mono.just(Set.of())).when(datasourceService).extractKeysFromDatasource(any(Datasource.class));

        NewAction action = new NewAction();
        action.setApplicationId(applicationId);
        action.setWorkspaceId(attackerWorkspaceId);
        action.setPolicies(Set.of());
        action.setPluginType(PluginType.DB);

        ActionDTO actionDTO = new ActionDTO();
        actionDTO.setName("AttackerAction");
        actionDTO.setPageId(UUID.randomUUID().toString());
        actionDTO.setPluginType(PluginType.DB);
        actionDTO.setDatasource(victimDatasource);
        actionDTO.setActionConfiguration(new ActionConfiguration());

        action.setUnpublishedAction(actionDTO);
        action.setPublishedAction(new ActionDTO());

        StepVerifier.create(newActionService.validateAction(action))
                .expectErrorMatches(throwable -> throwable instanceof AppsmithException
                        && ((AppsmithException) throwable).getError().equals(AppsmithError.UNAUTHORIZED_ACCESS))
                .verify();

        Mockito.verify(datasourceService, never()).save(any(Datasource.class), eq(false));
    }
}
