import { migrateJsonFormWidgetLabelPositonAndAlignment } from "../migrations/090-migrate-jsonformwidget-labelposition-and-alignment";
import type { DSLWidget } from "../types";

const inputDsl: DSLWidget = {
  widgetName: "MainContainer",
  backgroundColor: "none",
  rightColumn: 1118,
  snapColumns: 16,
  detachFromLayout: true,
  widgetId: "0",
  topRow: 0,
  bottomRow: 1280,
  containerStyle: "none",
  snapRows: 33,
  parentRowSpace: 1,
  type: "CANVAS_WIDGET",
  canExtend: true,
  version: 15,
  minHeight: 1292,
  parentColumnSpace: 1,
  dynamicTriggerPathList: [],
  dynamicBindingPathList: [],
  leftColumn: 0,
  isLoading: false,
  parentId: "",
  renderMode: "CANVAS",
  children: [
    {
      widgetName: "JSONForm1",
      type: "JSON_FORM_WIDGET",
      schema: {
        field1: {
          fieldType: "OBJECT",
          children: {
            switchField: {
              accessor: "Test Switch",
              accentColor: "#553DE9",
              alignWidget: "RIGHT",
              boxShadow: "none",
              children: {},
              dataType: "STRING",
              defaultValue: "",
              fieldType: "Switch",
              identifier: "TEST_IDENTIFIER",
              isCustomField: false,
              isDisabled: false,
              isRequired: false,
              isVisible: true,
              label: "Test Switch",
              labelPosition: "Right",
              labelStyle: "",
              labelTextColor: "",
              labelTextSize: "0.875rem",
              originalIdentifier: "Test Switch",
              position: 0,
              sourceData: "har",
              tooltip: "",
            },
            checkboxField1: {
              accessor: "Test Checkbox 1",
              accentColor: "#553DE9",
              alignWidget: "LEFT",
              boxShadow: "none",
              children: {},
              dataType: "STRING",
              defaultValue: "",
              fieldType: "Checkbox",
              identifier: "TEST_IDENTIFIER_1",
              isCustomField: false,
              isDisabled: false,
              isRequired: false,
              isVisible: true,
              label: "Test Checkbox 1",
              labelPosition: "Left",
              labelStyle: "",
              labelTextColor: "",
              labelTextSize: "0.875rem",
              originalIdentifier: "Test Checkbox 1",
              position: 1,
              sourceData: "har",
              tooltip: "",
            },
            checkboxField2: {
              accessor: "Test Checkbox 2",
              accentColor: "#553DE9",
              alignWidget: "RIGHT",
              boxShadow: "none",
              children: {},
              dataType: "STRING",
              defaultValue: "",
              fieldType: "Checkbox",
              identifier: "TEST_IDENTIFIER_2",
              isCustomField: false,
              isDisabled: false,
              isRequired: false,
              isVisible: true,
              label: "Test Checkbox 2",
              labelPosition: "Left",
              labelStyle: "",
              labelTextColor: "",
              labelTextSize: "0.875rem",
              originalIdentifier: "Test Checkbox 2",
              position: 2,
              sourceData: "har",
              tooltip: "",
            },
          },
        },
      },
      widgetId: "jsonForm1",
      dynamicBindingPathList: [],
      renderMode: "CANVAS",
    },
  ],
};

const outputDsl: DSLWidget = {
  widgetName: "MainContainer",
  backgroundColor: "none",
  rightColumn: 1118,
  snapColumns: 16,
  detachFromLayout: true,
  widgetId: "0",
  topRow: 0,
  bottomRow: 1280,
  containerStyle: "none",
  snapRows: 33,
  parentRowSpace: 1,
  type: "CANVAS_WIDGET",
  canExtend: true,
  version: 15,
  minHeight: 1292,
  parentColumnSpace: 1,
  dynamicTriggerPathList: [],
  dynamicBindingPathList: [],
  leftColumn: 0,
  isLoading: false,
  parentId: "",
  renderMode: "CANVAS",
  children: [
    {
      widgetName: "JSONForm1",
      type: "JSON_FORM_WIDGET",
      schema: {
        field1: {
          fieldType: "OBJECT",
          children: {
            switchField: {
              accessor: "Test Switch",
              accentColor: "#553DE9",
              alignWidget: "LEFT",
              boxShadow: "none",
              children: {},
              dataType: "STRING",
              defaultValue: "",
              fieldType: "Switch",
              identifier: "TEST_IDENTIFIER",
              isCustomField: false,
              isDisabled: false,
              isRequired: false,
              isVisible: true,
              label: "Test Switch",
              labelPosition: "Right",
              labelStyle: "",
              labelTextColor: "",
              labelTextSize: "0.875rem",
              originalIdentifier: "Test Switch",
              position: 0,
              sourceData: "har",
              tooltip: "",
            },
            checkboxField1: {
              accessor: "Test Checkbox 1",
              accentColor: "#553DE9",
              alignWidget: "LEFT",
              boxShadow: "none",
              children: {},
              dataType: "STRING",
              defaultValue: "",
              fieldType: "Checkbox",
              identifier: "TEST_IDENTIFIER_1",
              isCustomField: false,
              isDisabled: false,
              isRequired: false,
              isVisible: true,
              label: "Test Checkbox 1",
              labelPosition: "Right",
              labelStyle: "",
              labelTextColor: "",
              labelTextSize: "0.875rem",
              originalIdentifier: "Test Checkbox 1",
              position: 1,
              sourceData: "har",
              tooltip: "",
            },
            checkboxField2: {
              accessor: "Test Checkbox 2",
              accentColor: "#553DE9",
              alignWidget: "LEFT",
              boxShadow: "none",
              children: {},
              dataType: "STRING",
              defaultValue: "",
              fieldType: "Checkbox",
              identifier: "TEST_IDENTIFIER_2",
              isCustomField: false,
              isDisabled: false,
              isRequired: false,
              isVisible: true,
              label: "Test Checkbox 2",
              labelPosition: "Left",
              labelStyle: "",
              labelTextColor: "",
              labelTextSize: "0.875rem",
              originalIdentifier: "Test Checkbox 2",
              position: 2,
              sourceData: "har",
              tooltip: "",
            },
          },
        },
      },
      widgetId: "jsonForm1",
      dynamicBindingPathList: [],
      renderMode: "CANVAS",
    },
  ],
};

describe("JSON Form Widget Property Migration", () => {
  it("should migrate JSON Form widget properties correctly", () => {
    const newDsl = migrateJsonFormWidgetLabelPositonAndAlignment(inputDsl);
    expect(newDsl).toEqual(outputDsl);
  });
});
