exports.dsl = {
  dsl: {
    widgetName: "MainContainer",
    backgroundColor: "none",
    rightColumn: 1936,
    snapColumns: 64,
    detachFromLayout: true,
    widgetId: "0",
    topRow: 0,
    bottomRow: 1290,
    containerStyle: "none",
    snapRows: 125,
    parentRowSpace: 1,
    type: "CANVAS_WIDGET",
    canExtend: true,
    version: 46,
    minHeight: 1292,
    parentColumnSpace: 1,
    dynamicBindingPathList: [],
    leftColumn: 0,
    children: [
      {
        isVisible: true,
        text: "<h1>{{Input1.text}}</h1>",
        fontSize: "HEADING1",
        fontStyle: "BOLD",
        textAlign: "LEFT",
        textColor: "#231F20",
        widgetName: "Text1",
        version: 1,
        type: "TEXT_WIDGET",
        hideCard: false,
        displayName: "Text",
        key: "4ln743vbxf",
        iconSVG: "/static/media/icon.97c59b52.svg",
        widgetId: "oylox3e28e",
        renderMode: "CANVAS",
        isLoading: false,
        parentColumnSpace: 30.0625,
        parentRowSpace: 10,
        leftColumn: 1,
        rightColumn: 39,
        topRow: 16,
        bottomRow: 40,
        parentId: "0",
        dynamicBindingPathList: [
          {
            key: "text",
          },
        ],
        dynamicTriggerPathList: [],
      },
      {
        isVisible: true,
        inputType: "TEXT",
        label: "",
        widgetName: "Input1",
        version: 1,
        defaultText: "",
        iconAlign: "left",
        autoFocus: false,
        labelStyle: "",
        resetOnSubmit: true,
        isRequired: false,
        isDisabled: false,
        allowCurrencyChange: false,
        type: "INPUT_WIDGET",
        hideCard: false,
        displayName: "Input",
        key: "4xvbov2itw",
        iconSVG: "/static/media/icon.9f505595.svg",
        widgetId: "d454uqlxd0",
        renderMode: "CANVAS",
        isLoading: false,
        parentColumnSpace: 30.0625,
        parentRowSpace: 10,
        leftColumn: 1,
        rightColumn: 12,
        topRow: 9,
        bottomRow: 13,
        parentId: "0",
      },
    ],
  },
};
