import { ResponsiveBehavior } from "layoutSystems/common/utils/constants";
import type { WidgetDefaultProps } from "WidgetProvider/constants";

export const defaultsConfig = {
  widgetName: "ToolbarButtons",
  orientation: "horizontal",
  buttonVariant: "ghost",
  buttonColor: "accent",
  isDisabled: false,
  isVisible: true,
  version: 1,
  animateLoading: true,
  responsiveBehavior: ResponsiveBehavior.Fill,
  buttonsList: {
    button1: {
      label: "Add",
      isVisible: true,
      isDisabled: false,
      widgetId: "",
      id: "button1",
      index: 0,
      iconName: "plus",
      iconAlign: "start",
    },
    button2: {
      label: "Edit",
      isVisible: true,
      isDisabled: false,
      widgetId: "",
      id: "button2",
      index: 1,
      iconName: "pencil",
      iconAlign: "start",
    },
    button3: {
      label: "Copy",
      isVisible: true,
      isDisabled: false,
      widgetId: "",
      id: "button3",
      index: 2,
      iconName: "copy",
      iconAlign: "start",
    },
    separator: {
      isVisible: true,
      isDisabled: false,
      widgetId: "",
      id: "separator",
      index: 2,
      label: "Separator",
      itemType: "SEPARATOR",
    },
    button4: {
      label: "Delete",
      isVisible: true,
      isDisabled: false,
      widgetId: "",
      id: "button4",
      index: 2,
      iconName: "trash",
      iconAlign: "start",
    },
  },
} as unknown as WidgetDefaultProps;
