export const CANVAS_DEFAULT_WIDTH_PX = 1024;
export const CANVAS_DEFAULT_HEIGHT_PX = 1280;
export const CANVAS_DEFAULT_GRID_HEIGHT_PX = 1;
export const CANVAS_DEFAULT_GRID_WIDTH_PX = 1;
export const CANVAS_BACKGROUND_COLOR = "#FFFFFF";
