import { Colors, Color } from "./Colors";

export const appColors = [
  "#FFEFDB",
  "#D9E7FF",
  "#FFDEDE",
  "#E3DEFF",
  "#C7F3E3",
  "#F1DEFF",
  "#F4FFDE",
  "#C7F3F0",
  "#C2DAF0",
  "#F5D1D1",
  "#ECECEC",
  "#CCCCCC",
  "#F3F1C7",
  "#E4D8CC",
  "#EAEDFB",
  "#D6D1F2",
  "#FBF4ED",
  "#FFEBFB",
] as const;

const lightShades = [
  "#FAFAFA",
  "#F7F7F7",
  "#F0F0F0",
  "#E8E8E8",
  "#C5C5C5",
  "#A9A7A7",
  "#939090",
  "#716E6E",
  "#4B4848",
  "#302D2D",
  "#090707",
  "#FFFFFF",
  "#6A86CE",
  "#E0DEDE",
  "#EBEBEB",
  "#858282",
  "#000000",
  "#F86A2B",
] as const;

export const getColorWithOpacity = (color: Color, opacity: number) => {
  color = color.slice(1);
  const val = parseInt(color, 16);
  const r = (val >> 16) & 255;
  const g = (val >> 8) & 255;
  const b = val & 255;
  return `rgba(${r},${g},${b},${opacity})`;
};

export const colorpalette = {
  tooltip: {
    lightBg: lightShades[0],
    lightText: lightShades[10],
    darkBg: lightShades[10],
    darkText: lightShades[0],
  },
  appBackground: "#EDEDED",
  artboard: "#F6F6F6",
  primaryOld: Colors.GREEN,
  primaryDarker: Colors.JUNGLE_GREEN,
  primaryDarkest: Colors.JUNGLE_GREEN_DARKER,
  secondary: Colors.GEYSER_LIGHT,
  secondaryDarker: Colors.CONCRETE,
  secondaryDarkest: Colors.MERCURY,
  error: Colors.ERROR_RED,
  infoOld: Colors.SLATE_GRAY,
  errorMessage: Colors.ERROR_RED,
  hover: Colors.POLAR,
  inputActiveBorder: Colors.HIT_GRAY,
  inputInactiveBG: Colors.AQUA_HAZE,
  textDefault: Colors.BLACK_PEARL,
  textOnDarkBG: Colors.WHITE,
  textOnGreyBG: Colors.CHARCOAL,
  textOnWhiteBG: Colors.CODE_GRAY,
  textAnchor: Colors.PURPLE,
  border: Colors.GEYSER,
  paneCard: Colors.SHARK,
  paneInputBG: Colors.SHARK,
  paneBG: Colors.OUTER_SPACE,
  paneText: Colors.GRAY_CHATEAU,
  paneTextBG: Colors.DEEP_SPACE,
  paneTextUnderline: Colors.LIGHT_GREYISH_BLUE,
  paneSectionLabel: Colors.CADET_BLUE,
  navBG: Colors.SHARK,
  grid: Colors.ALTO2,
  containerBorder: Colors.FRENCH_PASS,
  menuButtonBGInactive: Colors.JUNGLE_MIST,
  menuIconColorInactive: Colors.OXFORD_BLUE,
  bodyBG: Colors.ATHENS_GRAY,
  builderBodyBG: Colors.WHITE,
  widgetMultiSelectBorder: Colors.MALIBU,
  widgetBorder: Colors.SLATE_GRAY,
  widgetLightBorder: Colors.WHITE_SMOKE,
  widgetSecondaryBorder: Colors.MERCURY,
  messageBG: Colors.CONCRETE,
  paneIcon: Colors.TROUT,
  notification: Colors.JAFFA,
  bindingTextDark: Colors.BINDING_COLOR,
  bindingText: Colors.BINDING_COLOR_LT,
  cmBacground: Colors.BLUE_CHARCOAL,
  lightningborder: Colors.ALABASTER,
  formButtonColor: Colors.WHITE,
  appCardColors: appColors,
  dataTypeBg: {
    function: "#BDB2FF",
    object: "#FFD6A5",
    unknown: "#4bb",
    array: "#CDFFA5",
    number: "#FFB2B2",
  },
  scrollbarLight: getColorWithOpacity(Colors.CHARCOAL, 0.5),
  scrollbarLightBG: getColorWithOpacity(Colors.WHITE, 0.5),
  scrollbarDark: getColorWithOpacity(Colors.LIGHT_GREY, 0.5),
  scrollbarDarkBG: getColorWithOpacity(Colors.CODE_GRAY, 0.5),
  dropdownIconBg: Colors.ALTO2,
  welcomeTourStickySidebarColor: Colors.WHITE,
  welcomeTourStickySidebarBackground: "#F86A2B",
  dropdownIconDarkBg: Colors.DARK_GRAY,
  dropdownGreyBg: Colors.Gallery,
};

export type ColorPaletteKeys = keyof typeof colorpalette;
export type ColorPalette = typeof colorpalette;
