export const NAVIGATION_BAR_MENU_WIDTH = "240px";
export const NAVIGATION_BAR_CONTENT_COLOR = "#FFFFFF";
export const NAVIGATION_BAR_BACKGROUND_COLOR = "#262626";
export const NAVIGATION_BAR_DANGER_COLOR = "#F22B2B";
export const NAVIGATION_BAR_MENU_FONT_SIZE = "14px";
