import {
  DISABLE_PREPARED_STATEMENT_CONFIRMATION_HEADING,
  DISABLE_PREPARED_STATEMENT_CONFIRMATION_DESCRIPTION,
  DISABLE_PREPARED_STATEMENT_CONFIRMATION_LEARN_MORE,
  DISABLE_SMART_SUBSTITUTION_CONFIRMATION_HEADING,
  DISABLE_SMART_SUBSTITUTION_CONFIRMATION_DESCRIPTION,
  DISABLE_SMART_SUBSTITUTION_CONFIRMATION_LEARN_MORE,
  DISABLE_BSON_SUBSTITUTION_CONFIRMATION_HEADING,
  DISABLE_BSON_SUBSTITUTION_CONFIRMATION_DESCRIPTION,
  DISABLE_BSON_SUBSTITUTION_CONFIRMATION_LEARN_MORE,
} from "ee/constants/messages";

export enum SecurityModalType {
  PREPARED_STATEMENT = "PREPARED_STATEMENT",
  SMART_SUBSTITUTION = "SMART_SUBSTITUTION",
  BSON_SUBSTITUTION = "BSON_SUBSTITUTION",
}

export interface SecurityModalContent {
  heading: () => string;
  description: () => string;
  learnMore?: {
    text: () => string;
    url: string;
  };
}

export const SECURITY_MODAL_CONTENT: Record<
  SecurityModalType,
  SecurityModalContent
> = {
  [SecurityModalType.PREPARED_STATEMENT]: {
    heading: DISABLE_PREPARED_STATEMENT_CONFIRMATION_HEADING,
    description: DISABLE_PREPARED_STATEMENT_CONFIRMATION_DESCRIPTION,
    learnMore: {
      text: DISABLE_PREPARED_STATEMENT_CONFIRMATION_LEARN_MORE.TEXT,
      url: DISABLE_PREPARED_STATEMENT_CONFIRMATION_LEARN_MORE.URL,
    },
  },
  [SecurityModalType.SMART_SUBSTITUTION]: {
    heading: DISABLE_SMART_SUBSTITUTION_CONFIRMATION_HEADING,
    description: DISABLE_SMART_SUBSTITUTION_CONFIRMATION_DESCRIPTION,
    learnMore: {
      text: DISABLE_SMART_SUBSTITUTION_CONFIRMATION_LEARN_MORE.TEXT,
      url: DISABLE_SMART_SUBSTITUTION_CONFIRMATION_LEARN_MORE.URL,
    },
  },
  [SecurityModalType.BSON_SUBSTITUTION]: {
    heading: DISABLE_BSON_SUBSTITUTION_CONFIRMATION_HEADING,
    description: DISABLE_BSON_SUBSTITUTION_CONFIRMATION_DESCRIPTION,
    learnMore: {
      text: DISABLE_BSON_SUBSTITUTION_CONFIRMATION_LEARN_MORE.TEXT,
      url: DISABLE_BSON_SUBSTITUTION_CONFIRMATION_LEARN_MORE.URL,
    },
  },
};
