import { WidgetProps } from "widgets/BaseWidget";
import { ContainerWidgetProps } from "widgets/ContainerWidget";
import { formWidgetButtonWidgetMigrations } from "./FormWidget";

const input: ContainerWidgetProps<WidgetProps> = {
  widgetName: "MainContainer",
  backgroundColor: "none",
  rightColumn: 1280,
  snapColumns: 64,
  detachFromLayout: true,
  widgetId: "0",
  topRow: 0,
  bottomRow: 1290,
  containerStyle: "none",
  snapRows: 125,
  parentRowSpace: 1,
  type: "CANVAS_WIDGET",
  canExtend: true,
  version: 26,
  minHeight: 1292,
  parentColumnSpace: 1,
  dynamicTriggerPathList: [],
  dynamicBindingPathList: [],
  leftColumn: 0,
  renderMode: "CANVAS",
  isLoading: false,
  children: [
    {
      widgetName: "Form1",
      backgroundColor: "white",
      rightColumn: 41,
      widgetId: "qeznqzmae8",
      topRow: 15,
      bottomRow: 67,
      parentRowSpace: 10,
      isVisible: true,
      type: "FORM_WIDGET",
      parentId: "0",
      isLoading: false,
      parentColumnSpace: 19.8125,
      leftColumn: 13,
      renderMode: "CANVAS",
      version: 1,
      children: [
        {
          widgetName: "Canvas1",
          rightColumn: 554.75,
          detachFromLayout: true,
          widgetId: "h53ef94ppg",
          containerStyle: "none",
          topRow: 0,
          bottomRow: 520,
          parentRowSpace: 1,
          isVisible: true,
          canExtend: false,
          type: "CANVAS_WIDGET",
          version: 1,
          parentId: "qeznqzmae8",
          minHeight: 520,
          isLoading: false,
          parentColumnSpace: 1,
          leftColumn: 0,
          renderMode: "CANVAS",
          children: [
            {
              widgetName: "Text1",
              rightColumn: 25.5,
              textAlign: "LEFT",
              widgetId: "da7c6abwc4",
              topRow: 1,
              bottomRow: 5,
              isVisible: true,
              fontStyle: "BOLD",
              type: "TEXT_WIDGET",
              textColor: "#231F20",
              version: 1,
              parentId: "h53ef94ppg",
              isLoading: false,
              leftColumn: 1.5,
              fontSize: "HEADING1",
              text: "Form",
            },
            {
              resetFormOnClick: true,
              widgetName: "FormButton1",
              rightColumn: 62.4,
              isDefaultClickDisabled: true,
              widgetId: "0k0kdcgus2",
              buttonStyle: "PRIMARY_BUTTON",
              topRow: 45,
              bottomRow: 49,
              recaptchaV2: false,
              isVisible: true,
              type: "FORM_BUTTON_WIDGET",
              version: 1,
              parentId: "h53ef94ppg",
              isLoading: false,
              disabledWhenInvalid: true,
              leftColumn: 46.4,
              text: "Submit",
            },
            {
              resetFormOnClick: true,
              widgetName: "FormButton2",
              rightColumn: 46,
              isDefaultClickDisabled: true,
              widgetId: "yoh0muyis1",
              buttonStyle: "SECONDARY_BUTTON",
              topRow: 45,
              bottomRow: 49,
              recaptchaV2: false,
              isVisible: true,
              type: "FORM_BUTTON_WIDGET",
              version: 1,
              parentId: "h53ef94ppg",
              isLoading: false,
              disabledWhenInvalid: false,
              leftColumn: 30,
              text: "Reset",
            },
          ],
        },
      ],
    },
  ],
};

const output: ContainerWidgetProps<WidgetProps> = {
  widgetName: "MainContainer",
  backgroundColor: "none",
  rightColumn: 1280,
  snapColumns: 64,
  detachFromLayout: true,
  widgetId: "0",
  topRow: 0,
  bottomRow: 1230,
  containerStyle: "none",
  snapRows: 125,
  parentRowSpace: 1,
  type: "CANVAS_WIDGET",
  canExtend: true,
  version: 27,
  minHeight: 1240,
  parentColumnSpace: 1,
  dynamicTriggerPathList: [],
  dynamicBindingPathList: [],
  leftColumn: 0,
  renderMode: "CANVAS",
  isLoading: false,
  children: [
    {
      widgetName: "Form1",
      backgroundColor: "white",
      rightColumn: 41,
      widgetId: "qeznqzmae8",
      topRow: 15,
      bottomRow: 67,
      parentRowSpace: 10,
      isVisible: true,
      type: "FORM_WIDGET",
      parentId: "0",
      isLoading: false,
      parentColumnSpace: 19.8125,
      leftColumn: 13,
      renderMode: "CANVAS",
      version: 1,
      children: [
        {
          widgetName: "Canvas1",
          rightColumn: 554.75,
          detachFromLayout: true,
          widgetId: "h53ef94ppg",
          containerStyle: "none",
          topRow: 0,
          bottomRow: 520,
          parentRowSpace: 1,
          isVisible: true,
          canExtend: false,
          type: "CANVAS_WIDGET",
          version: 1,
          parentId: "qeznqzmae8",
          minHeight: 520,
          isLoading: false,
          parentColumnSpace: 1,
          leftColumn: 0,
          children: [
            {
              widgetName: "Text1",
              rightColumn: 25.5,
              textAlign: "LEFT",
              widgetId: "da7c6abwc4",
              topRow: 1,
              bottomRow: 5,
              isVisible: true,
              fontStyle: "BOLD",
              type: "TEXT_WIDGET",
              textColor: "#231F20",
              version: 1,
              parentId: "h53ef94ppg",
              isLoading: false,
              leftColumn: 1.5,
              fontSize: "HEADING1",
              text: "Form",
            },
            {
              widgetName: "Button1",
              rightColumn: 62.4,
              onClick: '{{resetWidget("Form1", true)}}',
              isDefaultClickDisabled: true,
              widgetId: "0k0kdcgus2",
              buttonStyle: "PRIMARY_BUTTON",
              topRow: 45,
              bottomRow: 49,
              recaptchaV2: false,
              isVisible: true,
              type: "BUTTON_WIDGET",
              version: 1,
              parentId: "h53ef94ppg",
              isLoading: false,
              leftColumn: 46.4,
              text: "Submit",
              isDisabled: false,
            },
            {
              widgetName: "Button2",
              rightColumn: 46,
              onClick: '{{resetWidget("Form1", true)}}',
              isDefaultClickDisabled: true,
              widgetId: "yoh0muyis1",
              buttonStyle: "SECONDARY_BUTTON",
              topRow: 45,
              bottomRow: 49,
              recaptchaV2: false,
              isVisible: true,
              type: "BUTTON_WIDGET",
              version: 1,
              parentId: "h53ef94ppg",
              isLoading: false,
              leftColumn: 30,
              text: "Reset",
              isDisabled: false,
            },
          ],
        },
      ],
    },
  ],
};

describe("Form widget updated form button widget to button widget", () => {
  it("To test dsl updated to remove form btn widget and added button widget with correct props", () => {
    const newDsl = formWidgetButtonWidgetMigrations(input);
    expect(JSON.stringify(newDsl) === JSON.stringify(output));
  });
});
