import { migrateIncorrectDynamicBindingPathLists } from "utils/migrations/IncorrectDynamicBindingPathLists";
import { ContainerWidgetProps } from "widgets/ContainerWidget";
import { WidgetProps } from "widgets/BaseWidget";

const input: ContainerWidgetProps<WidgetProps> = {
  widgetName: "MainContainer",
  backgroundColor: "none",
  rightColumn: 1224,
  snapColumns: 16,
  detachFromLayout: true,
  widgetId: "0",
  topRow: 0,
  bottomRow: 1520,
  containerStyle: "none",
  snapRows: 33,
  parentRowSpace: 1,
  type: "CANVAS_WIDGET",
  canExtend: true,
  version: 12,
  minHeight: 1292,
  parentColumnSpace: 1,
  dynamicBindingPathList: [],
  leftColumn: 0,
  children: [
    {
      isVisible: true,
      widgetName: "Chart1",
      chartType: "LINE_CHART",
      chartName: "Sales on working days",
      allowHorizontalScroll: false,
      version: 1,
      chartData: [
        {
          seriesName: "",
          data: "{{Api1.data}}",
        },
      ],
      xAxisName: "Last Week",
      yAxisName: "Total Order Revenue $",
      type: "CHART_WIDGET",
      isLoading: false,
      parentColumnSpace: 74,
      parentRowSpace: 40,
      leftColumn: 4,
      rightColumn: 10,
      topRow: 6,
      bottomRow: 14,
      parentId: "0",
      widgetId: "x1naz9is2b",
      dynamicBindingPathList: [
        {
          key: "chartData",
        },
        {
          key: "chartData[0].data",
        },
        {
          key: "chartData[1].data",
        },
      ],
    },
    {
      isVisible: true,
      label: "Data",
      widgetName: "Table1",
      searchKey: "",
      textSize: "PARAGRAPH",
      horizontalAlignment: "LEFT",
      verticalAlignment: "CENTER",
      primaryColumns: {
        id: {
          index: 0,
          width: 150,
          id: "id",
          horizontalAlignment: "LEFT",
          verticalAlignment: "CENTER",
          columnType: "text",
          textSize: "PARAGRAPH",
          enableFilter: true,
          enableSort: true,
          isVisible: true,
          isDerived: false,
          label: "id",
          computedValue:
            "{{Table1.sanitizedTableData.map((currentRow) => { return currentRow.id})}}",
        },
        email: {
          index: 1,
          width: 150,
          id: "email",
          horizontalAlignment: "LEFT",
          verticalAlignment: "CENTER",
          columnType: "text",
          textSize: "PARAGRAPH",
          enableFilter: true,
          enableSort: true,
          isVisible: true,
          isDerived: false,
          label: "email",
          computedValue:
            "{{Table1.sanitizedTableData.map((currentRow) => { return currentRow.email})}}",
        },
        userName: {
          index: 2,
          width: 150,
          id: "userName",
          horizontalAlignment: "LEFT",
          verticalAlignment: "CENTER",
          columnType: "text",
          textSize: "PARAGRAPH",
          enableFilter: true,
          enableSort: true,
          isVisible: true,
          isDerived: false,
          label: "userName",
          computedValue:
            "{{Table1.sanitizedTableData.map((currentRow) => { return currentRow.userName})}}",
        },
        productName: {
          index: 3,
          width: 150,
          id: "productName",
          horizontalAlignment: "LEFT",
          verticalAlignment: "CENTER",
          columnType: "text",
          textSize: "PARAGRAPH",
          enableFilter: true,
          enableSort: true,
          isVisible: true,
          isDerived: false,
          label: "productName",
          computedValue:
            "{{Table1.sanitizedTableData.map((currentRow) => { return currentRow.productName})}}",
        },
        orderAmount: {
          index: 4,
          width: 150,
          id: "orderAmount",
          horizontalAlignment: "LEFT",
          verticalAlignment: "CENTER",
          columnType: "text",
          textSize: "PARAGRAPH",
          enableFilter: true,
          enableSort: true,
          isVisible: true,
          isDerived: false,
          label: "orderAmount",
          computedValue:
            "{{Table1.sanitizedTableData.map((currentRow) => { return currentRow.orderAmount})}}",
        },
      },
      derivedColumns: {},
      tableData: "{{Api2.data}}",
      version: 1,
      type: "TABLE_WIDGET",
      isLoading: false,
      parentColumnSpace: 74,
      parentRowSpace: 40,
      leftColumn: 2,
      rightColumn: 10,
      topRow: 19,
      bottomRow: 26,
      parentId: "0",
      widgetId: "lmky5ih0eq",
      columnOrder: ["id", "email", "userName", "productName", "orderAmount"],
      dynamicBindingPathList: [
        {
          key: "tableData",
        },
        {
          key: "primaryColumns.id.computedValue",
        },
        {
          key: "primaryColumns.userName.computedValue",
        },
        {
          key: "primaryColumns.productName.computedValue",
        },
        {
          key: "primaryColumns.orderAmount.computedValue",
        },
        {
          key: "primaryColumns[0].computedValue",
        },
        {
          key: "primaryColumns.0.computedValue",
        },
        {
          key: "primaryColumns.randomColumn.computedValue",
        },
      ],
    },
    {
      isVisible: true,
      backgroundColor: "#FFFFFF",
      widgetName: "Container1",
      containerStyle: "card",
      children: [
        {
          isVisible: true,
          widgetName: "Canvas1",
          version: 1,
          containerStyle: "none",
          canExtend: false,
          detachFromLayout: true,
          children: [
            {
              isVisible: true,
              inputType: "TEXT",
              label: "",
              widgetName: "Input1",
              version: 1,
              resetOnSubmit: true,
              type: "INPUT_WIDGET",
              isLoading: false,
              parentColumnSpace: 34.5,
              parentRowSpace: 40,
              leftColumn: 1,
              rightColumn: 6,
              topRow: 0,
              bottomRow: 1,
              parentId: "k3dkjt4xe0",
              widgetId: "54ap7bl008",
              defaultText: "{{Table1.selectedRow.id}}",
              dynamicBindingPathList: [
                {
                  key: "defaultText",
                },
                {
                  key: "value",
                },
              ],
            },
          ],
          minHeight: 400,
          type: "CANVAS_WIDGET",
          isLoading: false,
          parentColumnSpace: 1,
          parentRowSpace: 1,
          leftColumn: 0,
          rightColumn: 592,
          topRow: 0,
          bottomRow: 400,
          parentId: "1ha00a626q",
          widgetId: "k3dkjt4xe0",
        },
      ],
      version: 1,
      type: "CONTAINER_WIDGET",
      isLoading: false,
      parentColumnSpace: 74,
      parentRowSpace: 40,
      leftColumn: 4,
      rightColumn: 12,
      topRow: 26,
      bottomRow: 36,
      parentId: "0",
      widgetId: "1ha00a626q",
    },
  ],
};

const output: ContainerWidgetProps<WidgetProps> = {
  widgetName: "MainContainer",
  backgroundColor: "none",
  rightColumn: 1224,
  snapColumns: 16,
  detachFromLayout: true,
  widgetId: "0",
  topRow: 0,
  bottomRow: 1520,
  containerStyle: "none",
  snapRows: 33,
  parentRowSpace: 1,
  type: "CANVAS_WIDGET",
  canExtend: true,
  version: 12,
  minHeight: 1292,
  parentColumnSpace: 1,
  dynamicBindingPathList: [],
  leftColumn: 0,
  children: [
    {
      isVisible: true,
      widgetName: "Chart1",
      chartType: "LINE_CHART",
      chartName: "Sales on working days",
      allowHorizontalScroll: false,
      version: 1,
      chartData: [
        {
          seriesName: "",
          data: "{{Api1.data}}",
        },
      ],
      xAxisName: "Last Week",
      yAxisName: "Total Order Revenue $",
      type: "CHART_WIDGET",
      isLoading: false,
      parentColumnSpace: 74,
      parentRowSpace: 40,
      leftColumn: 4,
      rightColumn: 10,
      topRow: 6,
      bottomRow: 14,
      parentId: "0",
      widgetId: "x1naz9is2b",
      dynamicBindingPathList: [
        {
          key: "chartData[0].data",
        },
      ],
    },
    {
      isVisible: true,
      label: "Data",
      widgetName: "Table1",
      searchKey: "",
      textSize: "PARAGRAPH",
      horizontalAlignment: "LEFT",
      verticalAlignment: "CENTER",
      primaryColumns: {
        id: {
          index: 0,
          width: 150,
          id: "id",
          horizontalAlignment: "LEFT",
          verticalAlignment: "CENTER",
          columnType: "text",
          textSize: "PARAGRAPH",
          enableFilter: true,
          enableSort: true,
          isVisible: true,
          isDerived: false,
          label: "id",
          computedValue:
            "{{Table1.sanitizedTableData.map((currentRow) => { return currentRow.id})}}",
        },
        email: {
          index: 1,
          width: 150,
          id: "email",
          horizontalAlignment: "LEFT",
          verticalAlignment: "CENTER",
          columnType: "text",
          textSize: "PARAGRAPH",
          enableFilter: true,
          enableSort: true,
          isVisible: true,
          isDerived: false,
          label: "email",
          computedValue:
            "{{Table1.sanitizedTableData.map((currentRow) => { return currentRow.email})}}",
        },
        userName: {
          index: 2,
          width: 150,
          id: "userName",
          horizontalAlignment: "LEFT",
          verticalAlignment: "CENTER",
          columnType: "text",
          textSize: "PARAGRAPH",
          enableFilter: true,
          enableSort: true,
          isVisible: true,
          isDerived: false,
          label: "userName",
          computedValue:
            "{{Table1.sanitizedTableData.map((currentRow) => { return currentRow.userName})}}",
        },
        productName: {
          index: 3,
          width: 150,
          id: "productName",
          horizontalAlignment: "LEFT",
          verticalAlignment: "CENTER",
          columnType: "text",
          textSize: "PARAGRAPH",
          enableFilter: true,
          enableSort: true,
          isVisible: true,
          isDerived: false,
          label: "productName",
          computedValue:
            "{{Table1.sanitizedTableData.map((currentRow) => { return currentRow.productName})}}",
        },
        orderAmount: {
          index: 4,
          width: 150,
          id: "orderAmount",
          horizontalAlignment: "LEFT",
          verticalAlignment: "CENTER",
          columnType: "text",
          textSize: "PARAGRAPH",
          enableFilter: true,
          enableSort: true,
          isVisible: true,
          isDerived: false,
          label: "orderAmount",
          computedValue:
            "{{Table1.sanitizedTableData.map((currentRow) => { return currentRow.orderAmount})}}",
        },
      },
      derivedColumns: {},
      tableData: "{{Api2.data}}",
      version: 1,
      type: "TABLE_WIDGET",
      isLoading: false,
      parentColumnSpace: 74,
      parentRowSpace: 40,
      leftColumn: 2,
      rightColumn: 10,
      topRow: 19,
      bottomRow: 26,
      parentId: "0",
      widgetId: "lmky5ih0eq",
      columnOrder: ["id", "email", "userName", "productName", "orderAmount"],
      dynamicBindingPathList: [
        {
          key: "tableData",
        },
        {
          key: "primaryColumns.id.computedValue",
        },
        {
          key: "primaryColumns.email.computedValue",
        },
        {
          key: "primaryColumns.userName.computedValue",
        },
        {
          key: "primaryColumns.productName.computedValue",
        },
        {
          key: "primaryColumns.orderAmount.computedValue",
        },
      ],
    },
    {
      isVisible: true,
      backgroundColor: "#FFFFFF",
      widgetName: "Container1",
      containerStyle: "card",
      children: [
        {
          isVisible: true,
          widgetName: "Canvas1",
          version: 1,
          containerStyle: "none",
          canExtend: false,
          detachFromLayout: true,
          children: [
            {
              isVisible: true,
              inputType: "TEXT",
              label: "",
              widgetName: "Input1",
              version: 1,
              resetOnSubmit: true,
              type: "INPUT_WIDGET",
              isLoading: false,
              parentColumnSpace: 34.5,
              parentRowSpace: 40,
              leftColumn: 1,
              rightColumn: 6,
              topRow: 0,
              bottomRow: 1,
              parentId: "k3dkjt4xe0",
              widgetId: "54ap7bl008",
              defaultText: "{{Table1.selectedRow.id}}",
              dynamicBindingPathList: [
                {
                  key: "defaultText",
                },
              ],
            },
          ],
          minHeight: 400,
          type: "CANVAS_WIDGET",
          isLoading: false,
          parentColumnSpace: 1,
          parentRowSpace: 1,
          leftColumn: 0,
          rightColumn: 592,
          topRow: 0,
          bottomRow: 400,
          parentId: "1ha00a626q",
          widgetId: "k3dkjt4xe0",
        },
      ],
      version: 1,
      type: "CONTAINER_WIDGET",
      isLoading: false,
      parentColumnSpace: 74,
      parentRowSpace: 40,
      leftColumn: 4,
      rightColumn: 12,
      topRow: 26,
      bottomRow: 36,
      parentId: "0",
      widgetId: "1ha00a626q",
    },
  ],
};

it("migrates incorrect dynamic binding path lists", () => {
  const result = migrateIncorrectDynamicBindingPathLists(input);
  expect(result).toStrictEqual(output);
});
