import { DSLWidget } from "widgets/constants";
import { migrateInputWidgetDefaultSelectedPhoneNumberCode } from "./InputWidget";

describe("Input Widget Property Pane Upgrade", () => {
  it("To test phoneNumberCountryCode is having dial code instead of country code", () => {
    const inputDsl: DSLWidget = {
      widgetName: "MainContainer",
      backgroundColor: "none",
      rightColumn: 1118,
      snapColumns: 64,
      detachFromLayout: true,
      widgetId: "0",
      topRow: 0,
      bottomRow: 5016,
      containerStyle: "none",
      snapRows: 125,
      parentRowSpace: 1,
      type: "CANVAS_WIDGET",
      canExtend: true,
      version: 41,
      minHeight: 1292,
      parentColumnSpace: 1,
      dynamicBindingPathList: [],
      leftColumn: 0,
      renderMode: "CANVAS",
      isLoading: false,
      children: [
        {
          widgetName: "Input1",
          displayName: "Input",
          iconSVG: "/static/media/icon.e569391a.svg",
          topRow: 6,
          bottomRow: 10,
          parentRowSpace: 10,
          autoFocus: false,
          type: "INPUT_WIDGET",
          phoneNumberCountryCode: "IN",
          hideCard: false,
          parentColumnSpace: 17.28125,
          dynamicTriggerPathList: [],
          resetOnSubmit: true,
          leftColumn: 14,
          dynamicBindingPathList: [],
          labelStyle: "BOLD",
          inputType: "PHONE_NUMBER",
          isDisabled: false,
          key: "umf8qep1vn",
          isRequired: false,
          rightColumn: 34,
          widgetId: "wyxyvtpfsw",
          isVisible: true,
          label: "",
          allowCurrencyChange: false,
          version: 1,
          parentId: "0",
          renderMode: "CANVAS",
          isLoading: false,
          iconAlign: "left",
          defaultText: "",
        },
      ],
    };

    const outputDsl: DSLWidget = {
      widgetName: "MainContainer",
      backgroundColor: "none",
      rightColumn: 1118,
      snapColumns: 64,
      detachFromLayout: true,
      widgetId: "0",
      topRow: 0,
      bottomRow: 5016,
      containerStyle: "none",
      snapRows: 125,
      parentRowSpace: 1,
      type: "CANVAS_WIDGET",
      canExtend: true,
      version: 41,
      minHeight: 1292,
      parentColumnSpace: 1,
      dynamicBindingPathList: [],
      leftColumn: 0,
      renderMode: "CANVAS",
      isLoading: false,
      children: [
        {
          widgetName: "Input1",
          displayName: "Input",
          iconSVG: "/static/media/icon.e569391a.svg",
          topRow: 6,
          bottomRow: 10,
          parentRowSpace: 10,
          autoFocus: false,
          type: "INPUT_WIDGET",
          phoneNumberCountryCode: "+91",
          hideCard: false,
          parentColumnSpace: 17.28125,
          dynamicTriggerPathList: [],
          resetOnSubmit: true,
          leftColumn: 14,
          dynamicBindingPathList: [],
          labelStyle: "BOLD",
          inputType: "PHONE_NUMBER",
          isDisabled: false,
          key: "umf8qep1vn",
          isRequired: false,
          rightColumn: 34,
          widgetId: "wyxyvtpfsw",
          isVisible: true,
          label: "",
          allowCurrencyChange: false,
          version: 1,
          parentId: "0",
          renderMode: "CANVAS",
          isLoading: false,
          iconAlign: "left",
          defaultText: "",
        },
      ],
    };
    const newDsl = migrateInputWidgetDefaultSelectedPhoneNumberCode(inputDsl);
    expect(newDsl).toStrictEqual(outputDsl);
  });

  it("To test currencyCountryCode is binded to currencyCode", () => {
    const inputDsl: DSLWidget = {
      widgetName: "MainContainer",
      backgroundColor: "none",
      rightColumn: 1118,
      snapColumns: 64,
      detachFromLayout: true,
      widgetId: "0",
      topRow: 0,
      bottomRow: 5016,
      containerStyle: "none",
      snapRows: 125,
      parentRowSpace: 1,
      type: "CANVAS_WIDGET",
      canExtend: true,
      version: 43,
      minHeight: 700,
      parentColumnSpace: 1,
      dynamicBindingPathList: [],
      leftColumn: 0,
      children: [
        {
          widgetName: "Input1",
          displayName: "Input",
          iconSVG: "/static/media/icon.9f505595.svg",
          topRow: 15,
          bottomRow: 19,
          parentRowSpace: 10,
          autoFocus: false,
          type: "INPUT_WIDGET",
          hideCard: false,
          parentColumnSpace: 17.28125,
          dynamicTriggerPathList: [],
          resetOnSubmit: true,
          leftColumn: 16,
          dynamicBindingPathList: [],
          labelStyle: "BOLD",
          inputType: "CURRENCY",
          isDisabled: false,
          currencyCountryCode: "AD",
          key: "8fnj1syb0s",
          isRequired: false,
          rightColumn: 36,
          widgetId: "l2sm68nyut",
          isVisible: true,
          label: "",
          allowCurrencyChange: true,
          version: 1,
          parentId: "0",
          renderMode: "CANVAS",
          isLoading: false,
          iconAlign: "left",
          defaultText: "",
        },
        {
          widgetName: "Text1",
          displayName: "Text",
          iconSVG: "/static/media/icon.e6c93592.svg",
          topRow: 24,
          bottomRow: 28,
          parentRowSpace: 10,
          type: "TEXT_WIDGET",
          hideCard: false,
          parentColumnSpace: 17.28125,
          dynamicTriggerPathList: [],
          leftColumn: 15,
          dynamicBindingPathList: [
            {
              key: "text",
            },
          ],
          text: "{{Input1.currencyCountryCode}}",
          key: "2umcw47d8d",
          rightColumn: 31,
          textAlign: "LEFT",
          widgetId: "zp0gap4y1m",
          isVisible: true,
          fontStyle: "BOLD",
          textColor: "#231F20",
          version: 1,
          parentId: "0",
          renderMode: "CANVAS",
          isLoading: false,
          fontSize: "PARAGRAPH",
        },
      ],
    };

    const outputDsl: DSLWidget = {
      widgetName: "MainContainer",
      backgroundColor: "none",
      rightColumn: 1118,
      snapColumns: 64,
      detachFromLayout: true,
      widgetId: "0",
      topRow: 0,
      bottomRow: 5016,
      containerStyle: "none",
      snapRows: 125,
      parentRowSpace: 1,
      type: "CANVAS_WIDGET",
      canExtend: true,
      version: 43,
      minHeight: 700,
      parentColumnSpace: 1,
      dynamicBindingPathList: [],
      leftColumn: 0,
      children: [
        {
          widgetName: "Input1",
          displayName: "Input",
          iconSVG: "/static/media/icon.9f505595.svg",
          topRow: 15,
          bottomRow: 19,
          parentRowSpace: 10,
          autoFocus: false,
          type: "INPUT_WIDGET",
          hideCard: false,
          parentColumnSpace: 17.28125,
          dynamicTriggerPathList: [],
          resetOnSubmit: true,
          leftColumn: 16,
          dynamicBindingPathList: [],
          labelStyle: "BOLD",
          inputType: "CURRENCY",
          isDisabled: false,
          currencyCountryCode: "AD",
          key: "8fnj1syb0s",
          isRequired: false,
          rightColumn: 36,
          widgetId: "l2sm68nyut",
          isVisible: true,
          label: "",
          allowCurrencyChange: true,
          version: 1,
          parentId: "0",
          renderMode: "CANVAS",
          isLoading: false,
          iconAlign: "left",
          defaultText: "",
        },
        {
          widgetName: "Text1",
          displayName: "Text",
          iconSVG: "/static/media/icon.e6c93592.svg",
          topRow: 24,
          bottomRow: 28,
          parentRowSpace: 10,
          type: "TEXT_WIDGET",
          hideCard: false,
          parentColumnSpace: 17.28125,
          dynamicTriggerPathList: [],
          leftColumn: 15,
          dynamicBindingPathList: [
            {
              key: "text",
            },
          ],
          text: "{{Input1.currencyCode}}",
          key: "2umcw47d8d",
          rightColumn: 31,
          textAlign: "LEFT",
          widgetId: "zp0gap4y1m",
          isVisible: true,
          fontStyle: "BOLD",
          textColor: "#231F20",
          version: 1,
          parentId: "0",
          renderMode: "CANVAS",
          isLoading: false,
          fontSize: "PARAGRAPH",
        },
      ],
    };

    const newDsl = migrateInputWidgetDefaultSelectedPhoneNumberCode(inputDsl);
    expect(newDsl).toStrictEqual(outputDsl);
  });
});
