import { DSLWidget } from "widgets/constants";
import { migrateInputWidgetDefaultSelectedPhoneNumberCode } from "./InputWidget";

describe("Input Widget Property Pane Upgrade", () => {
  it("To test phoneNumberCountryCode is having dial code instead of country code", () => {
    const inputDsl: DSLWidget = {
      widgetName: "MainContainer",
      backgroundColor: "none",
      rightColumn: 1118,
      snapColumns: 64,
      detachFromLayout: true,
      widgetId: "0",
      topRow: 0,
      bottomRow: 5016,
      containerStyle: "none",
      snapRows: 125,
      parentRowSpace: 1,
      type: "CANVAS_WIDGET",
      canExtend: true,
      version: 41,
      minHeight: 1292,
      parentColumnSpace: 1,
      dynamicBindingPathList: [],
      leftColumn: 0,
      renderMode: "CANVAS",
      isLoading: false,
      children: [
        {
          widgetName: "Input1",
          displayName: "Input",
          iconSVG: "/static/media/icon.e569391a.svg",
          topRow: 6,
          bottomRow: 10,
          parentRowSpace: 10,
          autoFocus: false,
          type: "INPUT_WIDGET",
          phoneNumberCountryCode: "IN",
          hideCard: false,
          parentColumnSpace: 17.28125,
          dynamicTriggerPathList: [],
          resetOnSubmit: true,
          leftColumn: 14,
          dynamicBindingPathList: [],
          labelStyle: "BOLD",
          inputType: "PHONE_NUMBER",
          isDisabled: false,
          key: "umf8qep1vn",
          isRequired: false,
          rightColumn: 34,
          widgetId: "wyxyvtpfsw",
          isVisible: true,
          label: "",
          allowCurrencyChange: false,
          version: 1,
          parentId: "0",
          renderMode: "CANVAS",
          isLoading: false,
          iconAlign: "left",
          defaultText: "",
        },
      ],
    };

    const outputDsl: DSLWidget = {
      widgetName: "MainContainer",
      backgroundColor: "none",
      rightColumn: 1118,
      snapColumns: 64,
      detachFromLayout: true,
      widgetId: "0",
      topRow: 0,
      bottomRow: 5016,
      containerStyle: "none",
      snapRows: 125,
      parentRowSpace: 1,
      type: "CANVAS_WIDGET",
      canExtend: true,
      version: 41,
      minHeight: 1292,
      parentColumnSpace: 1,
      dynamicBindingPathList: [],
      leftColumn: 0,
      renderMode: "CANVAS",
      isLoading: false,
      children: [
        {
          widgetName: "Input1",
          displayName: "Input",
          iconSVG: "/static/media/icon.e569391a.svg",
          topRow: 6,
          bottomRow: 10,
          parentRowSpace: 10,
          autoFocus: false,
          type: "INPUT_WIDGET",
          phoneNumberCountryCode: "+91",
          hideCard: false,
          parentColumnSpace: 17.28125,
          dynamicTriggerPathList: [],
          resetOnSubmit: true,
          leftColumn: 14,
          dynamicBindingPathList: [],
          labelStyle: "BOLD",
          inputType: "PHONE_NUMBER",
          isDisabled: false,
          key: "umf8qep1vn",
          isRequired: false,
          rightColumn: 34,
          widgetId: "wyxyvtpfsw",
          isVisible: true,
          label: "",
          allowCurrencyChange: false,
          version: 1,
          parentId: "0",
          renderMode: "CANVAS",
          isLoading: false,
          iconAlign: "left",
          defaultText: "",
        },
      ],
    };
    const newDsl = migrateInputWidgetDefaultSelectedPhoneNumberCode(inputDsl);
    expect(newDsl).toStrictEqual(outputDsl);
  });
});
