import { ObjectsRegistry } from "../Objects/Registry";

export const agHelper = ObjectsRegistry.AggregateHelper;
export const locators = ObjectsRegistry.CommonLocators;
export const entityExplorer = ObjectsRegistry.EntityExplorer;
export const jsEditor = ObjectsRegistry.JSEditor;
export const propPane = ObjectsRegistry.PropertyPane;
export const deployMode = ObjectsRegistry.DeployMode;
export const appSettings = ObjectsRegistry.AppSettings;
export const generalSettings = ObjectsRegistry.GeneralSettings;
export const pageSettings = ObjectsRegistry.PageSettings;
export const embedSettings = ObjectsRegistry.EmbedSettings;
export const homePage = ObjectsRegistry.HomePage;
export const theme = ObjectsRegistry.ThemeSettings;
export const gitSync = ObjectsRegistry.GitSync;
export const apiPage = ObjectsRegistry.ApiPage;
export const adminSettings = ObjectsRegistry.AdminSettings;
export const dataSources = ObjectsRegistry.DataSources;
export const inviteModal = ObjectsRegistry.InviteModal;
export const table = ObjectsRegistry.Table;
export const debuggerHelper = ObjectsRegistry.DebuggerHelper;
export const templates = ObjectsRegistry.Templates;
export const peekOverlay = ObjectsRegistry.PeekOverlay;
export const installer = ObjectsRegistry.LibraryInstaller;
