package com.appsmith.server.repositories;

import com.appsmith.server.repositories.ce.CustomDatasourceStorageStructureRepositoryCE;

public interface CustomDatasourceStorageStructureRepository extends CustomDatasourceStorageStructureRepositoryCE {}
