package com.appsmith.server.repositories;

import com.appsmith.server.repositories.ce.CustomDatasourceConfigurationStructureRepositoryCE;

public interface CustomDatasourceConfigurationStructureRepository extends CustomDatasourceConfigurationStructureRepositoryCE {
}
