set -o nounset

mongo_uri="$1"
disable_telemetry="$2"

cat<<EOF
apiVersion: v1
kind: ConfigMap
metadata:
  name: application-config
data:
  APPSMITH_OAUTH2_GOOGLE_CLIENT_ID: ""
  APPSMITH_OAUTH2_GOOGLE_CLIENT_SECRET: ""
  APPSMITH_OAUTH2_GITHUB_CLIENT_ID: ""
  APPSMITH_OAUTH2_GITHUB_CLIENT_SECRET: ""
  APPSMITH_CLIENT_LOG_LEVEL: ""
  APPSMITH_GOOGLE_MAPS_API_KEY: ""
  APPSMITH_MAIL_ENABLED: "false"
  APPSMITH_MAIL_HOST: ""
  APPSMITH_MAIL_PORT: ""
  APPSMITH_MAIL_USERNAME: ""
  APPSMITH_MAIL_PASSWORD: ""
  APPSMITH_MAIL_FROM: ""
  APPSMITH_REPLY_TO: ""
  APPSMITH_MAIL_SMTP_AUTH: ""
  APPSMITH_MAIL_SMTP_TLS_ENABLED: ""
  APPSMITH_DISABLE_TELEMETRY: "$disable_telemetry"
  APPSMITH_RECAPTCHA_SITE_KEY: ""
  APPSMITH_RECAPTCHA_SECRET_KEY: ""
  APPSMITH_RECAPTCHA_ENABLED: "false"
  APPSMITH_DISABLE_INTERCOM: "false"
  APPSMITH_MONGODB_URI: "$mongo_uri"
  APPSMITH_REDIS_URL: "redis://127.0.0.1:6379"
EOF
