import {
  FlexVerticalAlignment,
  ResponsiveBehavior,
} from "layoutSystems/common/utils/constants";
import type { UpdatedDSLPostDelete } from "./WidgetDeletionSagas";
import { RenderModes } from "constants/WidgetConstants";

export const selectedWidget = {
  isVisible: true,
  type: "LIST_WIDGET_V2",
  backgroundColor: "transparent",
  itemBackgroundColor: "#FFFFFF",
  requiresFlatWidgetChildren: true,
  hasMetaWidgets: true,
  animateLoading: true,
  gridType: "vertical",
  minWidth: 450,
  responsiveBehavior: "fill",
  flexVerticalAlignment: "start",
  dynamicBindingPathList: [
    {
      key: "currentItemsView",
    },
    {
      key: "selectedItemView",
    },
    {
      key: "triggeredItemView",
    },
    {
      key: "primaryKeys",
    },
    {
      key: "accentColor",
    },
    {
      key: "borderRadius",
    },
    {
      key: "boxShadow",
    },
  ],
  currentItemsView: "{{[]}}",
  selectedItemView: "{{{}}}",
  triggeredItemView: "{{{}}}",
  enhancements: true,
  itemSpacing: 8,
  templateHeight: 160,
  listData: [
    {
      id: "001",
      name: "Blue",
      img: "https://assets.appsmith.com/widgets/default.png",
    },
    {
      id: "002",
      name: "Green",
      img: "https://assets.appsmith.com/widgets/default.png",
    },
    {
      id: "003",
      name: "Red",
      img: "https://assets.appsmith.com/widgets/default.png",
    },
  ],
  pageSize: 3,
  widgetName: "List1",
  children: ["7k233hsaeh"],
  additionalStaticProps: [
    "level",
    "levelData",
    "prefixMetaWidgetId",
    "metaWidgetId",
  ],
  primaryKeys:
    '{{List1.listData.map((currentItem, currentIndex) => currentItem["id"] )}}',
  key: "6tleh26qkb",
  isCanvas: true,
  needsErrorInfo: false,
  widgetId: "44ys7bu8r1",
  renderMode: "CANVAS",
  accentColor: "{{appsmith.theme.colors.primaryColor}}",
  borderRadius: "{{appsmith.theme.borderRadius.appBorderRadius}}",
  boxShadow: "{{appsmith.theme.boxShadow.appBoxShadow}}",
  isLoading: false,
  parentColumnSpace: 29.59375,
  parentRowSpace: 10,
  leftColumn: 22,
  rightColumn: 46,
  topRow: 14,
  bottomRow: 54,
  mobileLeftColumn: 22,
  mobileRightColumn: 46,
  mobileTopRow: 14,
  mobileBottomRow: 54,
  parentId: "0",
  mainContainerId: "n31d07fxy1",
  mainCanvasId: "7k233hsaeh",
};

export const stateWidget = {
  isVisible: true,
  type: "LIST_WIDGET_V2",
  backgroundColor: "transparent",
  itemBackgroundColor: "#FFFFFF",
  requiresFlatWidgetChildren: true,
  hasMetaWidgets: true,
  animateLoading: true,
  gridType: "vertical",
  minWidth: 450,
  responsiveBehavior: "fill",
  flexVerticalAlignment: "start",
  dynamicBindingPathList: [
    {
      key: "currentItemsView",
    },
    {
      key: "selectedItemView",
    },
    {
      key: "triggeredItemView",
    },
    {
      key: "primaryKeys",
    },
    {
      key: "accentColor",
    },
    {
      key: "borderRadius",
    },
    {
      key: "boxShadow",
    },
  ],
  currentItemsView: "{{[]}}",
  selectedItemView: "{{{}}}",
  triggeredItemView: "{{{}}}",
  enhancements: true,
  itemSpacing: 8,
  templateHeight: 160,
  listData: [
    {
      id: "001",
      name: "Blue",
      img: "https://assets.appsmith.com/widgets/default.png",
    },
    {
      id: "002",
      name: "Green",
      img: "https://assets.appsmith.com/widgets/default.png",
    },
    {
      id: "003",
      name: "Red",
      img: "https://assets.appsmith.com/widgets/default.png",
    },
  ],
  pageSize: 3,
  widgetName: "List1",
  children: ["hge9o90wnk"],
  additionalStaticProps: [
    "level",
    "levelData",
    "prefixMetaWidgetId",
    "metaWidgetId",
  ],
  primaryKeys:
    '{{List1.listData.map((currentItem, currentIndex) => currentItem["id"] )}}',
  key: "dgeqcbr3ev",
  isCanvas: true,
  needsErrorInfo: false,
  widgetId: "y2w9aaaoln",
  renderMode: "CANVAS",
  accentColor: "{{appsmith.theme.colors.primaryColor}}",
  borderRadius: "{{appsmith.theme.borderRadius.appBorderRadius}}",
  boxShadow: "{{appsmith.theme.boxShadow.appBoxShadow}}",
  isLoading: false,
  parentColumnSpace: 29.59375,
  parentRowSpace: 10,
  leftColumn: 18,
  rightColumn: 42,
  topRow: 13,
  bottomRow: 53,
  mobileLeftColumn: 18,
  mobileRightColumn: 42,
  mobileTopRow: 13,
  mobileBottomRow: 53,
  parentId: "0",
  mainContainerId: "2d5hr5ad75",
  mainCanvasId: "hge9o90wnk",
};

export const updatedDSL: UpdatedDSLPostDelete = {
  finalWidgets: {
    "0": {
      widgetName: "MainContainer",
      renderMode: RenderModes.CANVAS,
      isLoading: false,
      backgroundColor: "none",
      rightColumn: 4896,
      snapColumns: 64,
      detachFromLayout: true,
      widgetId: "0",
      topRow: 0,
      bottomRow: 530,
      containerStyle: "none",
      snapRows: 124,
      parentRowSpace: 1,
      type: "CANVAS_WIDGET",
      canExtend: true,
      version: 90,
      minHeight: 1292,
      dynamicTriggerPathList: [],
      parentColumnSpace: 1,
      dynamicBindingPathList: [],
      leftColumn: 0,
      children: [],
    },
  },
  otherWidgetsToDelete: [
    {
      isVisible: true,
      type: "LIST_WIDGET_V2",
      backgroundColor: "transparent",
      itemBackgroundColor: "#FFFFFF",
      requiresFlatWidgetChildren: true,
      hasMetaWidgets: true,
      animateLoading: true,
      gridType: "vertical",
      version: 1,
      minWidth: 450,
      responsiveBehavior: ResponsiveBehavior.Fill,
      flexVerticalAlignment: FlexVerticalAlignment.Center,
      dynamicBindingPathList: [
        {
          key: "currentItemsView",
        },
        {
          key: "selectedItemView",
        },
        {
          key: "triggeredItemView",
        },
        {
          key: "primaryKeys",
        },
        {
          key: "accentColor",
        },
        {
          key: "borderRadius",
        },
        {
          key: "boxShadow",
        },
      ],
      currentItemsView: "{{[]}}",
      selectedItemView: "{{{}}}",
      triggeredItemView: "{{{}}}",
      enhancements: true,
      itemSpacing: 8,
      templateHeight: 160,
      listData: [
        {
          id: "001",
          name: "Blue",
          img: "https://assets.appsmith.com/widgets/default.png",
        },
        {
          id: "002",
          name: "Green",
          img: "https://assets.appsmith.com/widgets/default.png",
        },
        {
          id: "003",
          name: "Red",
          img: "https://assets.appsmith.com/widgets/default.png",
        },
      ],
      pageSize: 3,
      widgetName: "List1",
      children: ["hge9o90wnk"],
      additionalStaticProps: [
        "level",
        "levelData",
        "prefixMetaWidgetId",
        "metaWidgetId",
      ],
      primaryKeys:
        '{{List1.listData.map((currentItem, currentIndex) => currentItem["id"] )}}',
      key: "dgeqcbr3ev",
      isCanvas: true,
      needsErrorInfo: false,
      widgetId: "y2w9aaaoln",
      renderMode: "CANVAS",
      accentColor: "{{appsmith.theme.colors.primaryColor}}",
      borderRadius: "{{appsmith.theme.borderRadius.appBorderRadius}}",
      boxShadow: "{{appsmith.theme.boxShadow.appBoxShadow}}",
      isLoading: false,
      parentColumnSpace: 29.59375,
      parentRowSpace: 10,
      leftColumn: 18,
      rightColumn: 42,
      topRow: 13,
      bottomRow: 53,
      mobileLeftColumn: 18,
      mobileRightColumn: 42,
      mobileTopRow: 13,
      mobileBottomRow: 53,
      parentId: "0",
      mainContainerId: "2d5hr5ad75",
      mainCanvasId: "hge9o90wnk",
    },
    {
      isVisible: true,
      type: "CANVAS_WIDGET",
      widgetName: "Canvas1",
      version: 1,
      detachFromLayout: true,
      flexLayers: [],
      responsiveBehavior: ResponsiveBehavior.Fill,
      minWidth: 450,
      minDynamicHeight: 4,
      maxDynamicHeight: 9000,
      dynamicHeight: "AUTO_HEIGHT",
      key: "prt1hmnjzd",
      needsErrorInfo: false,
      containerStyle: "none",
      canExtend: false,
      dropDisabled: true,
      openParentPropertyPane: true,
      noPad: true,
      children: ["2d5hr5ad75"],
      minHeight: 400,
      widgetId: "hge9o90wnk",
      renderMode: "CANVAS",
      borderRadius: "{{appsmith.theme.borderRadius.appBorderRadius}}",
      boxShadow: "{{appsmith.theme.boxShadow.appBoxShadow}}",
      isLoading: false,
      parentColumnSpace: 1,
      parentRowSpace: 1,
      leftColumn: 0,
      rightColumn: 710.25,
      topRow: 0,
      bottomRow: 400,
      mobileLeftColumn: 0,
      mobileRightColumn: 710.25,
      mobileTopRow: 0,
      mobileBottomRow: 400,
      parentId: "y2w9aaaoln",
      dynamicBindingPathList: [
        {
          key: "borderRadius",
        },
        {
          key: "boxShadow",
        },
      ],
    },
    {
      isVisible: true,
      type: "CONTAINER_WIDGET",
      backgroundColor: "white",
      widgetName: "Container1",
      containerStyle: "card",
      borderColor: "#E0DEDE",
      borderWidth: "1",
      boxShadow: "{{appsmith.theme.boxShadow.appBoxShadow}}",
      animateLoading: true,
      children: ["grxrg85g2s"],
      version: 1,
      flexVerticalAlignment: FlexVerticalAlignment.Stretch,
      responsiveBehavior: ResponsiveBehavior.Fill,
      parentColumnSpace: 10,
      parentRowSpace: 10,
      minWidth: 450,
      minDynamicHeight: 10,
      maxDynamicHeight: 9000,
      dynamicHeight: "FIXED",
      shouldScrollContents: false,
      key: "jd71btykgv",
      isCanvas: true,
      needsErrorInfo: false,
      dragDisabled: true,
      isDeletable: false,
      isListItemContainer: true,
      disallowCopy: true,
      noContainerOffset: true,
      positioning: "fixed",
      disabledWidgetFeatures: ["dynamicHeight"],
      widgetId: "2d5hr5ad75",
      renderMode: "CANVAS",
      borderRadius: "{{appsmith.theme.borderRadius.appBorderRadius}}",
      isLoading: false,
      leftColumn: 0,
      rightColumn: 64,
      topRow: 0,
      bottomRow: 12,
      mobileLeftColumn: 0,
      mobileRightColumn: 64,
      mobileTopRow: 0,
      mobileBottomRow: 12,
      parentId: "hge9o90wnk",
      dynamicBindingPathList: [
        {
          key: "borderRadius",
        },
        {
          key: "boxShadow",
        },
      ],
    },
    {
      isVisible: true,
      type: "CANVAS_WIDGET",
      widgetName: "Canvas2",
      version: 1,
      detachFromLayout: true,
      flexLayers: [],
      responsiveBehavior: ResponsiveBehavior.Fill,
      minWidth: 450,
      minDynamicHeight: 4,
      maxDynamicHeight: 9000,
      dynamicHeight: "AUTO_HEIGHT",
      key: "prt1hmnjzd",
      needsErrorInfo: false,
      containerStyle: "none",
      canExtend: false,
      children: ["lpohqxv6lj", "5779ts6v9y", "csb5ibtb4o"],
      useAutoLayout: false,
      minHeight: undefined,
      widgetId: "grxrg85g2s",
      renderMode: "CANVAS",
      borderRadius: "{{appsmith.theme.borderRadius.appBorderRadius}}",
      boxShadow: "{{appsmith.theme.boxShadow.appBoxShadow}}",
      isLoading: false,
      parentColumnSpace: 1,
      parentRowSpace: 1,
      leftColumn: 0,
      rightColumn: 0,
      topRow: 0,
      bottomRow: 120,
      mobileLeftColumn: 0,
      mobileRightColumn: undefined,
      mobileTopRow: 0,
      mobileBottomRow: undefined,
      parentId: "2d5hr5ad75",
      dynamicBindingPathList: [
        {
          key: "borderRadius",
        },
        {
          key: "boxShadow",
        },
      ],
    },
    {
      isVisible: true,
      type: "IMAGE_WIDGET",
      defaultImage: "https://assets.appsmith.com/widgets/default.png",
      imageShape: "RECTANGLE",
      maxZoomLevel: 1,
      enableRotation: false,
      enableDownload: false,
      objectFit: "cover",
      image: "{{currentItem.img}}",
      widgetName: "Image1",
      version: 1,
      animateLoading: true,
      flexVerticalAlignment: FlexVerticalAlignment.Stretch,
      key: "af9kkhgp5q",
      parentColumnSpace: 0,
      parentRowSpace: 0,
      needsErrorInfo: false,
      boxShadow: "none",
      dynamicBindingPathList: [
        {
          key: "image",
        },
        {
          key: "borderRadius",
        },
      ],
      dynamicTriggerPathList: [],
      widgetId: "lpohqxv6lj",
      renderMode: "CANVAS",
      borderRadius: "{{appsmith.theme.borderRadius.appBorderRadius}}",
      isLoading: false,
      leftColumn: 0,
      rightColumn: 16,
      topRow: 0,
      bottomRow: 8,
      mobileLeftColumn: 0,
      mobileRightColumn: 16,
      mobileTopRow: 0,
      mobileBottomRow: 8,
      parentId: "grxrg85g2s",
    },
    {
      isVisible: true,
      type: "TEXT_WIDGET",
      text: "{{currentItem.name}}",
      fontSize: "1rem",
      fontStyle: "BOLD",
      textAlign: "LEFT",
      textColor: "#231F20",
      widgetName: "Text1",
      shouldTruncate: false,
      overflow: "NONE",
      version: 1,
      animateLoading: true,
      responsiveBehavior: ResponsiveBehavior.Fill,
      parentColumnSpace: 0,
      parentRowSpace: 0,
      minWidth: 450,
      minDynamicHeight: 4,
      maxDynamicHeight: 9000,
      dynamicHeight: "FIXED",
      key: "1qm6xo8t9y",
      needsErrorInfo: false,
      textStyle: "HEADING",
      boxShadow: "none",
      dynamicBindingPathList: [
        {
          key: "text",
        },
        {
          key: "truncateButtonColor",
        },
        {
          key: "fontFamily",
        },
        {
          key: "borderRadius",
        },
        {
          key: "text",
        },
      ],
      dynamicTriggerPathList: [],
      widgetId: "5779ts6v9y",
      renderMode: "CANVAS",
      truncateButtonColor: "{{appsmith.theme.colors.primaryColor}}",
      fontFamily: "{{appsmith.theme.fontFamily.appFont}}",
      borderRadius: "{{appsmith.theme.borderRadius.appBorderRadius}}",
      isLoading: false,
      leftColumn: 16,
      rightColumn: 28,
      topRow: 0,
      bottomRow: 4,
      mobileLeftColumn: 16,
      mobileRightColumn: 28,
      mobileTopRow: 0,
      mobileBottomRow: 4,
      parentId: "grxrg85g2s",
    },
    {
      isVisible: true,
      type: "TEXT_WIDGET",
      text: "{{currentItem.id}}",
      fontSize: "1rem",
      fontStyle: "BOLD",
      textAlign: "LEFT",
      textColor: "#231F20",
      widgetName: "Text2",
      shouldTruncate: false,
      overflow: "NONE",
      version: 1,
      animateLoading: true,
      responsiveBehavior: ResponsiveBehavior.Fill,
      parentColumnSpace: 0,
      parentRowSpace: 0,
      minWidth: 450,
      minDynamicHeight: 4,
      maxDynamicHeight: 9000,
      dynamicHeight: "FIXED",
      key: "1qm6xo8t9y",
      needsErrorInfo: false,
      textStyle: "BODY",
      boxShadow: "none",
      dynamicBindingPathList: [
        {
          key: "text",
        },
        {
          key: "truncateButtonColor",
        },
        {
          key: "fontFamily",
        },
        {
          key: "borderRadius",
        },
        {
          key: "text",
        },
      ],
      dynamicTriggerPathList: [],
      widgetId: "csb5ibtb4o",
      renderMode: "CANVAS",
      truncateButtonColor: "{{appsmith.theme.colors.primaryColor}}",
      fontFamily: "{{appsmith.theme.fontFamily.appFont}}",
      borderRadius: "{{appsmith.theme.borderRadius.appBorderRadius}}",
      isLoading: false,
      leftColumn: 16,
      rightColumn: 24,
      topRow: 4,
      bottomRow: 8,
      mobileLeftColumn: 16,
      mobileRightColumn: 24,
      mobileTopRow: 4,
      mobileBottomRow: 8,
      parentId: "grxrg85g2s",
    },
  ],
  widgetName: "List1",
};
