import { getAssetUrl } from "ee/utils/airgapHelpers";
import { ASSETS_CDN_URL } from "constants/ThirdPartyConstants";
import type { FlattenedWidgetProps } from "WidgetProvider/constants";

export const simpleListInput = {
  containerParentId: "c9cgrw1iky",
  mainContainerId: "eejdk7ibci",
  mainContainerCanvasId: "y57vj73onh",
  templateWidgets: {
    c9cgrw1iky: {
      boxShadow: "none",
      widgetName: "Canvas1",
      displayName: "Canvas",
      topRow: 0,
      bottomRow: 400,
      parentRowSpace: 1,
      type: "CANVAS_WIDGET",
      canExtend: false,
      hideCard: true,
      dropDisabled: true,
      openParentPropertyPane: true,
      minHeight: 400,
      noPad: true,
      parentColumnSpace: 1,
      leftColumn: 0,
      dynamicBindingPathList: [
        {
          key: "borderRadius",
        },
        {
          key: "accentColor",
        },
      ],
      children: ["eejdk7ibci"],
      key: "5vnwufgrht",
      isDeprecated: false,
      rightColumn: 433.5,
      detachFromLayout: true,
      widgetId: "c9cgrw1iky",
      accentColor: "{{appsmith.theme.colors.primaryColor}}",
      containerStyle: "none",
      isVisible: true,
      version: 1,
      parentId: "c77j9jua6b",
      renderMode: "CANVAS",
      isLoading: false,
      borderRadius: "{{appsmith.theme.borderRadius.appBorderRadius}}",
    },
    eejdk7ibci: {
      boxShadow: "{{appsmith.theme.boxShadow.appBoxShadow}}",
      widgetName: "Container1",
      borderColor: "#E0DEDE",
      disallowCopy: true,
      isCanvas: true,
      displayName: "Container",
      iconSVG: "/static/media/icon.1977dca3370505e2db3a8e44cfd54907.svg",
      searchTags: ["div", "parent", "group"],
      topRow: 0,
      bottomRow: 12,
      dragDisabled: true,
      type: "CONTAINER_WIDGET",
      hideCard: false,
      isDeletable: false,
      animateLoading: true,
      leftColumn: 0,
      dynamicBindingPathList: [
        {
          key: "borderRadius",
        },
        {
          key: "boxShadow",
        },
      ],
      children: ["y57vj73onh"],
      borderWidth: "1",
      key: "xsysw7p962",
      backgroundColor: "white",
      isDeprecated: false,
      rightColumn: 64,
      widgetId: "eejdk7ibci",
      containerStyle: "card",
      isVisible: true,
      version: 1,
      parentId: "c9cgrw1iky",
      renderMode: "CANVAS",
      isLoading: false,
      borderRadius: "{{appsmith.theme.borderRadius.appBorderRadius}}",
    },
    y57vj73onh: {
      boxShadow: "none",
      widgetName: "Canvas2",
      displayName: "Canvas",
      topRow: 0,
      parentRowSpace: 1,
      type: "CANVAS_WIDGET",
      canExtend: false,
      hideCard: true,
      parentColumnSpace: 1,
      leftColumn: 0,
      dynamicBindingPathList: [
        {
          key: "borderRadius",
        },
        {
          key: "accentColor",
        },
      ],
      children: ["epowimtfiu", "lbvm24hgek", "zlo9748tza", "0jneiqpr4z"],
      key: "5vnwufgrht",
      isDeprecated: false,
      detachFromLayout: true,
      widgetId: "y57vj73onh",
      accentColor: "{{appsmith.theme.colors.primaryColor}}",
      containerStyle: "none",
      isVisible: true,
      version: 1,
      parentId: "eejdk7ibci",
      renderMode: "CANVAS",
      isLoading: false,
      borderRadius: "{{appsmith.theme.borderRadius.appBorderRadius}}",
    },
    epowimtfiu: {
      boxShadow: "none",
      widgetName: "Image1",
      displayName: "Image",
      iconSVG: "/static/media/icon.52d8fb963abcb95c79b10f1553389f22.svg",
      topRow: 0,
      bottomRow: 8,
      type: "IMAGE_WIDGET",
      hideCard: false,
      animateLoading: true,
      dynamicTriggerPathList: [],
      imageShape: "RECTANGLE",
      dynamicBindingPathList: [
        {
          key: "image",
        },
        {
          key: "borderRadius",
        },
      ],
      leftColumn: 0,
      defaultImage: getAssetUrl(`${ASSETS_CDN_URL}/widgets/default.png`),
      key: "47mo8av09c",
      image: "{{currentItem.img}}",
      isDeprecated: false,
      rightColumn: 16,
      objectFit: "cover",
      widgetId: "epowimtfiu",
      isVisible: true,
      version: 1,
      parentId: "y57vj73onh",
      renderMode: "CANVAS",
      isLoading: false,
      maxZoomLevel: 1,
      enableDownload: false,
      borderRadius: "{{appsmith.theme.borderRadius.appBorderRadius}}",
      enableRotation: false,
    },
    lbvm24hgek: {
      boxShadow: "none",
      widgetName: "Text1",
      displayName: "Text",
      iconSVG: "/static/media/icon.97c59b523e6f70ba6f40a10fc2c7c5b5.svg",
      searchTags: ["typography", "paragraph", "label"],
      topRow: 0,
      bottomRow: 4,
      type: "TEXT_WIDGET",
      hideCard: false,
      animateLoading: true,
      overflow: "NONE",
      dynamicTriggerPathList: [],
      fontFamily: "{{appsmith.theme.fontFamily.appFont}}",
      dynamicBindingPathList: [
        {
          key: "text",
        },
        {
          key: "truncateButtonColor",
        },
        {
          key: "fontFamily",
        },
        {
          key: "borderRadius",
        },
      ],
      leftColumn: 16,
      shouldTruncate: false,
      truncateButtonColor: "{{appsmith.theme.colors.primaryColor}}",
      text: "{{currentItem.name}}",
      key: "oz7gvds07q",
      isDeprecated: false,
      rightColumn: 28,
      textAlign: "LEFT",
      widgetId: "lbvm24hgek",
      isVisible: true,
      fontStyle: "BOLD",
      textColor: "#231F20",
      version: 1,
      parentId: "y57vj73onh",
      renderMode: "CANVAS",
      isLoading: false,
      borderRadius: "{{appsmith.theme.borderRadius.appBorderRadius}}",
      fontSize: "1rem",
      textStyle: "HEADING",
    },
    zlo9748tza: {
      boxShadow: "none",
      widgetName: "Text2",
      displayName: "Text",
      iconSVG: "/static/media/icon.97c59b523e6f70ba6f40a10fc2c7c5b5.svg",
      searchTags: ["typography", "paragraph", "label"],
      topRow: 4,
      bottomRow: 8,
      type: "TEXT_WIDGET",
      hideCard: false,
      animateLoading: true,
      overflow: "NONE",
      dynamicTriggerPathList: [],
      fontFamily: "{{appsmith.theme.fontFamily.appFont}}",
      dynamicBindingPathList: [
        {
          key: "text",
        },
        {
          key: "truncateButtonColor",
        },
        {
          key: "fontFamily",
        },
        {
          key: "borderRadius",
        },
      ],
      leftColumn: 16,
      shouldTruncate: false,
      truncateButtonColor: "{{appsmith.theme.colors.primaryColor}}",
      text: "{{currentItem.id}}",
      key: "oz7gvds07q",
      isDeprecated: false,
      rightColumn: 24,
      textAlign: "LEFT",
      widgetId: "zlo9748tza",
      isVisible: true,
      fontStyle: "BOLD",
      textColor: "#231F20",
      version: 1,
      parentId: "y57vj73onh",
      renderMode: "CANVAS",
      isLoading: false,
      borderRadius: "{{appsmith.theme.borderRadius.appBorderRadius}}",
      fontSize: "1rem",
      textStyle: "BODY",
    },
    "0jneiqpr4z": {
      boxShadow: "none",
      widgetName: "Input1",
      displayName: "Input",
      iconSVG: "/static/media/icon.9f505595da61a34f563dba82adeb06ec.svg",
      searchTags: ["form", "text input", "number", "textarea"],
      topRow: 1,
      bottomRow: 8,
      parentRowSpace: 10,
      labelWidth: 5,
      autoFocus: false,
      type: "INPUT_WIDGET_V2",
      hideCard: false,
      animateLoading: true,
      parentColumnSpace: 15.5234375,
      dynamicTriggerPathList: [],
      resetOnSubmit: true,
      leftColumn: 36,
      dynamicBindingPathList: [
        {
          key: "accentColor",
        },
        {
          key: "borderRadius",
        },
      ],
      labelPosition: "Top",
      labelStyle: "",
      inputType: "TEXT",
      isDisabled: false,
      key: "u1lqu77ftt",
      labelTextSize: "0.875rem",
      isRequired: false,
      isDeprecated: false,
      rightColumn: 56,
      widgetId: "0jneiqpr4z",
      accentColor: "{{appsmith.theme.colors.primaryColor}}",
      isVisible: true,
      label: "Label",
      version: 2,
      parentId: "y57vj73onh",
      labelAlignment: "left",
      renderMode: "CANVAS",
      isLoading: false,
      borderRadius: "{{appsmith.theme.borderRadius.appBorderRadius}}",
      iconAlign: "left",
      defaultText: "test",
    },
  } as unknown as Record<string, FlattenedWidgetProps>,
};

export const nestedListInput = {
  containerParentId: "2qrmrz0b86",
  mainContainerId: "lneohookgm",
  mainContainerCanvasId: "qpgtpiw3cu",
  templateWidgets: {
    "2qrmrz0b86": {
      boxShadow: "none",
      widgetName: "Canvas1",
      displayName: "Canvas",
      topRow: 0,
      bottomRow: 510,
      parentRowSpace: 1,
      type: "CANVAS_WIDGET",
      canExtend: false,
      hideCard: true,
      dropDisabled: true,
      openParentPropertyPane: true,
      minHeight: 400,
      noPad: true,
      parentColumnSpace: 1,
      leftColumn: 0,
      dynamicBindingPathList: [
        {
          key: "borderRadius",
        },
        {
          key: "accentColor",
        },
      ],
      children: ["lneohookgm"],
      key: "owl49rakiv",
      isDeprecated: false,
      rightColumn: 1021.5,
      detachFromLayout: true,
      widgetId: "2qrmrz0b86",
      accentColor: "{{appsmith.theme.colors.primaryColor}}",
      containerStyle: "none",
      isVisible: true,
      version: 1,
      parentId: "nlzfim1gdf",
      renderMode: "CANVAS",
      isLoading: false,
      borderRadius: "{{appsmith.theme.borderRadius.appBorderRadius}}",
    },
    lneohookgm: {
      boxShadow: "{{appsmith.theme.boxShadow.appBoxShadow}}",
      widgetName: "Container1",
      borderColor: "#E0DEDE",
      disallowCopy: true,
      isCanvas: true,
      displayName: "Container",
      iconSVG: "/static/media/icon.1977dca3370505e2db3a8e44cfd54907.svg",
      searchTags: ["div", "parent", "group"],
      topRow: 0,
      bottomRow: 49,
      dragDisabled: true,
      type: "CONTAINER_WIDGET",
      hideCard: false,
      isDeletable: false,
      animateLoading: true,
      leftColumn: 0,
      dynamicBindingPathList: [
        {
          key: "borderRadius",
        },
        {
          key: "boxShadow",
        },
      ],
      children: ["qpgtpiw3cu"],
      borderWidth: "1",
      key: "wkbtyhw919",
      backgroundColor: "white",
      isDeprecated: false,
      rightColumn: 64,
      widgetId: "lneohookgm",
      containerStyle: "card",
      isVisible: true,
      version: 1,
      parentId: "2qrmrz0b86",
      renderMode: "CANVAS",
      isLoading: false,
      borderRadius: "{{appsmith.theme.borderRadius.appBorderRadius}}",
    },
    qpgtpiw3cu: {
      boxShadow: "none",
      widgetName: "Canvas2",
      displayName: "Canvas",
      topRow: 0,
      parentRowSpace: 1,
      type: "CANVAS_WIDGET",
      canExtend: false,
      hideCard: true,
      parentColumnSpace: 1,
      leftColumn: 0,
      dynamicBindingPathList: [
        {
          key: "borderRadius",
        },
        {
          key: "accentColor",
        },
      ],
      children: ["623fj7t7ld", "9qcijo7ri3", "25x15bnona", "fs2d2lqjgd"],
      key: "owl49rakiv",
      isDeprecated: false,
      detachFromLayout: true,
      widgetId: "qpgtpiw3cu",
      accentColor: "{{appsmith.theme.colors.primaryColor}}",
      containerStyle: "none",
      isVisible: true,
      version: 1,
      parentId: "lneohookgm",
      renderMode: "CANVAS",
      isLoading: false,
      borderRadius: "{{appsmith.theme.borderRadius.appBorderRadius}}",
    },
    "623fj7t7ld": {
      boxShadow: "none",
      widgetName: "Image1",
      displayName: "Image",
      iconSVG: "/static/media/icon.52d8fb963abcb95c79b10f1553389f22.svg",
      topRow: 0,
      bottomRow: 8,
      type: "IMAGE_WIDGET",
      hideCard: false,
      animateLoading: true,
      dynamicTriggerPathList: [],
      imageShape: "RECTANGLE",
      dynamicBindingPathList: [
        {
          key: "image",
        },
        {
          key: "borderRadius",
        },
      ],
      leftColumn: 0,
      defaultImage: getAssetUrl(`${ASSETS_CDN_URL}/widgets/default.png`),
      key: "2g7ntchr1f",
      image: "{{currentItem.img}}",
      isDeprecated: false,
      rightColumn: 16,
      objectFit: "cover",
      widgetId: "623fj7t7ld",
      isVisible: true,
      version: 1,
      parentId: "qpgtpiw3cu",
      renderMode: "CANVAS",
      isLoading: false,
      maxZoomLevel: 1,
      enableDownload: false,
      borderRadius: "{{appsmith.theme.borderRadius.appBorderRadius}}",
      enableRotation: false,
    },
    "9qcijo7ri3": {
      boxShadow: "none",
      widgetName: "Text1",
      displayName: "Text",
      iconSVG: "/static/media/icon.97c59b523e6f70ba6f40a10fc2c7c5b5.svg",
      searchTags: ["typography", "paragraph", "label"],
      topRow: 0,
      bottomRow: 4,
      type: "TEXT_WIDGET",
      hideCard: false,
      animateLoading: true,
      overflow: "NONE",
      dynamicTriggerPathList: [],
      fontFamily: "{{appsmith.theme.fontFamily.appFont}}",
      dynamicBindingPathList: [
        {
          key: "text",
        },
        {
          key: "truncateButtonColor",
        },
        {
          key: "fontFamily",
        },
        {
          key: "borderRadius",
        },
      ],
      leftColumn: 16,
      shouldTruncate: false,
      truncateButtonColor: "{{appsmith.theme.colors.primaryColor}}",
      text: "{{currentItem.name}}",
      key: "g9hodrowsi",
      isDeprecated: false,
      rightColumn: 28,
      textAlign: "LEFT",
      widgetId: "9qcijo7ri3",
      isVisible: true,
      fontStyle: "BOLD",
      textColor: "#231F20",
      version: 1,
      parentId: "qpgtpiw3cu",
      renderMode: "CANVAS",
      isLoading: false,
      borderRadius: "{{appsmith.theme.borderRadius.appBorderRadius}}",
      fontSize: "1rem",
      textStyle: "HEADING",
    },
    "25x15bnona": {
      boxShadow: "none",
      widgetName: "Text2",
      displayName: "Text",
      iconSVG: "/static/media/icon.97c59b523e6f70ba6f40a10fc2c7c5b5.svg",
      searchTags: ["typography", "paragraph", "label"],
      topRow: 4,
      bottomRow: 8,
      type: "TEXT_WIDGET",
      hideCard: false,
      animateLoading: true,
      overflow: "NONE",
      dynamicTriggerPathList: [],
      fontFamily: "{{appsmith.theme.fontFamily.appFont}}",
      dynamicBindingPathList: [
        {
          key: "text",
        },
        {
          key: "truncateButtonColor",
        },
        {
          key: "fontFamily",
        },
        {
          key: "borderRadius",
        },
      ],
      leftColumn: 16,
      shouldTruncate: false,
      truncateButtonColor: "{{appsmith.theme.colors.primaryColor}}",
      text: "{{currentItem.id}}",
      key: "g9hodrowsi",
      isDeprecated: false,
      rightColumn: 24,
      textAlign: "LEFT",
      widgetId: "25x15bnona",
      isVisible: true,
      fontStyle: "BOLD",
      textColor: "#231F20",
      version: 1,
      parentId: "qpgtpiw3cu",
      renderMode: "CANVAS",
      isLoading: false,
      borderRadius: "{{appsmith.theme.borderRadius.appBorderRadius}}",
      fontSize: "1rem",
      textStyle: "BODY",
    },
    fs2d2lqjgd: {
      isVisible: true,
      backgroundColor: "transparent",
      itemBackgroundColor: "#FFFFFF",
      requiresFlatWidgetChildren: true,
      hasMetaWidgets: true,
      animateLoading: true,
      gridType: "vertical",
      dynamicBindingPathList: [
        {
          key: "currentItemsView",
        },
        {
          key: "selectedItemView",
        },
        {
          key: "triggeredItemView",
        },
        {
          key: "primaryKeys",
        },
        {
          key: "borderRadius",
        },
        {
          key: "accentColor",
        },
      ],
      currentItemsView: "{{[]}}",
      selectedItemView: "{{{}}}",
      triggeredItemView: "{{{}}}",
      enhancements: true,
      itemSpacing: 8,
      templateBottomRow: 16,
      listData: [
        {
          id: "001",
          name: "Blue",
          img: getAssetUrl(`${ASSETS_CDN_URL}/widgets/default.png`),
        },
        {
          id: "002",
          name: "Green",
          img: getAssetUrl(`${ASSETS_CDN_URL}/widgets/default.png`),
        },
        {
          id: "003",
          name: "Red",
          img: getAssetUrl(`${ASSETS_CDN_URL}/widgets/default.png`),
        },
      ],
      pageSize: 3,
      widgetName: "List6",
      children: ["sel6fxh5fy"],
      primaryKeys:
        '{{List6.listData.map((currentItem, currentIndex) => currentItem["id"] )}}',
      type: "LIST_WIDGET_V2",
      hideCard: false,
      isDeprecated: false,
      displayName: "List V2",
      key: "fq71tyxnm1",
      iconSVG: "/static/media/icon.9925ee17dee37bf1ba7374412563a8a7.svg",
      isCanvas: true,
      widgetId: "fs2d2lqjgd",
      renderMode: "CANVAS",
      boxShadow: "none",
      borderRadius: "{{appsmith.theme.borderRadius.appBorderRadius}}",
      accentColor: "{{appsmith.theme.colors.primaryColor}}",
      isLoading: false,
      parentColumnSpace: 15.5234375,
      parentRowSpace: 10,
      leftColumn: 32,
      rightColumn: 56,
      topRow: 2,
      bottomRow: 42,
      parentId: "qpgtpiw3cu",
      mainContainerId: "naphqxj9hz",
      mainCanvasId: "sel6fxh5fy",
      dynamicTriggerPathList: [],
    },
    sel6fxh5fy: {
      isVisible: true,
      widgetName: "Canvas3",
      version: 1,
      detachFromLayout: true,
      type: "CANVAS_WIDGET",
      hideCard: true,
      isDeprecated: false,
      displayName: "Canvas",
      key: "owl49rakiv",
      containerStyle: "none",
      canExtend: false,
      dropDisabled: true,
      openParentPropertyPane: true,
      noPad: true,
      children: ["naphqxj9hz"],
      minHeight: 400,
      widgetId: "sel6fxh5fy",
      renderMode: "CANVAS",
      boxShadow: "none",
      borderRadius: "{{appsmith.theme.borderRadius.appBorderRadius}}",
      accentColor: "{{appsmith.theme.colors.primaryColor}}",
      isLoading: false,
      parentColumnSpace: 1,
      parentRowSpace: 1,
      leftColumn: 0,
      rightColumn: 372.5625,
      topRow: 0,
      bottomRow: 400,
      parentId: "fs2d2lqjgd",
      dynamicBindingPathList: [
        {
          key: "borderRadius",
        },
        {
          key: "accentColor",
        },
      ],
    },
    naphqxj9hz: {
      isVisible: true,
      backgroundColor: "white",
      widgetName: "Container2",
      containerStyle: "card",
      borderColor: "#E0DEDE",
      borderWidth: "1",
      boxShadow: "{{appsmith.theme.boxShadow.appBoxShadow}}",
      animateLoading: true,
      children: ["qi2677bszw"],
      version: 1,
      searchTags: ["div", "parent", "group"],
      type: "CONTAINER_WIDGET",
      hideCard: false,
      isDeprecated: false,
      displayName: "Container",
      key: "wkbtyhw919",
      iconSVG: "/static/media/icon.1977dca3370505e2db3a8e44cfd54907.svg",
      isCanvas: true,
      dragDisabled: true,
      isDeletable: false,
      disallowCopy: true,
      widgetId: "naphqxj9hz",
      renderMode: "CANVAS",
      borderRadius: "{{appsmith.theme.borderRadius.appBorderRadius}}",
      isLoading: false,
      leftColumn: 0,
      rightColumn: 64,
      topRow: 0,
      bottomRow: 12,
      parentId: "sel6fxh5fy",
      dynamicBindingPathList: [
        {
          key: "borderRadius",
        },
        {
          key: "boxShadow",
        },
      ],
    },
    qi2677bszw: {
      isVisible: true,
      widgetName: "Canvas4",
      version: 1,
      detachFromLayout: true,
      type: "CANVAS_WIDGET",
      hideCard: true,
      isDeprecated: false,
      displayName: "Canvas",
      key: "owl49rakiv",
      containerStyle: "none",
      canExtend: false,
      children: ["xyt7kd0vsa", "dkk5yh9urt", "q8e2zhxsdb"],
      minHeight: null,
      widgetId: "qi2677bszw",
      renderMode: "CANVAS",
      boxShadow: "none",
      borderRadius: "{{appsmith.theme.borderRadius.appBorderRadius}}",
      accentColor: "{{appsmith.theme.colors.primaryColor}}",
      isLoading: false,
      parentColumnSpace: 1,
      parentRowSpace: 1,
      leftColumn: 0,
      rightColumn: null,
      topRow: 0,
      bottomRow: null,
      parentId: "naphqxj9hz",
      dynamicBindingPathList: [
        {
          key: "borderRadius",
        },
        {
          key: "accentColor",
        },
      ],
    },
    xyt7kd0vsa: {
      isVisible: true,
      defaultImage: getAssetUrl(`${ASSETS_CDN_URL}/widgets/default.png`),
      imageShape: "RECTANGLE",
      maxZoomLevel: 1,
      enableRotation: false,
      enableDownload: false,
      objectFit: "cover",
      image: "{{currentItem.img}}",
      widgetName: "Image2",
      version: 1,
      animateLoading: true,
      type: "IMAGE_WIDGET",
      hideCard: false,
      isDeprecated: false,
      displayName: "Image",
      key: "2g7ntchr1f",
      iconSVG: "/static/media/icon.52d8fb963abcb95c79b10f1553389f22.svg",
      boxShadow: "none",
      dynamicBindingPathList: [
        {
          key: "image",
        },
        {
          key: "borderRadius",
        },
      ],
      dynamicTriggerPathList: [],
      widgetId: "xyt7kd0vsa",
      renderMode: "CANVAS",
      borderRadius: "{{appsmith.theme.borderRadius.appBorderRadius}}",
      isLoading: false,
      leftColumn: 0,
      rightColumn: 16,
      topRow: 0,
      bottomRow: 8,
      parentId: "qi2677bszw",
    },
    dkk5yh9urt: {
      isVisible: true,
      text: "{{currentItem.name}}",
      fontSize: "1rem",
      fontStyle: "BOLD",
      textAlign: "LEFT",
      textColor: "#231F20",
      widgetName: "Text4",
      shouldTruncate: false,
      overflow: "NONE",
      version: 1,
      animateLoading: true,
      searchTags: ["typography", "paragraph", "label"],
      type: "TEXT_WIDGET",
      hideCard: false,
      isDeprecated: false,
      displayName: "Text",
      key: "g9hodrowsi",
      iconSVG: "/static/media/icon.97c59b523e6f70ba6f40a10fc2c7c5b5.svg",
      textStyle: "HEADING",
      boxShadow: "none",
      dynamicBindingPathList: [
        {
          key: "text",
        },
        {
          key: "truncateButtonColor",
        },
        {
          key: "fontFamily",
        },
        {
          key: "borderRadius",
        },
      ],
      dynamicTriggerPathList: [],
      widgetId: "dkk5yh9urt",
      renderMode: "CANVAS",
      truncateButtonColor: "{{appsmith.theme.colors.primaryColor}}",
      fontFamily: "{{appsmith.theme.fontFamily.appFont}}",
      borderRadius: "{{appsmith.theme.borderRadius.appBorderRadius}}",
      isLoading: false,
      leftColumn: 16,
      rightColumn: 28,
      topRow: 0,
      bottomRow: 4,
      parentId: "qi2677bszw",
    },
    q8e2zhxsdb: {
      isVisible: true,
      text: '{{level_1.currentItem.id + " " + level_1.currentIndex +" " + level_1.currentView.Text1.text + " " + currentIndex + currentItem.name + currentView.Text4.text}}',
      fontSize: "1rem",
      fontStyle: "BOLD",
      textAlign: "LEFT",
      textColor: "#231F20",
      widgetName: "Text5",
      shouldTruncate: false,
      overflow: "NONE",
      version: 1,
      animateLoading: true,
      searchTags: ["typography", "paragraph", "label"],
      type: "TEXT_WIDGET",
      hideCard: false,
      isDeprecated: false,
      displayName: "Text",
      key: "g9hodrowsi",
      iconSVG: "/static/media/icon.97c59b523e6f70ba6f40a10fc2c7c5b5.svg",
      textStyle: "BODY",
      boxShadow: "none",
      dynamicBindingPathList: [
        {
          key: "text",
        },
        {
          key: "truncateButtonColor",
        },
        {
          key: "fontFamily",
        },
        {
          key: "borderRadius",
        },
      ],
      dynamicTriggerPathList: [],
      widgetId: "q8e2zhxsdb",
      renderMode: "CANVAS",
      truncateButtonColor: "{{appsmith.theme.colors.primaryColor}}",
      fontFamily: "{{appsmith.theme.fontFamily.appFont}}",
      borderRadius: "{{appsmith.theme.borderRadius.appBorderRadius}}",
      isLoading: false,
      leftColumn: 16,
      rightColumn: 24,
      topRow: 4,
      bottomRow: 8,
      parentId: "qi2677bszw",
    },
  } as unknown as Record<string, FlattenedWidgetProps>,
};
