export const unitTestBaseMockStore = {
  entities: {
    pageList: {
      pages: [
        {
          pageName: "Page1",
          pageId: "659d2e15d0cbfb0c5e0a742b",
          isDefault: true,
          isHidden: false,
          slug: "page1",
          userPermissions: [
            "read:pages",
            "manage:pages",
            "create:pageActions",
            "delete:pages",
          ],
        },
      ],
      isGeneratingTemplatePage: false,
      applicationId: "659d2e15d0cbfb0c5e0a7428",
      currentPageId: "659d2e15d0cbfb0c5e0a742b",
      defaultPageId: "659d2e15d0cbfb0c5e0a742b",
      loading: {},
    },
    app: {
      user: {
        email: "jacques@adasdsad.com",
        username: "jacques@adasdsad.com",
        useCase: "personal project",
        enableTelemetry: true,
        roles: [
          "Upgrade to business edition to access roles and groups for conditional business logic",
        ],
        groups: [
          "Upgrade to business edition to access roles and groups for conditional business logic",
        ],
        emptyInstance: false,
        accountNonExpired: true,
        accountNonLocked: true,
        credentialsNonExpired: true,
        isAnonymous: false,
        isEnabled: true,
        isSuperUser: false,
        isConfigurable: true,
        adminSettingsVisible: false,
        isIntercomConsentGiven: false,
      },
      URL: {
        fullPath:
          "https://dev.appsmith.com/app/my-first-application/page1-659d2e15d0cbfb0c5e0a742b/edit",
        host: "dev.appsmith.com",
        hostname: "dev.appsmith.com",
        queryParams: {},
        protocol: "https:",
        pathname:
          "/app/my-first-application/page1-659d2e15d0cbfb0c5e0a742b/edit",
        port: "",
        hash: "",
      },
      store: {},
      geolocation: {
        canBeRequested: true,
        currentPosition: {},
      },
      mode: "EDIT",
    },
    plugins: {
      list: [],
      defaultPluginList: [
        {
          id: "5ca385dc81b37f0004b4db85",
          userPermissions: [],
          name: "REST API",
          packageName: "restapi-plugin",
          iconLocation: "https://assets.appsmith.com/RestAPI.png",
          allowUserDatasources: true,
          isRemotePlugin: false,
          requiresDatasource: true,
          remotePlugin: false,
          new: false,
        },
        {
          id: "5e8dad9bf062d5125ddfd836",
          userPermissions: [],
          name: "PostgreSQL",
          packageName: "postgres-plugin",
          iconLocation: "https://assets.appsmith.com/logo/postgresql.svg",
          allowUserDatasources: true,
          isRemotePlugin: false,
          requiresDatasource: true,
          remotePlugin: false,
          new: false,
        },
        {
          id: "5ec3bccdd4b5eaa50ba6f583",
          userPermissions: [],
          name: "MongoDB",
          packageName: "mongo-plugin",
          iconLocation: "https://assets.appsmith.com/logo/mongodb.svg",
          allowUserDatasources: true,
          isRemotePlugin: false,
          requiresDatasource: true,
          remotePlugin: false,
          new: false,
        },
        {
          id: "5f192a44a2d05225d010db9d",
          userPermissions: [],
          name: "MySQL",
          packageName: "mysql-plugin",
          iconLocation: "https://assets.appsmith.com/logo/mysql.svg",
          allowUserDatasources: true,
          isRemotePlugin: false,
          requiresDatasource: true,
          remotePlugin: false,
          new: false,
        },
        {
          id: "5f92f9e9107018510ae540be",
          userPermissions: [],
          name: "Elasticsearch",
          packageName: "elasticsearch-plugin",
          iconLocation: "https://assets.appsmith.com/logo/elastic.svg",
          allowUserDatasources: true,
          isRemotePlugin: false,
          requiresDatasource: true,
          remotePlugin: false,
          new: false,
        },
        {
          id: "5f92f9ec107018510ae540c0",
          userPermissions: [],
          name: "DynamoDB",
          packageName: "dynamo-plugin",
          iconLocation: "https://assets.appsmith.com/logo/aws-dynamodb.svg",
          allowUserDatasources: true,
          isRemotePlugin: false,
          requiresDatasource: true,
          remotePlugin: false,
          new: false,
        },
        {
          id: "5f92f9ef107018510ae540c3",
          userPermissions: [],
          name: "Redis",
          packageName: "redis-plugin",
          iconLocation: "https://assets.appsmith.com/logo/redis.svg",
          allowUserDatasources: true,
          isRemotePlugin: false,
          requiresDatasource: true,
          remotePlugin: false,
          new: false,
        },
        {
          id: "5f92f9f1107018510ae540c5",
          userPermissions: [],
          name: "Microsoft SQL Server",
          packageName: "mssql-plugin",
          iconLocation: "https://assets.appsmith.com/logo/mssql.svg",
          allowUserDatasources: true,
          isRemotePlugin: false,
          requiresDatasource: true,
          remotePlugin: false,
          new: false,
        },
        {
          id: "5fbcc1c758377818ddaec444",
          userPermissions: [],
          name: "Firestore",
          packageName: "firestore-plugin",
          iconLocation: "https://assets.appsmith.com/logo/firestore.svg",
          allowUserDatasources: true,
          isRemotePlugin: false,
          requiresDatasource: true,
          remotePlugin: false,
          new: false,
        },
        {
          id: "60081f50ffab735a9dae84e7",
          userPermissions: [],
          name: "Redshift",
          packageName: "redshift-plugin",
          iconLocation: "https://assets.appsmith.com/logo/aws-redshift.svg",
          allowUserDatasources: true,
          isRemotePlugin: false,
          requiresDatasource: true,
          remotePlugin: false,
          new: false,
        },
        {
          id: "60374b7d074f9b49cd68a036",
          userPermissions: [],
          name: "S3",
          packageName: "amazons3-plugin",
          iconLocation: "https://assets.appsmith.com/logo/aws-s3.svg",
          allowUserDatasources: true,
          isRemotePlugin: false,
          requiresDatasource: true,
          remotePlugin: false,
          new: false,
        },
        {
          id: "60910df653a4d211ac7dd678",
          userPermissions: [],
          name: "Google Sheets",
          packageName: "google-sheets-plugin",
          iconLocation: "https://assets.appsmith.com/GoogleSheets.svg",
          allowUserDatasources: true,
          isRemotePlugin: false,
          requiresDatasource: true,
          remotePlugin: false,
          new: false,
        },
        {
          id: "60d1c008c238633f08e5f5c4",
          userPermissions: [],
          name: "Snowflake",
          packageName: "snowflake-plugin",
          iconLocation: "https://assets.appsmith.com/logo/snowflake.svg",
          allowUserDatasources: true,
          isRemotePlugin: false,
          requiresDatasource: true,
          remotePlugin: false,
          new: false,
        },
        {
          id: "60f183893106c14e45586d98",
          userPermissions: [],
          name: "ArangoDB",
          packageName: "arangodb-plugin",
          iconLocation: "https://assets.appsmith.com/logo/arangodb.svg",
          allowUserDatasources: true,
          isRemotePlugin: false,
          requiresDatasource: true,
          remotePlugin: false,
          new: false,
        },
        {
          id: "613a26d921750e4b557a9241",
          userPermissions: [],
          name: "JS Functions",
          packageName: "js-plugin",
          iconLocation: "https://assets.appsmith.com/js-yellow.svg",
          allowUserDatasources: true,
          isRemotePlugin: false,
          requiresDatasource: true,
          remotePlugin: false,
          new: false,
        },
        {
          id: "61b87870869bd22f1428db09",
          userPermissions: [],
          name: "SMTP",
          packageName: "smtp-plugin",
          iconLocation: "https://assets.appsmith.com/smtp-icon.svg",
          allowUserDatasources: true,
          isRemotePlugin: false,
          requiresDatasource: true,
          remotePlugin: false,
          new: false,
        },
        {
          id: "61dbfd4b6bd5757f166ccc76",
          userPermissions: [],
          name: "Airtable",
          packageName: "saas-plugin",
          iconLocation: "https://assets.appsmith.com/integrations/airtable.svg",
          allowUserDatasources: true,
          isRemotePlugin: false,
          requiresDatasource: true,
          remotePlugin: false,
          new: false,
        },
        {
          id: "627938600b47255c280c19da",
          userPermissions: [],
          name: "Twilio",
          packageName: "saas-plugin",
          iconLocation: "https://assets.appsmith.com/integrations/twilio1.png",
          allowUserDatasources: true,
          isRemotePlugin: false,
          requiresDatasource: true,
          remotePlugin: false,
          new: false,
        },
        {
          id: "6287c0e37901344ba8d12776",
          userPermissions: [],
          name: "HubSpot",
          packageName: "saas-plugin",
          iconLocation: "https://assets.appsmith.com/integrations/hubspot.png",
          allowUserDatasources: true,
          isRemotePlugin: false,
          requiresDatasource: true,
          remotePlugin: false,
          new: false,
        },
        {
          id: "6320bc011da87f61107aa9e0",
          userPermissions: [],
          name: "Authenticated GraphQL API",
          packageName: "graphql-plugin",
          iconLocation:
            "https://s3.us-east-2.amazonaws.com/assets.appsmith.com/logo/graphql.svg",
          allowUserDatasources: true,
          isRemotePlugin: false,
          requiresDatasource: true,
          remotePlugin: false,
          new: false,
        },
        {
          id: "642a4177c5ccee14a368f798",
          userPermissions: [],
          name: "Oracle",
          packageName: "oracle-plugin",
          iconLocation:
            "https://s3.us-east-2.amazonaws.com/assets.appsmith.com/oracle.svg",
          allowUserDatasources: true,
          isRemotePlugin: false,
          requiresDatasource: true,
          remotePlugin: false,
          new: false,
        },
        {
          id: "6554bcb66ed461189b1cf6fb",
          userPermissions: [],
          name: "Open AI",
          packageName: "openai-plugin",
          iconLocation: "https://assets.appsmith.com/logo/open-ai.svg",
          allowUserDatasources: true,
          isRemotePlugin: false,
          requiresDatasource: true,
          remotePlugin: false,
          new: false,
        },
        {
          id: "6572b13e7f7dd327b43df7fb",
          userPermissions: [],
          name: "Anthropic",
          packageName: "anthropic-plugin",
          iconLocation: "https://assets.appsmith.com/logo/anthropic.svg",
          allowUserDatasources: true,
          isRemotePlugin: false,
          requiresDatasource: true,
          remotePlugin: false,
          new: false,
        },
        {
          id: "657c1629c8356e4ca12cc9de",
          userPermissions: [],
          name: "Google AI",
          packageName: "googleai-plugin",
          iconLocation: "https://assets.appsmith.com/google-ai.svg",
          allowUserDatasources: true,
          isRemotePlugin: false,
          requiresDatasource: true,
          remotePlugin: false,
          new: false,
        },
        {
          id: "658aa4705f082e415f8a15c7",
          userPermissions: [],
          name: "Databricks",
          packageName: "databricks-plugin",
          iconLocation: "https://assets.appsmith.com/databricks-logo.svg",
          allowUserDatasources: true,
          isRemotePlugin: false,
          requiresDatasource: true,
          remotePlugin: false,
          new: false,
        },
        {
          id: "658aa47d5f082e415f8a15c8",
          userPermissions: [],
          name: "AWS Lambda",
          packageName: "aws-lambda-plugin",
          iconLocation: "https://assets.appsmith.com/aws-lambda-logo.svg",
          allowUserDatasources: true,
          isRemotePlugin: false,
          requiresDatasource: true,
          remotePlugin: false,
          new: false,
        },
        {
          id: "65a8a29571f08f72be5011e9",
          userPermissions: [],
          name: "Appsmith AI",
          packageName: "appsmithai-plugin",
          iconLocation: "https://assets.appsmith.com/logo/appsmith-ai.svg",
          allowUserDatasources: true,
          isRemotePlugin: false,
          requiresDatasource: true,
          remotePlugin: false,
          new: false,
        },
        {
          id: "65a8a2a271f08f72be5011ea",
          userPermissions: [],
          name: "Workflow",
          packageName: "workflow-plugin",
          iconLocation: "https://assets.appsmith.com/workflows.svg",
          allowUserDatasources: true,
          isRemotePlugin: false,
          requiresDatasource: true,
          remotePlugin: false,
          new: false,
        },
      ],
      loading: false,
      formConfigs: {},
      editorConfigs: {},
      settingConfigs: {},
      datasourceFormButtonConfigs: {},
      dependencies: {},
      fetchingSinglePluginForm: {},
      fetchingDefaultPlugins: false,
    },
  },
  ui: {
    workspaces: {
      currentWorkspace: {
        id: "659d2e14d0cbfb0c5e0a7424",
        userPermissions: [
          "publish:workspaceApplications",
          "delete:workspace",
          "manage:workspaceApplications",
          "delete:workspaceDatasources",
          "export:workspaceApplications",
          "read:workspaceDatasources",
          "read:workspaceApplications",
          "inviteUsers:workspace",
          "read:workspaces",
          "manage:workspaceDatasources",
          "create:datasources",
          "delete:workspaceApplications",
          "create:applications",
          "manage:workspaces",
        ],
        name: "jacques's apps",
        email: "jacques@adasdsad.com",
        plugins: [
          {
            userPermissions: [],
            pluginId: "653236215e9a6424e4c04b5c",
            status: "FREE",
            new: true,
          },
          {
            userPermissions: [],
            pluginId: "653236215e9a6424e4c04b5b",
            status: "FREE",
            new: true,
          },
          {
            userPermissions: [],
            pluginId: "653236225e9a6424e4c04b75",
            status: "FREE",
            new: true,
          },
          {
            userPermissions: [],
            pluginId: "653236215e9a6424e4c04b5a",
            status: "FREE",
            new: true,
          },
          {
            userPermissions: [],
            pluginId: "6572a3933efa034a885f73bf",
            status: "FREE",
            new: true,
          },
          {
            userPermissions: [],
            pluginId: "653236215e9a6424e4c04b59",
            status: "FREE",
            new: true,
          },
          {
            userPermissions: [],
            pluginId: "653236215e9a6424e4c04b64",
            status: "FREE",
            new: true,
          },
          {
            userPermissions: [],
            pluginId: "653236215e9a6424e4c04b63",
            status: "FREE",
            new: true,
          },
          {
            userPermissions: [],
            pluginId: "653236215e9a6424e4c04b62",
            status: "FREE",
            new: true,
          },
          {
            userPermissions: [],
            pluginId: "653236225e9a6424e4c04b74",
            status: "FREE",
            new: true,
          },
          {
            userPermissions: [],
            pluginId: "653236215e9a6424e4c04b58",
            status: "FREE",
            new: true,
          },
          {
            userPermissions: [],
            pluginId: "653236205e9a6424e4c04b51",
            status: "FREE",
            new: true,
          },
          {
            userPermissions: [],
            pluginId: "6597efc7d0cbfb0c5e0a73cc",
            status: "FREE",
            new: true,
          },
          {
            userPermissions: [],
            pluginId: "654a489144e16d2e57f05d60",
            status: "FREE",
            new: true,
          },
          {
            userPermissions: [],
            pluginId: "653236215e9a6424e4c04b61",
            status: "FREE",
            new: true,
          },
          {
            userPermissions: [],
            pluginId: "6597efc7d0cbfb0c5e0a73ce",
            status: "FREE",
            new: true,
          },
          {
            userPermissions: [],
            pluginId: "653236215e9a6424e4c04b55",
            status: "FREE",
            new: true,
          },
          {
            userPermissions: [],
            pluginId: "653236205e9a6424e4c04b52",
            status: "FREE",
            new: true,
          },
          {
            userPermissions: [],
            pluginId: "653236465e9a6424e4c04b77",
            status: "FREE",
            new: true,
          },
          {
            userPermissions: [],
            pluginId: "6597efc7d0cbfb0c5e0a73cd",
            status: "FREE",
            new: true,
          },
          {
            userPermissions: [],
            pluginId: "653236205e9a6424e4c04b53",
            status: "FREE",
            new: true,
          },
          {
            userPermissions: [],
            pluginId: "653236465e9a6424e4c04b78",
            status: "FREE",
            new: true,
          },
          {
            userPermissions: [],
            pluginId: "653236215e9a6424e4c04b5f",
            status: "FREE",
            new: true,
          },
          {
            userPermissions: [],
            pluginId: "653236465e9a6424e4c04b79",
            status: "FREE",
            new: true,
          },
          {
            userPermissions: [],
            pluginId: "653236215e9a6424e4c04b5e",
            status: "FREE",
            new: true,
          },
          {
            userPermissions: [],
            pluginId: "653236215e9a6424e4c04b5d",
            status: "FREE",
            new: true,
          },
        ],
        slug: "jacques-s-apps",
        isAutoGeneratedWorkspace: true,
        tenantId: "653236225e9a6424e4c04b65",
        logoUrl: "/api/v1/assets/null",
        new: false,
      },
      list: [],
    },
    selectedWorkspace: {
      workspace: {
        id: "659d2e14d0cbfb0c5e0a7424",
        userPermissions: [
          "publish:workspaceApplications",
          "delete:workspace",
          "manage:workspaceApplications",
          "delete:workspaceDatasources",
          "export:workspaceApplications",
          "read:workspaceDatasources",
          "read:workspaceApplications",
          "inviteUsers:workspace",
          "read:workspaces",
          "manage:workspaceDatasources",
          "create:datasources",
          "delete:workspaceApplications",
          "create:applications",
          "manage:workspaces",
        ],
        name: "jacques's apps",
        email: "jacques@adasdsad.com",
        plugins: [
          {
            userPermissions: [],
            pluginId: "653236215e9a6424e4c04b5c",
            status: "FREE",
            new: true,
          },
          {
            userPermissions: [],
            pluginId: "653236215e9a6424e4c04b5b",
            status: "FREE",
            new: true,
          },
          {
            userPermissions: [],
            pluginId: "653236225e9a6424e4c04b75",
            status: "FREE",
            new: true,
          },
          {
            userPermissions: [],
            pluginId: "653236215e9a6424e4c04b5a",
            status: "FREE",
            new: true,
          },
          {
            userPermissions: [],
            pluginId: "6572a3933efa034a885f73bf",
            status: "FREE",
            new: true,
          },
          {
            userPermissions: [],
            pluginId: "653236215e9a6424e4c04b59",
            status: "FREE",
            new: true,
          },
          {
            userPermissions: [],
            pluginId: "653236215e9a6424e4c04b64",
            status: "FREE",
            new: true,
          },
          {
            userPermissions: [],
            pluginId: "653236215e9a6424e4c04b63",
            status: "FREE",
            new: true,
          },
          {
            userPermissions: [],
            pluginId: "653236215e9a6424e4c04b62",
            status: "FREE",
            new: true,
          },
          {
            userPermissions: [],
            pluginId: "653236225e9a6424e4c04b74",
            status: "FREE",
            new: true,
          },
          {
            userPermissions: [],
            pluginId: "653236215e9a6424e4c04b58",
            status: "FREE",
            new: true,
          },
          {
            userPermissions: [],
            pluginId: "653236205e9a6424e4c04b51",
            status: "FREE",
            new: true,
          },
          {
            userPermissions: [],
            pluginId: "6597efc7d0cbfb0c5e0a73cc",
            status: "FREE",
            new: true,
          },
          {
            userPermissions: [],
            pluginId: "654a489144e16d2e57f05d60",
            status: "FREE",
            new: true,
          },
          {
            userPermissions: [],
            pluginId: "653236215e9a6424e4c04b61",
            status: "FREE",
            new: true,
          },
          {
            userPermissions: [],
            pluginId: "6597efc7d0cbfb0c5e0a73ce",
            status: "FREE",
            new: true,
          },
          {
            userPermissions: [],
            pluginId: "653236215e9a6424e4c04b55",
            status: "FREE",
            new: true,
          },
          {
            userPermissions: [],
            pluginId: "653236205e9a6424e4c04b52",
            status: "FREE",
            new: true,
          },
          {
            userPermissions: [],
            pluginId: "653236465e9a6424e4c04b77",
            status: "FREE",
            new: true,
          },
          {
            userPermissions: [],
            pluginId: "6597efc7d0cbfb0c5e0a73cd",
            status: "FREE",
            new: true,
          },
          {
            userPermissions: [],
            pluginId: "653236205e9a6424e4c04b53",
            status: "FREE",
            new: true,
          },
          {
            userPermissions: [],
            pluginId: "653236465e9a6424e4c04b78",
            status: "FREE",
            new: true,
          },
          {
            userPermissions: [],
            pluginId: "653236215e9a6424e4c04b5f",
            status: "FREE",
            new: true,
          },
          {
            userPermissions: [],
            pluginId: "653236465e9a6424e4c04b79",
            status: "FREE",
            new: true,
          },
          {
            userPermissions: [],
            pluginId: "653236215e9a6424e4c04b5e",
            status: "FREE",
            new: true,
          },
          {
            userPermissions: [],
            pluginId: "653236215e9a6424e4c04b5d",
            status: "FREE",
            new: true,
          },
        ],
        slug: "jacques-s-apps",
        isAutoGeneratedWorkspace: true,
        tenantId: "653236225e9a6424e4c04b65",
        logoUrl: "/api/v1/assets/null",
        new: false,
      },
    },
    applications: {
      currentApplication: {
        applicationDetail: {
          navigationSetting: {
            showNavbar: true,
            showSignIn: true,
            orientation: "top",
            navStyle: "stacked",
            position: "static",
            itemStyle: "text",
            colorStyle: "light",
            logoAssetId: "",
            logoConfiguration: "logoAndApplicationTitle",
          },
          themeSetting: {
            fontFamily: "System Default",
            accentColor: "#553DE9",
            colorMode: "LIGHT",
            borderRadius: "6px",
            density: 1,
            sizing: 1,
          },
        },
        id: "659d2e15d0cbfb0c5e0a7428",
        modifiedBy: "jacques@adasdsad.com",
        userPermissions: [
          "manage:applications",
          "canComment:applications",
          "export:applications",
          "manageProtectedBranches:applications",
          "read:applications",
          "manageDefaultBranches:applications",
          "create:pages",
          "publish:applications",
          "connectToGit:applications",
          "manageAutoCommit:applications",
          "delete:applications",
          "makePublic:applications",
        ],
        name: "My first application",
        workspaceId: "659d2e14d0cbfb0c5e0a7424",
        isPublic: false,
        appIsExample: false,
        unreadCommentThreads: 0,
        color: "#FBF4ED",
        slug: "my-first-application",
        unpublishedCustomJSLibs: [],
        publishedCustomJSLibs: [],
        evaluationVersion: 2,
        applicationVersion: 2,
        collapseInvisibleWidgets: true,
        isAutoUpdate: false,
        new: false,
        modifiedAt: "2024-01-09T11:29:25.076Z",
        pages: [
          {
            id: "659d2e15d0cbfb0c5e0a742b",
            name: "Page1",
            slug: "page1",
            isDefault: true,
            userPermissions: [
              "read:pages",
              "manage:pages",
              "create:pageActions",
              "delete:pages",
            ],
          },
        ],
      },
      isFetchingApplications: false,
    },
    templates: {
      filters: {
        functions: ["All"],
      },
      allFilters: {},
      templateSearchQuery: "",
      templates: [],
      isImportingStarterBuildingBlockToApp: false,
    },
  },
};
