export const unitTestBaseMockStore = {
  entities: {
    pageList: {
      pages: [
        {
          pageName: "Page1",
          pageId: "659d2e15d0cbfb0c5e0a742b",
          isDefault: true,
          isHidden: false,
          slug: "page1",
          userPermissions: [
            "read:pages",
            "manage:pages",
            "create:pageActions",
            "delete:pages",
          ],
        },
      ],
      isGeneratingTemplatePage: false,
      applicationId: "659d2e15d0cbfb0c5e0a7428",
      currentPageId: "659d2e15d0cbfb0c5e0a742b",
      defaultPageId: "659d2e15d0cbfb0c5e0a742b",
      loading: {},
    },
    app: {
      user: {
        email: "jacques@adasdsad.com",
        username: "jacques@adasdsad.com",
        useCase: "personal project",
        enableTelemetry: true,
        roles: [
          "Upgrade to business plan to access roles and groups for conditional business logic",
        ],
        groups: [
          "Upgrade to business plan to access roles and groups for conditional business logic",
        ],
        emptyInstance: false,
        accountNonExpired: true,
        accountNonLocked: true,
        credentialsNonExpired: true,
        isAnonymous: false,
        isEnabled: true,
        isSuperUser: false,
        isConfigurable: true,
        adminSettingsVisible: false,
        isIntercomConsentGiven: false,
      },
      URL: {
        fullPath:
          "https://dev.appsmith.com/app/my-first-application/page1-659d2e15d0cbfb0c5e0a742b/edit",
        host: "dev.appsmith.com",
        hostname: "dev.appsmith.com",
        queryParams: {},
        protocol: "https:",
        pathname:
          "/app/my-first-application/page1-659d2e15d0cbfb0c5e0a742b/edit",
        port: "",
        hash: "",
      },
      store: {},
      geolocation: {
        canBeRequested: true,
        currentPosition: {},
      },
      mode: "EDIT",
    },
  },
  ui: {
    workspaces: {
      currentWorkspace: {
        id: "659d2e14d0cbfb0c5e0a7424",
        userPermissions: [
          "publish:workspaceApplications",
          "delete:workspace",
          "manage:workspaceApplications",
          "delete:workspaceDatasources",
          "export:workspaceApplications",
          "read:workspaceDatasources",
          "read:workspaceApplications",
          "inviteUsers:workspace",
          "read:workspaces",
          "manage:workspaceDatasources",
          "create:datasources",
          "delete:workspaceApplications",
          "create:applications",
          "manage:workspaces",
        ],
        name: "jacques's apps",
        email: "jacques@adasdsad.com",
        plugins: [
          {
            userPermissions: [],
            pluginId: "653236215e9a6424e4c04b5c",
            status: "FREE",
            new: true,
          },
          {
            userPermissions: [],
            pluginId: "653236215e9a6424e4c04b5b",
            status: "FREE",
            new: true,
          },
          {
            userPermissions: [],
            pluginId: "653236225e9a6424e4c04b75",
            status: "FREE",
            new: true,
          },
          {
            userPermissions: [],
            pluginId: "653236215e9a6424e4c04b5a",
            status: "FREE",
            new: true,
          },
          {
            userPermissions: [],
            pluginId: "6572a3933efa034a885f73bf",
            status: "FREE",
            new: true,
          },
          {
            userPermissions: [],
            pluginId: "653236215e9a6424e4c04b59",
            status: "FREE",
            new: true,
          },
          {
            userPermissions: [],
            pluginId: "653236215e9a6424e4c04b64",
            status: "FREE",
            new: true,
          },
          {
            userPermissions: [],
            pluginId: "653236215e9a6424e4c04b63",
            status: "FREE",
            new: true,
          },
          {
            userPermissions: [],
            pluginId: "653236215e9a6424e4c04b62",
            status: "FREE",
            new: true,
          },
          {
            userPermissions: [],
            pluginId: "653236225e9a6424e4c04b74",
            status: "FREE",
            new: true,
          },
          {
            userPermissions: [],
            pluginId: "653236215e9a6424e4c04b58",
            status: "FREE",
            new: true,
          },
          {
            userPermissions: [],
            pluginId: "653236205e9a6424e4c04b51",
            status: "FREE",
            new: true,
          },
          {
            userPermissions: [],
            pluginId: "6597efc7d0cbfb0c5e0a73cc",
            status: "FREE",
            new: true,
          },
          {
            userPermissions: [],
            pluginId: "654a489144e16d2e57f05d60",
            status: "FREE",
            new: true,
          },
          {
            userPermissions: [],
            pluginId: "653236215e9a6424e4c04b61",
            status: "FREE",
            new: true,
          },
          {
            userPermissions: [],
            pluginId: "6597efc7d0cbfb0c5e0a73ce",
            status: "FREE",
            new: true,
          },
          {
            userPermissions: [],
            pluginId: "653236215e9a6424e4c04b55",
            status: "FREE",
            new: true,
          },
          {
            userPermissions: [],
            pluginId: "653236205e9a6424e4c04b52",
            status: "FREE",
            new: true,
          },
          {
            userPermissions: [],
            pluginId: "653236465e9a6424e4c04b77",
            status: "FREE",
            new: true,
          },
          {
            userPermissions: [],
            pluginId: "6597efc7d0cbfb0c5e0a73cd",
            status: "FREE",
            new: true,
          },
          {
            userPermissions: [],
            pluginId: "653236205e9a6424e4c04b53",
            status: "FREE",
            new: true,
          },
          {
            userPermissions: [],
            pluginId: "653236465e9a6424e4c04b78",
            status: "FREE",
            new: true,
          },
          {
            userPermissions: [],
            pluginId: "653236215e9a6424e4c04b5f",
            status: "FREE",
            new: true,
          },
          {
            userPermissions: [],
            pluginId: "653236465e9a6424e4c04b79",
            status: "FREE",
            new: true,
          },
          {
            userPermissions: [],
            pluginId: "653236215e9a6424e4c04b5e",
            status: "FREE",
            new: true,
          },
          {
            userPermissions: [],
            pluginId: "653236215e9a6424e4c04b5d",
            status: "FREE",
            new: true,
          },
        ],
        slug: "jacques-s-apps",
        isAutoGeneratedWorkspace: true,
        organizationId: "653236225e9a6424e4c04b65",
        logoUrl: "/api/v1/assets/null",
        new: false,
      },
    },
    selectedWorkspace: {
      workspace: {
        id: "659d2e14d0cbfb0c5e0a7424",
        userPermissions: [
          "publish:workspaceApplications",
          "delete:workspace",
          "manage:workspaceApplications",
          "delete:workspaceDatasources",
          "export:workspaceApplications",
          "read:workspaceDatasources",
          "read:workspaceApplications",
          "inviteUsers:workspace",
          "read:workspaces",
          "manage:workspaceDatasources",
          "create:datasources",
          "delete:workspaceApplications",
          "create:applications",
          "manage:workspaces",
        ],
        name: "jacques's apps",
        email: "jacques@adasdsad.com",
        plugins: [
          {
            userPermissions: [],
            pluginId: "653236215e9a6424e4c04b5c",
            status: "FREE",
            new: true,
          },
          {
            userPermissions: [],
            pluginId: "653236215e9a6424e4c04b5b",
            status: "FREE",
            new: true,
          },
          {
            userPermissions: [],
            pluginId: "653236225e9a6424e4c04b75",
            status: "FREE",
            new: true,
          },
          {
            userPermissions: [],
            pluginId: "653236215e9a6424e4c04b5a",
            status: "FREE",
            new: true,
          },
          {
            userPermissions: [],
            pluginId: "6572a3933efa034a885f73bf",
            status: "FREE",
            new: true,
          },
          {
            userPermissions: [],
            pluginId: "653236215e9a6424e4c04b59",
            status: "FREE",
            new: true,
          },
          {
            userPermissions: [],
            pluginId: "653236215e9a6424e4c04b64",
            status: "FREE",
            new: true,
          },
          {
            userPermissions: [],
            pluginId: "653236215e9a6424e4c04b63",
            status: "FREE",
            new: true,
          },
          {
            userPermissions: [],
            pluginId: "653236215e9a6424e4c04b62",
            status: "FREE",
            new: true,
          },
          {
            userPermissions: [],
            pluginId: "653236225e9a6424e4c04b74",
            status: "FREE",
            new: true,
          },
          {
            userPermissions: [],
            pluginId: "653236215e9a6424e4c04b58",
            status: "FREE",
            new: true,
          },
          {
            userPermissions: [],
            pluginId: "653236205e9a6424e4c04b51",
            status: "FREE",
            new: true,
          },
          {
            userPermissions: [],
            pluginId: "6597efc7d0cbfb0c5e0a73cc",
            status: "FREE",
            new: true,
          },
          {
            userPermissions: [],
            pluginId: "654a489144e16d2e57f05d60",
            status: "FREE",
            new: true,
          },
          {
            userPermissions: [],
            pluginId: "653236215e9a6424e4c04b61",
            status: "FREE",
            new: true,
          },
          {
            userPermissions: [],
            pluginId: "6597efc7d0cbfb0c5e0a73ce",
            status: "FREE",
            new: true,
          },
          {
            userPermissions: [],
            pluginId: "653236215e9a6424e4c04b55",
            status: "FREE",
            new: true,
          },
          {
            userPermissions: [],
            pluginId: "653236205e9a6424e4c04b52",
            status: "FREE",
            new: true,
          },
          {
            userPermissions: [],
            pluginId: "653236465e9a6424e4c04b77",
            status: "FREE",
            new: true,
          },
          {
            userPermissions: [],
            pluginId: "6597efc7d0cbfb0c5e0a73cd",
            status: "FREE",
            new: true,
          },
          {
            userPermissions: [],
            pluginId: "653236205e9a6424e4c04b53",
            status: "FREE",
            new: true,
          },
          {
            userPermissions: [],
            pluginId: "653236465e9a6424e4c04b78",
            status: "FREE",
            new: true,
          },
          {
            userPermissions: [],
            pluginId: "653236215e9a6424e4c04b5f",
            status: "FREE",
            new: true,
          },
          {
            userPermissions: [],
            pluginId: "653236465e9a6424e4c04b79",
            status: "FREE",
            new: true,
          },
          {
            userPermissions: [],
            pluginId: "653236215e9a6424e4c04b5e",
            status: "FREE",
            new: true,
          },
          {
            userPermissions: [],
            pluginId: "653236215e9a6424e4c04b5d",
            status: "FREE",
            new: true,
          },
        ],
        slug: "jacques-s-apps",
        isAutoGeneratedWorkspace: true,
        organizationId: "653236225e9a6424e4c04b65",
        logoUrl: "/api/v1/assets/null",
        new: false,
      },
    },
    applications: {
      currentApplication: {
        applicationDetail: {
          navigationSetting: {
            showNavbar: true,
            showSignIn: true,
            orientation: "top",
            navStyle: "stacked",
            position: "static",
            itemStyle: "text",
            colorStyle: "light",
            logoAssetId: "",
            logoConfiguration: "logoAndApplicationTitle",
          },
          themeSetting: {
            fontFamily: "System Default",
            accentColor: "#553DE9",
            colorMode: "LIGHT",
            borderRadius: "6px",
            density: 1,
            sizing: 1,
          },
        },
        id: "659d2e15d0cbfb0c5e0a7428",
        modifiedBy: "jacques@adasdsad.com",
        userPermissions: [
          "manage:applications",
          "canComment:applications",
          "export:applications",
          "manageProtectedBranches:applications",
          "read:applications",
          "manageDefaultBranches:applications",
          "create:pages",
          "publish:applications",
          "connectToGit:applications",
          "manageAutoCommit:applications",
          "delete:applications",
          "makePublic:applications",
        ],
        name: "My first application",
        workspaceId: "659d2e14d0cbfb0c5e0a7424",
        isPublic: false,
        appIsExample: false,
        unreadCommentThreads: 0,
        color: "#FBF4ED",
        slug: "my-first-application",
        unpublishedCustomJSLibs: [],
        publishedCustomJSLibs: [],
        evaluationVersion: 2,
        applicationVersion: 2,
        collapseInvisibleWidgets: true,
        isAutoUpdate: false,
        new: false,
        modifiedAt: "2024-01-09T11:29:25.076Z",
        pages: [
          {
            id: "659d2e15d0cbfb0c5e0a742b",
            name: "Page1",
            slug: "page1",
            isDefault: true,
            userPermissions: [
              "read:pages",
              "manage:pages",
              "create:pageActions",
              "delete:pages",
            ],
          },
        ],
      },
      isFetchingApplications: false,
    },
    templates: {
      filters: {
        functions: ["All"],
      },
      allFilters: {},
      templateSearchQuery: "",
      templates: [],
    },
  },
};
