// Generated by CodiumAI
import { DEFAULT_FONT_SIZE } from "constants/WidgetConstants";
import TextWidget from "widgets/TextWidget/widget";
describe("TextWidget", () => {
  // Renders text correctly with default properties
  it("should render text correctly with default properties", () => {
    const props = TextWidget.getDefaults();
    const textWidget = new TextWidget(props);
    const view = textWidget.getWidgetView();

    expect(view.props.children.props.text).toBe(
      "Hello {{appsmith.user.name || appsmith.user.email}}",
    );
    expect(view.props.children.props.fontSize).toBe(DEFAULT_FONT_SIZE);
    expect(view.props.children.props.fontStyle).toBe("BOLD");
    expect(view.props.children.props.textAlign).toBe("LEFT");
    expect(view.props.children.props.textColor).toBe("#231F20");
  });

  // Handles empty text property without errors
  it("should handle empty text property without errors", () => {
    const props = { ...TextWidget.getDefaults(), text: "" };
    const textWidget = new TextWidget(props);
    const view = textWidget.getWidgetView();

    expect(view.props.children.props.text).toBe("");
    expect(view.props.children.props.fontSize).toBe(DEFAULT_FONT_SIZE);
    expect(view.props.children.props.fontStyle).toBe("BOLD");
    expect(view.props.children.props.textAlign).toBe("LEFT");
    expect(view.props.children.props.textColor).toBe("#231F20");
  });
});
