{
 "title": "Redis Dashboard",
 "tags": [
  "prometheus",
  "redis"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(redis_up, namespace)"
   },
   {
    "name": "pod_name",
    "label": "Pod Name",
    "query": "label_values(redis_up{namespace=\"$namespace\"}, pod)"
   },
   {
    "name": "instance",
    "query": "label_values(redis_up{namespace=\"$namespace\", pod=\"$pod_name\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Total redis operations",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(spring_data_redis_seconds_count{})"
    }
   ]
  },
  {
   "title": "Total commands executed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(spring_data_redis_seconds_count{}[1m])",
     "legendFormat": "{{db_operation}}"
    }
   ]
  },
  {
   "title": "Total command duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(spring_data_redis_seconds_sum{}[$__rate_interval])",
     "legendFormat": "{{db_operation}}"
    }
   ]
  },
  {
   "title": "Success rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(db_operation) (spring_data_redis_seconds_count{error=\"none\"}) / sum by(db_operation) (spring_data_redis_seconds_count{})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}