exports.dsl = {
  dsl: {
    widgetName: "MainContainer",
    backgroundColor: "none",
    rightColumn: 816,
    snapColumns: 64,
    detachFromLayout: true,
    widgetId: "0",
    topRow: 0,
    bottomRow: 5016,
    containerStyle: "none",
    snapRows: 125,
    parentRowSpace: 1,
    type: "CANVAS_WIDGET",
    canExtend: true,
    version: 46,
    minHeight: 1292,
    parentColumnSpace: 1,
    dynamicBindingPathList: [],
    leftColumn: 0,
    children: [
      {
        isVisible: true,
        text: "Hello Satish",
        fontSize: "PARAGRAPH",
        fontStyle: "BOLD",
        textAlign: "LEFT",
        textColor: "#231F20",
        widgetName: "Text1",
        version: 1,
        type: "TEXT_WIDGET",
        hideCard: false,
        displayName: "Text",
        key: "ua553p4ugl",
        iconSVG: "/static/media/icon.97c59b52.svg",
        widgetId: "fupx9kpm8i",
        renderMode: "CANVAS",
        isLoading: false,
        parentColumnSpace: 12.5625,
        parentRowSpace: 10,
        leftColumn: 13,
        rightColumn: 29,
        topRow: 17,
        bottomRow: 21,
        parentId: "0",
        dynamicBindingPathList: [],
        dynamicTriggerPathList: [],
      },
    ],
  },
};
