#!/bin/sh
#
# Configured as part of the DigitalOcean 1-Click Image build process

myip=$(hostname -I | awk '{print$1}')
cat <<EOF
********************************************************************************
Hello! Welcome to your Appsmith droplet!

Your Appsmith is installed at ``/root/appsmith``.

Find our documentation at https://docs.appsmith.com and join us on Discord at https://discord.gg/rBTTVJp.
********************************************************************************
EOF