export const CUSTOM_WIDGET_BUILDER_EVENTS = {
  READY: "READY",
  READY_ACK: "READY_ACK",
  UPDATE_SRCDOC: "UPDATE_SRCDOC",
  UPDATE_SRCDOC_ACK: "UPDATE_SRCDOC_ACK",
  UPDATE_REFERRENCES: "UPDATE_REFERRENCES",
  UPDATE_REFERRENCES_ACK: "UPDATE_REFERRENCES_ACK",
  CLOSE: "CLOSE",
};
