import type { NestedDSL, UnnestedDSL } from "./DSL";
import { nestDSL, unnestDSL } from "./DSL";
import { ROOT_CONTAINER_WIDGET_ID } from "./constants";

// eslint-disable-next-line prettier/prettier
const SAMPLE_DSL = {
  widgetName: "MainContainer",
  backgroundColor: "none",
  rightColumn: 4896,
  snapColumns: 64,
  detachFromLayout: true,
  widgetId: "0",
  topRow: 0,
  bottomRow: 730,
  containerStyle: "none",
  snapRows: 124,
  parentRowSpace: 1,
  type: "CANVAS_WIDGET",
  canExtend: true,
  version: 80,
  minHeight: 1292,
  dynamicTriggerPathList: [],
  parentColumnSpace: 1,
  dynamicBindingPathList: [],
  leftColumn: 0,
  children: [
    {
      boxShadow: "{{appsmith.theme.boxShadow.appBoxShadow}}",
      requiresFlatWidgetChildren: true,
      isCanvas: true,
      iconSVG: "/static/media/icon.35f3ec19dbc201b2b26e900b1eeb08a0.svg",
      topRow: 33,
      pageSize: 3,
      type: "LIST_WIDGET_V2",
      itemSpacing: 8,
      animateLoading: true,
      dynamicBindingPathList: [
        { key: "currentItemsView" },
        { key: "selectedItemView" },
        { key: "triggeredItemView" },
        { key: "primaryKeys" },
        { key: "accentColor" },
        { key: "borderRadius" },
        { key: "boxShadow" },
      ],
      leftColumn: 9,
      enhancements: true,
      children: [
        {
          mobileBottomRow: 400,
          widgetName: "Canvas1",
          displayName: "Canvas",
          topRow: 0,
          bottomRow: 400,
          parentRowSpace: 1,
          type: "CANVAS_WIDGET",
          canExtend: false,
          hideCard: true,
          dropDisabled: true,
          openParentPropertyPane: true,
          minHeight: 400,
          mobileRightColumn: 392.796875,
          noPad: true,
          parentColumnSpace: 1,
          leftColumn: 0,
          dynamicBindingPathList: [],
          children: [
            {
              boxShadow: "{{appsmith.theme.boxShadow.appBoxShadow}}",
              mobileBottomRow: 12,
              widgetName: "Container1",
              borderColor: "#E0DEDE",
              disallowCopy: true,
              isCanvas: true,
              displayName: "Container",
              iconSVG:
                "/static/media/icon.c47c069fe28eb6d2d27f0fffdc053074.svg",
              searchTags: ["div", "parent", "group"],
              topRow: 0,
              bottomRow: 12,
              dragDisabled: true,
              type: "CONTAINER_WIDGET",
              hideCard: false,
              shouldScrollContents: false,
              isDeletable: false,
              mobileRightColumn: 64,
              animateLoading: true,
              leftColumn: 0,
              dynamicBindingPathList: [
                { key: "borderRadius" },
                { key: "boxShadow" },
              ],
              children: [
                {
                  widgetName: "Canvas2",
                  displayName: "Canvas",
                  topRow: 0,
                  bottomRow: 120,
                  parentRowSpace: 1,
                  type: "CANVAS_WIDGET",
                  canExtend: false,
                  hideCard: true,
                  useAutoLayout: false,
                  parentColumnSpace: 1,
                  leftColumn: 0,
                  dynamicBindingPathList: [],
                  children: [
                    {
                      boxShadow: "none",
                      mobileBottomRow: 8,
                      widgetName: "Image1",
                      displayName: "Image",
                      iconSVG:
                        "/static/media/icon.30c8cbd442cce232b01ba2d434c53a53.svg",
                      topRow: 0,
                      bottomRow: 8,
                      type: "IMAGE_WIDGET",
                      hideCard: false,
                      mobileRightColumn: 16,
                      animateLoading: true,
                      dynamicTriggerPathList: [],
                      imageShape: "RECTANGLE",
                      dynamicBindingPathList: [
                        { key: "image" },
                        { key: "borderRadius" },
                      ],
                      leftColumn: 0,
                      defaultImage:
                        "https://assets.appsmith.com/widgets/default.png",
                      key: "cwepcnpl32",
                      image: "{{currentItem.img}}",
                      isDeprecated: false,
                      rightColumn: 16,
                      objectFit: "cover",
                      widgetId: "upy3xp4ilf",
                      isVisible: true,
                      version: 1,
                      parentId: "yvls3113m0",
                      renderMode: "CANVAS",
                      isLoading: false,
                      mobileTopRow: 0,
                      maxZoomLevel: 1,
                      enableDownload: false,
                      borderRadius:
                        "{{appsmith.theme.borderRadius.appBorderRadius}}",
                      mobileLeftColumn: 0,
                      enableRotation: false,
                    },
                    {
                      boxShadow: "none",
                      mobileBottomRow: 4,
                      widgetName: "Text1",
                      displayName: "Text",
                      iconSVG:
                        "/static/media/icon.c3b6033f570046f8c6288d911333a827.svg",
                      searchTags: ["typography", "paragraph", "label"],
                      topRow: 0,
                      bottomRow: 4,
                      type: "TEXT_WIDGET",
                      hideCard: false,
                      mobileRightColumn: 28,
                      animateLoading: true,
                      overflow: "NONE",
                      dynamicTriggerPathList: [],
                      fontFamily: "{{appsmith.theme.fontFamily.appFont}}",
                      dynamicBindingPathList: [
                        { key: "text" },
                        { key: "truncateButtonColor" },
                        { key: "fontFamily" },
                        { key: "borderRadius" },
                      ],
                      leftColumn: 16,
                      shouldTruncate: false,
                      truncateButtonColor:
                        "{{appsmith.theme.colors.primaryColor}}",
                      text: "{{currentItem.name}}",
                      key: "xp3e1x8l6u",
                      isDeprecated: false,
                      rightColumn: 28,
                      textAlign: "LEFT",
                      dynamicHeight: "FIXED",
                      widgetId: "ccwpk4rv3j",
                      minWidth: 450,
                      isVisible: true,
                      fontStyle: "BOLD",
                      textColor: "#231F20",
                      version: 1,
                      parentId: "yvls3113m0",
                      renderMode: "CANVAS",
                      isLoading: false,
                      mobileTopRow: 0,
                      responsiveBehavior: "fill",
                      borderRadius:
                        "{{appsmith.theme.borderRadius.appBorderRadius}}",
                      mobileLeftColumn: 16,
                      maxDynamicHeight: 9000,
                      fontSize: "1rem",
                      textStyle: "HEADING",
                      minDynamicHeight: 4,
                    },
                    {
                      boxShadow: "none",
                      mobileBottomRow: 8,
                      widgetName: "Text2",
                      displayName: "Text",
                      iconSVG:
                        "/static/media/icon.c3b6033f570046f8c6288d911333a827.svg",
                      searchTags: ["typography", "paragraph", "label"],
                      topRow: 4,
                      bottomRow: 8,
                      type: "TEXT_WIDGET",
                      hideCard: false,
                      mobileRightColumn: 24,
                      animateLoading: true,
                      overflow: "NONE",
                      dynamicTriggerPathList: [],
                      fontFamily: "{{appsmith.theme.fontFamily.appFont}}",
                      dynamicBindingPathList: [
                        { key: "text" },
                        { key: "truncateButtonColor" },
                        { key: "fontFamily" },
                        { key: "borderRadius" },
                      ],
                      leftColumn: 16,
                      shouldTruncate: false,
                      truncateButtonColor:
                        "{{appsmith.theme.colors.primaryColor}}",
                      text: "{{currentItem.id}}",
                      key: "xp3e1x8l6u",
                      isDeprecated: false,
                      rightColumn: 24,
                      textAlign: "LEFT",
                      dynamicHeight: "FIXED",
                      widgetId: "g3uofmfu17",
                      minWidth: 450,
                      isVisible: true,
                      fontStyle: "BOLD",
                      textColor: "#231F20",
                      version: 1,
                      parentId: "yvls3113m0",
                      renderMode: "CANVAS",
                      isLoading: false,
                      mobileTopRow: 4,
                      responsiveBehavior: "fill",
                      borderRadius:
                        "{{appsmith.theme.borderRadius.appBorderRadius}}",
                      mobileLeftColumn: 16,
                      maxDynamicHeight: 9000,
                      fontSize: "1rem",
                      textStyle: "BODY",
                      minDynamicHeight: 4,
                    },
                  ],
                  key: "ncdyqpor2j",
                  isDeprecated: false,
                  detachFromLayout: true,
                  widgetId: "yvls3113m0",
                  containerStyle: "none",
                  minWidth: 450,
                  isVisible: true,
                  version: 1,
                  parentId: "shvsm3l4g7",
                  renderMode: "CANVAS",
                  isLoading: false,
                  mobileTopRow: 0,
                  responsiveBehavior: "fill",
                  mobileLeftColumn: 0,
                  flexLayers: [],
                },
              ],
              borderWidth: "1",
              positioning: "fixed",
              flexVerticalAlignment: "start",
              key: "ows9djl4p4",
              backgroundColor: "white",
              isDeprecated: false,
              rightColumn: 64,
              dynamicHeight: "FIXED",
              widgetId: "shvsm3l4g7",
              containerStyle: "card",
              minWidth: 450,
              isVisible: true,
              version: 1,
              isListItemContainer: true,
              parentId: "3n1y1ozs1j",
              renderMode: "CANVAS",
              isLoading: false,
              mobileTopRow: 0,
              responsiveBehavior: "fill",
              noContainerOffset: true,
              disabledWidgetFeatures: ["dynamicHeight"],
              borderRadius: "{{appsmith.theme.borderRadius.appBorderRadius}}",
              mobileLeftColumn: 0,
              maxDynamicHeight: 9000,
              minDynamicHeight: 10,
            },
          ],
          key: "ncdyqpor2j",
          isDeprecated: false,
          rightColumn: 392.796875,
          detachFromLayout: true,
          widgetId: "3n1y1ozs1j",
          containerStyle: "none",
          minWidth: 450,
          isVisible: true,
          version: 1,
          parentId: "rc2v2pco5x",
          renderMode: "CANVAS",
          isLoading: false,
          mobileTopRow: 0,
          responsiveBehavior: "fill",
          mobileLeftColumn: 0,
          flexLayers: [],
        },
      ],
      itemBackgroundColor: "#FFFFFF",
      accentColor: "{{appsmith.theme.colors.primaryColor}}",
      isVisible: true,
      hasMetaWidgets: true,
      isLoading: false,
      mainCanvasId: "3n1y1ozs1j",
      borderRadius: "{{appsmith.theme.borderRadius.appBorderRadius}}",
      additionalStaticProps: [
        "level",
        "levelData",
        "prefixMetaWidgetId",
        "metaWidgetId",
      ],
      mobileBottomRow: 71,
      currentItemsView: "{{[]}}",
      triggeredItemView: "{{{}}}",
      widgetName: "List1",
      listData: [
        {
          id: "001",
          name: "Blue",
          img: "https://assets.appsmith.com/widgets/default.png",
        },
        {
          id: "002",
          name: "Green",
          img: "https://assets.appsmith.com/widgets/default.png",
        },
        {
          id: "003",
          name: "Red",
          img: "https://assets.appsmith.com/widgets/default.png",
        },
      ],
      displayName: "List",
      bottomRow: 73,
      parentRowSpace: 10,
      hideCard: false,
      templateBottomRow: 16,
      mobileRightColumn: 23,
      mainContainerId: "shvsm3l4g7",
      primaryKeys:
        '{{List1.listData.map((currentItem, currentIndex) => currentItem["id"] )}}',
      parentColumnSpace: 17.078125,
      gridType: "vertical",
      key: "znjdpuqafa",
      backgroundColor: "transparent",
      isDeprecated: false,
      rightColumn: 32,
      widgetId: "rc2v2pco5x",
      minWidth: 450,
      parentId: "0",
      renderMode: "CANVAS",
      mobileTopRow: 31,
      responsiveBehavior: "fill",
      mobileLeftColumn: 0,
      selectedItemView: "{{{}}}",
    },
    {
      boxShadow: "{{appsmith.theme.boxShadow.appBoxShadow}}",
      mobileBottomRow: 43,
      widgetName: "Container2",
      borderColor: "#E0DEDE",
      isCanvas: true,
      displayName: "Container",
      iconSVG: "/static/media/icon.c47c069fe28eb6d2d27f0fffdc053074.svg",
      searchTags: ["div", "parent", "group"],
      topRow: 41,
      bottomRow: 57,
      parentRowSpace: 10,
      type: "CONTAINER_WIDGET",
      hideCard: false,
      shouldScrollContents: true,
      mobileRightColumn: 61,
      animateLoading: true,
      parentColumnSpace: 17.078125,
      leftColumn: 36,
      dynamicBindingPathList: [{ key: "borderRadius" }, { key: "boxShadow" }],
      children: [
        {
          mobileBottomRow: 100,
          widgetName: "Canvas3",
          displayName: "Canvas",
          topRow: 0,
          bottomRow: 160,
          parentRowSpace: 1,
          type: "CANVAS_WIDGET",
          canExtend: false,
          hideCard: true,
          minHeight: 100,
          mobileRightColumn: 409.875,
          parentColumnSpace: 1,
          leftColumn: 0,
          dynamicBindingPathList: [],
          children: [
            {
              boxShadow: "{{appsmith.theme.boxShadow.appBoxShadow}}",
              mobileBottomRow: 11,
              widgetName: "Container3",
              borderColor: "#E0DEDE",
              isCanvas: true,
              displayName: "Container",
              iconSVG:
                "/static/media/icon.c47c069fe28eb6d2d27f0fffdc053074.svg",
              searchTags: ["div", "parent", "group"],
              topRow: 1,
              bottomRow: 14,
              parentRowSpace: 10,
              type: "CONTAINER_WIDGET",
              hideCard: false,
              shouldScrollContents: true,
              mobileRightColumn: 28,
              animateLoading: true,
              parentColumnSpace: 6.091796875,
              leftColumn: 4,
              dynamicBindingPathList: [
                { key: "borderRadius" },
                { key: "boxShadow" },
              ],
              children: [
                {
                  mobileBottomRow: 100,
                  widgetName: "Canvas4",
                  displayName: "Canvas",
                  topRow: 0,
                  bottomRow: 130,
                  parentRowSpace: 1,
                  type: "CANVAS_WIDGET",
                  canExtend: false,
                  hideCard: true,
                  minHeight: 100,
                  mobileRightColumn: 146.203125,
                  parentColumnSpace: 1,
                  leftColumn: 0,
                  dynamicBindingPathList: [],
                  children: [
                    {
                      boxShadow: "{{appsmith.theme.boxShadow.appBoxShadow}}",
                      mobileBottomRow: 11,
                      widgetName: "Container4",
                      borderColor: "#E0DEDE",
                      isCanvas: true,
                      displayName: "Container",
                      iconSVG:
                        "/static/media/icon.c47c069fe28eb6d2d27f0fffdc053074.svg",
                      searchTags: ["div", "parent", "group"],
                      topRow: 1,
                      bottomRow: 11,
                      parentRowSpace: 10,
                      type: "CONTAINER_WIDGET",
                      hideCard: false,
                      shouldScrollContents: true,
                      mobileRightColumn: 33,
                      animateLoading: true,
                      parentColumnSpace: 4.82745361328125,
                      leftColumn: 9,
                      dynamicBindingPathList: [
                        { key: "borderRadius" },
                        { key: "boxShadow" },
                      ],
                      children: [
                        {
                          mobileBottomRow: 100,
                          widgetName: "Canvas5",
                          displayName: "Canvas",
                          topRow: 0,
                          bottomRow: 100,
                          parentRowSpace: 1,
                          type: "CANVAS_WIDGET",
                          canExtend: false,
                          hideCard: true,
                          minHeight: 100,
                          mobileRightColumn: 115.85888671875,
                          parentColumnSpace: 1,
                          leftColumn: 0,
                          dynamicBindingPathList: [],
                          children: [
                            {
                              mobileBottomRow: 6,
                              widgetName: "Text4",
                              displayName: "Text",
                              iconSVG:
                                "/static/media/icon.c3b6033f570046f8c6288d911333a827.svg",
                              searchTags: ["typography", "paragraph", "label"],
                              topRow: 2,
                              bottomRow: 6,
                              parentRowSpace: 10,
                              type: "TEXT_WIDGET",
                              hideCard: false,
                              mobileRightColumn: 37,
                              animateLoading: true,
                              overflow: "NONE",
                              fontFamily:
                                "{{appsmith.theme.fontFamily.appFont}}",
                              parentColumnSpace: 1.4977951049804688,
                              leftColumn: 21,
                              dynamicBindingPathList: [
                                { key: "truncateButtonColor" },
                                { key: "fontFamily" },
                                { key: "borderRadius" },
                              ],
                              shouldTruncate: false,
                              truncateButtonColor:
                                "{{appsmith.theme.colors.primaryColor}}",
                              text: "Label",
                              key: "c5hxqhpakk",
                              isDeprecated: false,
                              rightColumn: 58,
                              textAlign: "LEFT",
                              dynamicHeight: "AUTO_HEIGHT",
                              widgetId: "jjwddocy09",
                              minWidth: 450,
                              isVisible: true,
                              fontStyle: "BOLD",
                              textColor: "#231F20",
                              version: 1,
                              parentId: "c1a174vcuv",
                              renderMode: "CANVAS",
                              isLoading: false,
                              mobileTopRow: 2,
                              responsiveBehavior: "fill",
                              originalTopRow: 2,
                              borderRadius:
                                "{{appsmith.theme.borderRadius.appBorderRadius}}",
                              mobileLeftColumn: 21,
                              maxDynamicHeight: 9000,
                              originalBottomRow: 11,
                              fontSize: "1rem",
                              minDynamicHeight: 4,
                            },
                          ],
                          key: "6eauw600tz",
                          isDeprecated: false,
                          rightColumn: 115.85888671875,
                          detachFromLayout: true,
                          widgetId: "c1a174vcuv",
                          containerStyle: "none",
                          minWidth: 450,
                          isVisible: true,
                          version: 1,
                          parentId: "ioi2hs6bb8",
                          renderMode: "CANVAS",
                          isLoading: false,
                          mobileTopRow: 0,
                          responsiveBehavior: "fill",
                          mobileLeftColumn: 0,
                          flexLayers: [],
                        },
                      ],
                      borderWidth: "1",
                      flexVerticalAlignment: "start",
                      key: "4i422x0he4",
                      backgroundColor: "#FFFFFF",
                      isDeprecated: false,
                      rightColumn: 33,
                      dynamicHeight: "AUTO_HEIGHT",
                      widgetId: "ioi2hs6bb8",
                      containerStyle: "card",
                      minWidth: 450,
                      isVisible: true,
                      version: 1,
                      parentId: "wsqb5t6x2y",
                      renderMode: "CANVAS",
                      isLoading: false,
                      mobileTopRow: 1,
                      responsiveBehavior: "fill",
                      originalTopRow: 1,
                      borderRadius:
                        "{{appsmith.theme.borderRadius.appBorderRadius}}",
                      mobileLeftColumn: 9,
                      maxDynamicHeight: 9000,
                      originalBottomRow: 11,
                      minDynamicHeight: 10,
                    },
                    {
                      mobileBottomRow: 8,
                      widgetName: "Text3",
                      displayName: "Text",
                      iconSVG:
                        "/static/media/icon.c3b6033f570046f8c6288d911333a827.svg",
                      searchTags: ["typography", "paragraph", "label"],
                      topRow: 4,
                      bottomRow: 8,
                      parentRowSpace: 10,
                      type: "TEXT_WIDGET",
                      hideCard: false,
                      mobileRightColumn: 53,
                      animateLoading: true,
                      overflow: "NONE",
                      fontFamily: "{{appsmith.theme.fontFamily.appFont}}",
                      parentColumnSpace: 4.82745361328125,
                      leftColumn: 37,
                      dynamicBindingPathList: [
                        { key: "truncateButtonColor" },
                        { key: "fontFamily" },
                        { key: "borderRadius" },
                      ],
                      shouldTruncate: false,
                      truncateButtonColor:
                        "{{appsmith.theme.colors.primaryColor}}",
                      text: "Label",
                      key: "c5hxqhpakk",
                      isDeprecated: false,
                      rightColumn: 53,
                      textAlign: "LEFT",
                      dynamicHeight: "AUTO_HEIGHT",
                      widgetId: "wud7q8j28k",
                      minWidth: 450,
                      isVisible: true,
                      fontStyle: "BOLD",
                      textColor: "#231F20",
                      version: 1,
                      parentId: "wsqb5t6x2y",
                      renderMode: "CANVAS",
                      isLoading: false,
                      mobileTopRow: 4,
                      responsiveBehavior: "fill",
                      borderRadius:
                        "{{appsmith.theme.borderRadius.appBorderRadius}}",
                      mobileLeftColumn: 37,
                      maxDynamicHeight: 9000,
                      fontSize: "1rem",
                      minDynamicHeight: 4,
                    },
                  ],
                  key: "6eauw600tz",
                  isDeprecated: false,
                  rightColumn: 146.203125,
                  detachFromLayout: true,
                  widgetId: "wsqb5t6x2y",
                  containerStyle: "none",
                  minWidth: 450,
                  isVisible: true,
                  version: 1,
                  parentId: "8u270nkzh3",
                  renderMode: "CANVAS",
                  isLoading: false,
                  mobileTopRow: 0,
                  responsiveBehavior: "fill",
                  mobileLeftColumn: 0,
                  flexLayers: [],
                },
              ],
              borderWidth: "1",
              flexVerticalAlignment: "start",
              key: "4i422x0he4",
              backgroundColor: "#FFFFFF",
              isDeprecated: false,
              rightColumn: 58,
              dynamicHeight: "AUTO_HEIGHT",
              widgetId: "8u270nkzh3",
              containerStyle: "card",
              minWidth: 450,
              isVisible: true,
              version: 1,
              parentId: "pfyl7wpbpi",
              renderMode: "CANVAS",
              isLoading: false,
              mobileTopRow: 1,
              responsiveBehavior: "fill",
              originalTopRow: 1,
              borderRadius: "{{appsmith.theme.borderRadius.appBorderRadius}}",
              mobileLeftColumn: 4,
              maxDynamicHeight: 9000,
              originalBottomRow: 14,
              minDynamicHeight: 10,
            },
          ],
          key: "6eauw600tz",
          isDeprecated: false,
          rightColumn: 409.875,
          detachFromLayout: true,
          widgetId: "pfyl7wpbpi",
          containerStyle: "none",
          minWidth: 450,
          isVisible: true,
          version: 1,
          parentId: "ohmnikzp4y",
          renderMode: "CANVAS",
          isLoading: false,
          mobileTopRow: 0,
          responsiveBehavior: "fill",
          mobileLeftColumn: 0,
          flexLayers: [],
        },
      ],
      borderWidth: "1",
      flexVerticalAlignment: "start",
      key: "4i422x0he4",
      backgroundColor: "#FFFFFF",
      isDeprecated: false,
      rightColumn: 60,
      dynamicHeight: "AUTO_HEIGHT",
      widgetId: "ohmnikzp4y",
      containerStyle: "card",
      minWidth: 450,
      isVisible: true,
      version: 1,
      parentId: "0",
      renderMode: "CANVAS",
      isLoading: false,
      mobileTopRow: 33,
      responsiveBehavior: "fill",
      originalTopRow: 41,
      borderRadius: "{{appsmith.theme.borderRadius.appBorderRadius}}",
      mobileLeftColumn: 37,
      maxDynamicHeight: 9000,
      originalBottomRow: 57,
      minDynamicHeight: 10,
    },
    {
      resetFormOnClick: false,
      boxShadow: "none",
      mobileBottomRow: 63,
      widgetName: "Button1",
      buttonColor: "{{appsmith.theme.colors.primaryColor}}",
      displayName: "Button",
      iconSVG: "/static/media/icon.7beb9123fb53027d9d6b778cdfe4caed.svg",
      searchTags: ["click", "submit"],
      topRow: 59,
      bottomRow: 63,
      parentRowSpace: 10,
      type: "BUTTON_WIDGET",
      hideCard: false,
      mobileRightColumn: 52,
      animateLoading: true,
      parentColumnSpace: 17.078125,
      leftColumn: 36,
      dynamicBindingPathList: [{ key: "buttonColor" }, { key: "borderRadius" }],
      text: "Submit",
      isDisabled: false,
      key: "8ydzffjwno",
      isDeprecated: false,
      rightColumn: 52,
      isDefaultClickDisabled: true,
      widgetId: "jc5vxeux1w",
      minWidth: 120,
      isVisible: true,
      recaptchaType: "V3",
      version: 1,
      parentId: "0",
      renderMode: "CANVAS",
      isLoading: false,
      mobileTopRow: 59,
      responsiveBehavior: "hug",
      originalTopRow: 59,
      disabledWhenInvalid: false,
      borderRadius: "{{appsmith.theme.borderRadius.appBorderRadius}}",
      mobileLeftColumn: 36,
      originalBottomRow: 63,
      buttonVariant: "PRIMARY",
      placement: "CENTER",
    },
  ],
};

// eslint-disable-next-line prettier/prettier
const SAMPLE_FLAT_DSL = {
  entities: {
    canvasWidgets: {
      "0": {
        widgetName: "MainContainer",
        backgroundColor: "none",
        rightColumn: 4896,
        snapColumns: 64,
        detachFromLayout: true,
        widgetId: "0",
        topRow: 0,
        bottomRow: 730,
        containerStyle: "none",
        snapRows: 124,
        parentRowSpace: 1,
        type: "CANVAS_WIDGET",
        canExtend: true,
        version: 80,
        minHeight: 1292,
        dynamicTriggerPathList: [],
        parentColumnSpace: 1,
        dynamicBindingPathList: [],
        leftColumn: 0,
        children: ["rc2v2pco5x", "ohmnikzp4y", "jc5vxeux1w"],
      },
      upy3xp4ilf: {
        boxShadow: "none",
        mobileBottomRow: 8,
        widgetName: "Image1",
        displayName: "Image",
        iconSVG: "/static/media/icon.30c8cbd442cce232b01ba2d434c53a53.svg",
        topRow: 0,
        bottomRow: 8,
        type: "IMAGE_WIDGET",
        hideCard: false,
        mobileRightColumn: 16,
        animateLoading: true,
        dynamicTriggerPathList: [],
        imageShape: "RECTANGLE",
        dynamicBindingPathList: [{ key: "image" }, { key: "borderRadius" }],
        leftColumn: 0,
        defaultImage: "https://assets.appsmith.com/widgets/default.png",
        key: "cwepcnpl32",
        image: "{{currentItem.img}}",
        isDeprecated: false,
        rightColumn: 16,
        objectFit: "cover",
        widgetId: "upy3xp4ilf",
        isVisible: true,
        version: 1,
        parentId: "yvls3113m0",
        renderMode: "CANVAS",
        isLoading: false,
        mobileTopRow: 0,
        maxZoomLevel: 1,
        enableDownload: false,
        borderRadius: "{{appsmith.theme.borderRadius.appBorderRadius}}",
        mobileLeftColumn: 0,
        enableRotation: false,
      },
      ccwpk4rv3j: {
        boxShadow: "none",
        mobileBottomRow: 4,
        widgetName: "Text1",
        displayName: "Text",
        iconSVG: "/static/media/icon.c3b6033f570046f8c6288d911333a827.svg",
        searchTags: ["typography", "paragraph", "label"],
        topRow: 0,
        bottomRow: 4,
        type: "TEXT_WIDGET",
        hideCard: false,
        mobileRightColumn: 28,
        animateLoading: true,
        overflow: "NONE",
        dynamicTriggerPathList: [],
        fontFamily: "{{appsmith.theme.fontFamily.appFont}}",
        dynamicBindingPathList: [
          { key: "text" },
          { key: "truncateButtonColor" },
          { key: "fontFamily" },
          { key: "borderRadius" },
        ],
        leftColumn: 16,
        shouldTruncate: false,
        truncateButtonColor: "{{appsmith.theme.colors.primaryColor}}",
        text: "{{currentItem.name}}",
        key: "xp3e1x8l6u",
        isDeprecated: false,
        rightColumn: 28,
        textAlign: "LEFT",
        dynamicHeight: "FIXED",
        widgetId: "ccwpk4rv3j",
        minWidth: 450,
        isVisible: true,
        fontStyle: "BOLD",
        textColor: "#231F20",
        version: 1,
        parentId: "yvls3113m0",
        renderMode: "CANVAS",
        isLoading: false,
        mobileTopRow: 0,
        responsiveBehavior: "fill",
        borderRadius: "{{appsmith.theme.borderRadius.appBorderRadius}}",
        mobileLeftColumn: 16,
        maxDynamicHeight: 9000,
        fontSize: "1rem",
        textStyle: "HEADING",
        minDynamicHeight: 4,
      },
      g3uofmfu17: {
        boxShadow: "none",
        mobileBottomRow: 8,
        widgetName: "Text2",
        displayName: "Text",
        iconSVG: "/static/media/icon.c3b6033f570046f8c6288d911333a827.svg",
        searchTags: ["typography", "paragraph", "label"],
        topRow: 4,
        bottomRow: 8,
        type: "TEXT_WIDGET",
        hideCard: false,
        mobileRightColumn: 24,
        animateLoading: true,
        overflow: "NONE",
        dynamicTriggerPathList: [],
        fontFamily: "{{appsmith.theme.fontFamily.appFont}}",
        dynamicBindingPathList: [
          { key: "text" },
          { key: "truncateButtonColor" },
          { key: "fontFamily" },
          { key: "borderRadius" },
        ],
        leftColumn: 16,
        shouldTruncate: false,
        truncateButtonColor: "{{appsmith.theme.colors.primaryColor}}",
        text: "{{currentItem.id}}",
        key: "xp3e1x8l6u",
        isDeprecated: false,
        rightColumn: 24,
        textAlign: "LEFT",
        dynamicHeight: "FIXED",
        widgetId: "g3uofmfu17",
        minWidth: 450,
        isVisible: true,
        fontStyle: "BOLD",
        textColor: "#231F20",
        version: 1,
        parentId: "yvls3113m0",
        renderMode: "CANVAS",
        isLoading: false,
        mobileTopRow: 4,
        responsiveBehavior: "fill",
        borderRadius: "{{appsmith.theme.borderRadius.appBorderRadius}}",
        mobileLeftColumn: 16,
        maxDynamicHeight: 9000,
        fontSize: "1rem",
        textStyle: "BODY",
        minDynamicHeight: 4,
      },
      yvls3113m0: {
        widgetName: "Canvas2",
        displayName: "Canvas",
        topRow: 0,
        bottomRow: 120,
        parentRowSpace: 1,
        type: "CANVAS_WIDGET",
        canExtend: false,
        hideCard: true,
        useAutoLayout: false,
        parentColumnSpace: 1,
        leftColumn: 0,
        dynamicBindingPathList: [],
        children: ["upy3xp4ilf", "ccwpk4rv3j", "g3uofmfu17"],
        key: "ncdyqpor2j",
        isDeprecated: false,
        detachFromLayout: true,
        widgetId: "yvls3113m0",
        containerStyle: "none",
        minWidth: 450,
        isVisible: true,
        version: 1,
        parentId: "shvsm3l4g7",
        renderMode: "CANVAS",
        isLoading: false,
        mobileTopRow: 0,
        responsiveBehavior: "fill",
        mobileLeftColumn: 0,
        flexLayers: [],
      },
      shvsm3l4g7: {
        boxShadow: "{{appsmith.theme.boxShadow.appBoxShadow}}",
        mobileBottomRow: 12,
        widgetName: "Container1",
        borderColor: "#E0DEDE",
        disallowCopy: true,
        isCanvas: true,
        displayName: "Container",
        iconSVG: "/static/media/icon.c47c069fe28eb6d2d27f0fffdc053074.svg",
        searchTags: ["div", "parent", "group"],
        topRow: 0,
        bottomRow: 12,
        dragDisabled: true,
        type: "CONTAINER_WIDGET",
        hideCard: false,
        shouldScrollContents: false,
        isDeletable: false,
        mobileRightColumn: 64,
        animateLoading: true,
        leftColumn: 0,
        dynamicBindingPathList: [{ key: "borderRadius" }, { key: "boxShadow" }],
        children: ["yvls3113m0"],
        borderWidth: "1",
        positioning: "fixed",
        flexVerticalAlignment: "start",
        key: "ows9djl4p4",
        backgroundColor: "white",
        isDeprecated: false,
        rightColumn: 64,
        dynamicHeight: "FIXED",
        widgetId: "shvsm3l4g7",
        containerStyle: "card",
        minWidth: 450,
        isVisible: true,
        version: 1,
        isListItemContainer: true,
        parentId: "3n1y1ozs1j",
        renderMode: "CANVAS",
        isLoading: false,
        mobileTopRow: 0,
        responsiveBehavior: "fill",
        noContainerOffset: true,
        disabledWidgetFeatures: ["dynamicHeight"],
        borderRadius: "{{appsmith.theme.borderRadius.appBorderRadius}}",
        mobileLeftColumn: 0,
        maxDynamicHeight: 9000,
        minDynamicHeight: 10,
      },
      "3n1y1ozs1j": {
        mobileBottomRow: 400,
        widgetName: "Canvas1",
        displayName: "Canvas",
        topRow: 0,
        bottomRow: 400,
        parentRowSpace: 1,
        type: "CANVAS_WIDGET",
        canExtend: false,
        hideCard: true,
        dropDisabled: true,
        openParentPropertyPane: true,
        minHeight: 400,
        mobileRightColumn: 392.796875,
        noPad: true,
        parentColumnSpace: 1,
        leftColumn: 0,
        dynamicBindingPathList: [],
        children: ["shvsm3l4g7"],
        key: "ncdyqpor2j",
        isDeprecated: false,
        rightColumn: 392.796875,
        detachFromLayout: true,
        widgetId: "3n1y1ozs1j",
        containerStyle: "none",
        minWidth: 450,
        isVisible: true,
        version: 1,
        parentId: "rc2v2pco5x",
        renderMode: "CANVAS",
        isLoading: false,
        mobileTopRow: 0,
        responsiveBehavior: "fill",
        mobileLeftColumn: 0,
        flexLayers: [],
      },
      rc2v2pco5x: {
        boxShadow: "{{appsmith.theme.boxShadow.appBoxShadow}}",
        requiresFlatWidgetChildren: true,
        isCanvas: true,
        iconSVG: "/static/media/icon.35f3ec19dbc201b2b26e900b1eeb08a0.svg",
        topRow: 33,
        pageSize: 3,
        type: "LIST_WIDGET_V2",
        itemSpacing: 8,
        animateLoading: true,
        dynamicBindingPathList: [
          { key: "currentItemsView" },
          { key: "selectedItemView" },
          { key: "triggeredItemView" },
          { key: "primaryKeys" },
          { key: "accentColor" },
          { key: "borderRadius" },
          { key: "boxShadow" },
        ],
        leftColumn: 9,
        enhancements: true,
        children: ["3n1y1ozs1j"],
        itemBackgroundColor: "#FFFFFF",
        accentColor: "{{appsmith.theme.colors.primaryColor}}",
        isVisible: true,
        hasMetaWidgets: true,
        isLoading: false,
        mainCanvasId: "3n1y1ozs1j",
        borderRadius: "{{appsmith.theme.borderRadius.appBorderRadius}}",
        additionalStaticProps: [
          "level",
          "levelData",
          "prefixMetaWidgetId",
          "metaWidgetId",
        ],
        mobileBottomRow: 71,
        currentItemsView: "{{[]}}",
        triggeredItemView: "{{{}}}",
        widgetName: "List1",
        listData: [
          {
            id: "001",
            name: "Blue",
            img: "https://assets.appsmith.com/widgets/default.png",
          },
          {
            id: "002",
            name: "Green",
            img: "https://assets.appsmith.com/widgets/default.png",
          },
          {
            id: "003",
            name: "Red",
            img: "https://assets.appsmith.com/widgets/default.png",
          },
        ],
        displayName: "List",
        bottomRow: 73,
        parentRowSpace: 10,
        hideCard: false,
        templateBottomRow: 16,
        mobileRightColumn: 23,
        mainContainerId: "shvsm3l4g7",
        primaryKeys:
          '{{List1.listData.map((currentItem, currentIndex) => currentItem["id"] )}}',
        parentColumnSpace: 17.078125,
        gridType: "vertical",
        key: "znjdpuqafa",
        backgroundColor: "transparent",
        isDeprecated: false,
        rightColumn: 32,
        widgetId: "rc2v2pco5x",
        minWidth: 450,
        parentId: "0",
        renderMode: "CANVAS",
        mobileTopRow: 31,
        responsiveBehavior: "fill",
        mobileLeftColumn: 0,
        selectedItemView: "{{{}}}",
      },
      jjwddocy09: {
        mobileBottomRow: 6,
        widgetName: "Text4",
        displayName: "Text",
        iconSVG: "/static/media/icon.c3b6033f570046f8c6288d911333a827.svg",
        searchTags: ["typography", "paragraph", "label"],
        topRow: 2,
        bottomRow: 6,
        parentRowSpace: 10,
        type: "TEXT_WIDGET",
        hideCard: false,
        mobileRightColumn: 37,
        animateLoading: true,
        overflow: "NONE",
        fontFamily: "{{appsmith.theme.fontFamily.appFont}}",
        parentColumnSpace: 1.4977951049804688,
        leftColumn: 21,
        dynamicBindingPathList: [
          { key: "truncateButtonColor" },
          { key: "fontFamily" },
          { key: "borderRadius" },
        ],
        shouldTruncate: false,
        truncateButtonColor: "{{appsmith.theme.colors.primaryColor}}",
        text: "Label",
        key: "c5hxqhpakk",
        isDeprecated: false,
        rightColumn: 58,
        textAlign: "LEFT",
        dynamicHeight: "AUTO_HEIGHT",
        widgetId: "jjwddocy09",
        minWidth: 450,
        isVisible: true,
        fontStyle: "BOLD",
        textColor: "#231F20",
        version: 1,
        parentId: "c1a174vcuv",
        renderMode: "CANVAS",
        isLoading: false,
        mobileTopRow: 2,
        responsiveBehavior: "fill",
        originalTopRow: 2,
        borderRadius: "{{appsmith.theme.borderRadius.appBorderRadius}}",
        mobileLeftColumn: 21,
        maxDynamicHeight: 9000,
        originalBottomRow: 11,
        fontSize: "1rem",
        minDynamicHeight: 4,
      },
      c1a174vcuv: {
        mobileBottomRow: 100,
        widgetName: "Canvas5",
        displayName: "Canvas",
        topRow: 0,
        bottomRow: 100,
        parentRowSpace: 1,
        type: "CANVAS_WIDGET",
        canExtend: false,
        hideCard: true,
        minHeight: 100,
        mobileRightColumn: 115.85888671875,
        parentColumnSpace: 1,
        leftColumn: 0,
        dynamicBindingPathList: [],
        children: ["jjwddocy09"],
        key: "6eauw600tz",
        isDeprecated: false,
        rightColumn: 115.85888671875,
        detachFromLayout: true,
        widgetId: "c1a174vcuv",
        containerStyle: "none",
        minWidth: 450,
        isVisible: true,
        version: 1,
        parentId: "ioi2hs6bb8",
        renderMode: "CANVAS",
        isLoading: false,
        mobileTopRow: 0,
        responsiveBehavior: "fill",
        mobileLeftColumn: 0,
        flexLayers: [],
      },
      ioi2hs6bb8: {
        boxShadow: "{{appsmith.theme.boxShadow.appBoxShadow}}",
        mobileBottomRow: 11,
        widgetName: "Container4",
        borderColor: "#E0DEDE",
        isCanvas: true,
        displayName: "Container",
        iconSVG: "/static/media/icon.c47c069fe28eb6d2d27f0fffdc053074.svg",
        searchTags: ["div", "parent", "group"],
        topRow: 1,
        bottomRow: 11,
        parentRowSpace: 10,
        type: "CONTAINER_WIDGET",
        hideCard: false,
        shouldScrollContents: true,
        mobileRightColumn: 33,
        animateLoading: true,
        parentColumnSpace: 4.82745361328125,
        leftColumn: 9,
        dynamicBindingPathList: [{ key: "borderRadius" }, { key: "boxShadow" }],
        children: ["c1a174vcuv"],
        borderWidth: "1",
        flexVerticalAlignment: "start",
        key: "4i422x0he4",
        backgroundColor: "#FFFFFF",
        isDeprecated: false,
        rightColumn: 33,
        dynamicHeight: "AUTO_HEIGHT",
        widgetId: "ioi2hs6bb8",
        containerStyle: "card",
        minWidth: 450,
        isVisible: true,
        version: 1,
        parentId: "wsqb5t6x2y",
        renderMode: "CANVAS",
        isLoading: false,
        mobileTopRow: 1,
        responsiveBehavior: "fill",
        originalTopRow: 1,
        borderRadius: "{{appsmith.theme.borderRadius.appBorderRadius}}",
        mobileLeftColumn: 9,
        maxDynamicHeight: 9000,
        originalBottomRow: 11,
        minDynamicHeight: 10,
      },
      wud7q8j28k: {
        mobileBottomRow: 8,
        widgetName: "Text3",
        displayName: "Text",
        iconSVG: "/static/media/icon.c3b6033f570046f8c6288d911333a827.svg",
        searchTags: ["typography", "paragraph", "label"],
        topRow: 4,
        bottomRow: 8,
        parentRowSpace: 10,
        type: "TEXT_WIDGET",
        hideCard: false,
        mobileRightColumn: 53,
        animateLoading: true,
        overflow: "NONE",
        fontFamily: "{{appsmith.theme.fontFamily.appFont}}",
        parentColumnSpace: 4.82745361328125,
        leftColumn: 37,
        dynamicBindingPathList: [
          { key: "truncateButtonColor" },
          { key: "fontFamily" },
          { key: "borderRadius" },
        ],
        shouldTruncate: false,
        truncateButtonColor: "{{appsmith.theme.colors.primaryColor}}",
        text: "Label",
        key: "c5hxqhpakk",
        isDeprecated: false,
        rightColumn: 53,
        textAlign: "LEFT",
        dynamicHeight: "AUTO_HEIGHT",
        widgetId: "wud7q8j28k",
        minWidth: 450,
        isVisible: true,
        fontStyle: "BOLD",
        textColor: "#231F20",
        version: 1,
        parentId: "wsqb5t6x2y",
        renderMode: "CANVAS",
        isLoading: false,
        mobileTopRow: 4,
        responsiveBehavior: "fill",
        borderRadius: "{{appsmith.theme.borderRadius.appBorderRadius}}",
        mobileLeftColumn: 37,
        maxDynamicHeight: 9000,
        fontSize: "1rem",
        minDynamicHeight: 4,
      },
      wsqb5t6x2y: {
        mobileBottomRow: 100,
        widgetName: "Canvas4",
        displayName: "Canvas",
        topRow: 0,
        bottomRow: 130,
        parentRowSpace: 1,
        type: "CANVAS_WIDGET",
        canExtend: false,
        hideCard: true,
        minHeight: 100,
        mobileRightColumn: 146.203125,
        parentColumnSpace: 1,
        leftColumn: 0,
        dynamicBindingPathList: [],
        children: ["ioi2hs6bb8", "wud7q8j28k"],
        key: "6eauw600tz",
        isDeprecated: false,
        rightColumn: 146.203125,
        detachFromLayout: true,
        widgetId: "wsqb5t6x2y",
        containerStyle: "none",
        minWidth: 450,
        isVisible: true,
        version: 1,
        parentId: "8u270nkzh3",
        renderMode: "CANVAS",
        isLoading: false,
        mobileTopRow: 0,
        responsiveBehavior: "fill",
        mobileLeftColumn: 0,
        flexLayers: [],
      },
      "8u270nkzh3": {
        boxShadow: "{{appsmith.theme.boxShadow.appBoxShadow}}",
        mobileBottomRow: 11,
        widgetName: "Container3",
        borderColor: "#E0DEDE",
        isCanvas: true,
        displayName: "Container",
        iconSVG: "/static/media/icon.c47c069fe28eb6d2d27f0fffdc053074.svg",
        searchTags: ["div", "parent", "group"],
        topRow: 1,
        bottomRow: 14,
        parentRowSpace: 10,
        type: "CONTAINER_WIDGET",
        hideCard: false,
        shouldScrollContents: true,
        mobileRightColumn: 28,
        animateLoading: true,
        parentColumnSpace: 6.091796875,
        leftColumn: 4,
        dynamicBindingPathList: [{ key: "borderRadius" }, { key: "boxShadow" }],
        children: ["wsqb5t6x2y"],
        borderWidth: "1",
        flexVerticalAlignment: "start",
        key: "4i422x0he4",
        backgroundColor: "#FFFFFF",
        isDeprecated: false,
        rightColumn: 58,
        dynamicHeight: "AUTO_HEIGHT",
        widgetId: "8u270nkzh3",
        containerStyle: "card",
        minWidth: 450,
        isVisible: true,
        version: 1,
        parentId: "pfyl7wpbpi",
        renderMode: "CANVAS",
        isLoading: false,
        mobileTopRow: 1,
        responsiveBehavior: "fill",
        originalTopRow: 1,
        borderRadius: "{{appsmith.theme.borderRadius.appBorderRadius}}",
        mobileLeftColumn: 4,
        maxDynamicHeight: 9000,
        originalBottomRow: 14,
        minDynamicHeight: 10,
      },
      pfyl7wpbpi: {
        mobileBottomRow: 100,
        widgetName: "Canvas3",
        displayName: "Canvas",
        topRow: 0,
        bottomRow: 160,
        parentRowSpace: 1,
        type: "CANVAS_WIDGET",
        canExtend: false,
        hideCard: true,
        minHeight: 100,
        mobileRightColumn: 409.875,
        parentColumnSpace: 1,
        leftColumn: 0,
        dynamicBindingPathList: [],
        children: ["8u270nkzh3"],
        key: "6eauw600tz",
        isDeprecated: false,
        rightColumn: 409.875,
        detachFromLayout: true,
        widgetId: "pfyl7wpbpi",
        containerStyle: "none",
        minWidth: 450,
        isVisible: true,
        version: 1,
        parentId: "ohmnikzp4y",
        renderMode: "CANVAS",
        isLoading: false,
        mobileTopRow: 0,
        responsiveBehavior: "fill",
        mobileLeftColumn: 0,
        flexLayers: [],
      },
      ohmnikzp4y: {
        boxShadow: "{{appsmith.theme.boxShadow.appBoxShadow}}",
        mobileBottomRow: 43,
        widgetName: "Container2",
        borderColor: "#E0DEDE",
        isCanvas: true,
        displayName: "Container",
        iconSVG: "/static/media/icon.c47c069fe28eb6d2d27f0fffdc053074.svg",
        searchTags: ["div", "parent", "group"],
        topRow: 41,
        bottomRow: 57,
        parentRowSpace: 10,
        type: "CONTAINER_WIDGET",
        hideCard: false,
        shouldScrollContents: true,
        mobileRightColumn: 61,
        animateLoading: true,
        parentColumnSpace: 17.078125,
        leftColumn: 36,
        dynamicBindingPathList: [{ key: "borderRadius" }, { key: "boxShadow" }],
        children: ["pfyl7wpbpi"],
        borderWidth: "1",
        flexVerticalAlignment: "start",
        key: "4i422x0he4",
        backgroundColor: "#FFFFFF",
        isDeprecated: false,
        rightColumn: 60,
        dynamicHeight: "AUTO_HEIGHT",
        widgetId: "ohmnikzp4y",
        containerStyle: "card",
        minWidth: 450,
        isVisible: true,
        version: 1,
        parentId: "0",
        renderMode: "CANVAS",
        isLoading: false,
        mobileTopRow: 33,
        responsiveBehavior: "fill",
        originalTopRow: 41,
        borderRadius: "{{appsmith.theme.borderRadius.appBorderRadius}}",
        mobileLeftColumn: 37,
        maxDynamicHeight: 9000,
        originalBottomRow: 57,
        minDynamicHeight: 10,
      },
      jc5vxeux1w: {
        resetFormOnClick: false,
        boxShadow: "none",
        mobileBottomRow: 63,
        widgetName: "Button1",
        buttonColor: "{{appsmith.theme.colors.primaryColor}}",
        displayName: "Button",
        iconSVG: "/static/media/icon.7beb9123fb53027d9d6b778cdfe4caed.svg",
        searchTags: ["click", "submit"],
        topRow: 59,
        bottomRow: 63,
        parentRowSpace: 10,
        type: "BUTTON_WIDGET",
        hideCard: false,
        mobileRightColumn: 52,
        animateLoading: true,
        parentColumnSpace: 17.078125,
        leftColumn: 36,
        dynamicBindingPathList: [
          { key: "buttonColor" },
          { key: "borderRadius" },
        ],
        text: "Submit",
        isDisabled: false,
        key: "8ydzffjwno",
        isDeprecated: false,
        rightColumn: 52,
        isDefaultClickDisabled: true,
        widgetId: "jc5vxeux1w",
        minWidth: 120,
        isVisible: true,
        recaptchaType: "V3",
        version: 1,
        parentId: "0",
        renderMode: "CANVAS",
        isLoading: false,
        mobileTopRow: 59,
        responsiveBehavior: "hug",
        originalTopRow: 59,
        disabledWhenInvalid: false,
        borderRadius: "{{appsmith.theme.borderRadius.appBorderRadius}}",
        mobileLeftColumn: 36,
        originalBottomRow: 63,
        buttonVariant: "PRIMARY",
        placement: "CENTER",
      },
    },
  },
  result: "0",
};

describe("Test #1 - Check export types & constant values", () => {
  it("nestDSL is a function", () => {
    expect(typeof nestDSL).toBe("function");
  });

  it("unnestDSL is a function", () => {
    expect(typeof unnestDSL).toBe("function");
  });

  it("ROOT_CONTAINER_WIDGET_ID is a string", () => {
    expect(typeof ROOT_CONTAINER_WIDGET_ID).toBe("string");
  });

  it("ROOT_CONTAINER_WIDGET_ID remains 0", () => {
    expect(ROOT_CONTAINER_WIDGET_ID).toBe("0");
  });
});

describe("Test #2 - Check functional sanity", () => {
  const getDynamicNestedDSL = (limit = 10) => {
    const nestedDSL: NestedDSL<Record<string, any>> = {
      widgetId: "0",
      widgetName: "MainContainer",
    };
    let temp = nestedDSL;
    for (let i = 1; i <= limit; i += 1) {
      const newChild = {
        widgetId: i.toString(),
        widgetName: `Container${i}`,
      };
      temp.children = [newChild];
      temp = newChild;
    }
    return nestedDSL;
  };

  const getDynamicFlatDSL = (limit = 10) => {
    const widgets: UnnestedDSL<Record<string, any>> = {
      "0": {
        widgetId: "0",
        widgetName: "MainContainer",
        children: ["1"],
      },
    };
    for (let i = 1; i <= limit; i += 1) {
      const widgetId = i.toString();
      const newWidget: Record<string, any> = {
        widgetId,
        widgetName: `Container${i}`,
      };
      if (i < limit) {
        newWidget.children = [(i + 1).toString()];
      }
      widgets[widgetId] = newWidget;
    }
    return widgets;
  };

  it("Check `unnestDSL` for 10 level deep nesting", () => {
    const nestedDSL = getDynamicNestedDSL(10);
    const expectedFlatDSL = getDynamicFlatDSL(10);

    const flatDSL = unnestDSL(nestedDSL);
    expect(flatDSL).toStrictEqual(expectedFlatDSL);
  });

  it("Check `unnestDSL` for 100 level deep nesting", () => {
    const nestedDSL = getDynamicNestedDSL(100);
    const expectedFlatDSL = getDynamicFlatDSL(100);

    const flatDSL = unnestDSL(nestedDSL);
    expect(flatDSL).toStrictEqual(expectedFlatDSL);
  });

  it("`unnestDSL` throws error for maximum callstack for >500 level deep nesting", () => {
    const nestedDSL = getDynamicNestedDSL(10000);
    expect(() => {
      unnestDSL(nestedDSL);
    }).toThrowError(RangeError);
  });

  it("Check `nestDSL` for 10 level deep nesting", () => {
    const flatDSL = getDynamicFlatDSL(10);
    const expectedNestedDSL = getDynamicNestedDSL(10);

    const nestedDSL = nestDSL(flatDSL);
    expect(nestedDSL).toStrictEqual(expectedNestedDSL);
  });

  it("Check `nestDSL` for 100 level deep nesting", () => {
    const flatDSL = getDynamicFlatDSL(100);
    const expectedNestedDSL = getDynamicNestedDSL(100);

    const nestedDSL = nestDSL(flatDSL);
    expect(nestedDSL).toStrictEqual(expectedNestedDSL);
  });

  it("`nestDSL` throws error for maximum callstack for >500 level deep nesting", () => {
    const flatDSL = getDynamicFlatDSL(10000);
    expect(() => {
      nestDSL(flatDSL);
    }).toThrowError(RangeError);
  });
});

describe("Test #3 - normalize operations on SIMPLE DSL structures", () => {
  const simple_dsl = {
    widgetId: "0",
    widgetName: "MainContainer",
    children: [
      {
        widgetId: "0/0",
        widgetName: "Text1",
      },
      {
        widgetId: "0/1",
        widgetName: "Container1",
        children: [
          {
            widgetId: "0/1/0",
            widgetName: "Canvas1",
            children: [
              {
                widgetId: "0/1/0/0",
                widgetName: "Button1",
              },
            ],
          },
        ],
      },
    ],
  };
  const simple_flat_dsl = {
    "0": {
      widgetId: "0",
      widgetName: "MainContainer",
      children: ["0/0", "0/1"],
    },
    "0/0": { widgetId: "0/0", widgetName: "Text1" },
    "0/1": { widgetId: "0/1", widgetName: "Container1", children: ["0/1/0"] },
    "0/1/0": {
      widgetId: "0/1/0",
      widgetName: "Canvas1",
      children: ["0/1/0/0"],
    },
    "0/1/0/0": { widgetId: "0/1/0/0", widgetName: "Button1" },
  };

  it("Test `unnestDSL` for simple_dsl", () => {
    const flatDSL = unnestDSL(simple_dsl);
    expect(flatDSL).toStrictEqual(simple_flat_dsl);
  });

  it("Test `nestDSL` for simple_flat_dsl", () => {
    const nestedDSL = nestDSL(simple_flat_dsl);
    expect(nestedDSL).toStrictEqual(simple_dsl);
  });
});

describe("Test #4 - normalize operations on REAL DSL structures", () => {
  it("Test `unnestDSL` on SAMPLE_DSL", () => {
    const flatDSL = unnestDSL<Record<string, any>>(SAMPLE_DSL);
    expect(flatDSL).toStrictEqual(SAMPLE_FLAT_DSL.entities.canvasWidgets);
  });

  it("Test `nestDSL` on SAMPLE_FLAT_DSL", () => {
    const nestedDSL = nestDSL(SAMPLE_FLAT_DSL.entities.canvasWidgets);
    expect(nestedDSL).toStrictEqual(SAMPLE_DSL);
  });
});

export {};
