exports.actions = {
  SELECT_CATEGORY: "SELECT_CATEGORY",
  BIND_TABLE_DATA: "BIND_TABLE_DATA",
  CLICK_ON_TABLE_ROW: "CLICK_ON_TABLE_ROW",
  UPDATE_POST_TITLE: "UPDATE_POST_TITLE",
  OPEN_MODAL: "OPEN_MODAL",
  CLOSE_MODAL: "CLOSE_MODAL",
  SELECT_WIDGET_MENU_OPEN: "SELECT_WIDGET_MENU_OPEN",
  SELECT_WIDGET_SELECT_OPTION: "SELECT_WIDGET_SELECT_OPTION",

  // misc test
  MISC_OPEN_SELECT_WIDGET: "MISC_OPEN_SELECT_WIDGET",
  MISC_SELECT_OPTION: "MISC_SELECT_OPTION",
  MISC_ECHO: "MISC_ECHO",
  SELECT_TABLE: "SELECT_TABLE",
  MISC_CLICK_TABLE_ROW: "MISC_CLICK_TABLE_ROW",
  MISC_OPEN_SIMPLE_MODAL: "MISC_OPEN_SIMPLE_MODAL",
  MISC_CLOSE_SIMPLE_MODAL: "MISC_CLOSE_SIMPLE_MODAL",

  MISC_OPEN_COMPLEX_MODAL: "MISC_OPEN_COMPLEX_MODAL",
  MISC_CLOSE_COMPLEX_MODAL: "MISC_CLOSE_COMPLEX_MODAL",
};
