exports.actions = {
  SELECT_CATEGORY: "SELECT_CATEGORY",
  BIND_TABLE_DATA: "BIND_TABLE_DATA",
  CLICK_ON_TABLE_ROW: "CLICK_ON_TABLE_ROW",
  UPDATE_POST_TITLE: "UPDATE_POST_TITLE",
  OPEN_MODAL: "OPEN_MODAL",
  CLOSE_MODAL: "CLOSE_MODAL",
};
