import type {
  AssignmentExpressionData,
  CallExpressionData,
  IdentifierInfo,
  MemberCallExpressionData,
  MemberExpressionData,
  ObjectExpression,
  PropertyNode,
} from "./src";
import {
  entityRefactorFromCode,
  extractExpressionsFromCode,
  extractIdentifierInfoFromCode,
  getAST,
  getFunctionalParamsFromNode,
  getMemberExpressionObjectFromProperty,
  isCallExpressionNode,
  isFunctionPresent,
  isIdentifierNode,
  isLiteralNode,
  isObjectExpression,
  isPropertyAFunctionNode,
  isPropertyNode,
  isTypeOfFunction,
  isVariableDeclarator,
} from "./src";
// action creator
import {
  canTranslateToUI,
  checkIfArgumentExistAtPosition,
  checkIfCatchBlockExists,
  checkIfThenBlockExists,
  getActionBlocks,
  getCallExpressions,
  getEnumArgumentAtPosition,
  getFuncExpressionAtPosition,
  getFunction,
  getFunctionArguments,
  getFunctionBodyStatements,
  getFunctionName,
  getFunctionNameFromJsObjectExpression,
  getFunctionParams,
  getMainAction,
  getModalName,
  getQueryParam,
  getTextArgumentAtPosition,
  getThenCatchBlocksFromQuery,
  replaceActionInQuery,
  setCallbackFunctionField,
  setCatchBlockInQuery,
  setEnumArgumentAtPosition,
  setModalName,
  setObjectAtPosition,
  setQueryParam,
  setTextArgumentAtPosition,
  setThenBlockInQuery,
} from "./src/actionCreator";
// constants
import { ECMA_VERSION, NodeTypes, SourceType } from "./src/constants";
// JSObjects
import type {
  JSFunctionProperty,
  JSPropertyPosition,
  JSVarProperty,
  TParsedJSProperty,
} from "./src/jsObject";
import {
  addPropertiesToJSObjectCode,
  isJSFunctionProperty,
  parseJSObject,
} from "./src/jsObject";
// peekOverlay
import type { PeekOverlayExpressionIdentifierOptions } from "./src/peekOverlay";
import { PeekOverlayExpressionIdentifier } from "./src/peekOverlay";

// types or interfaces should be exported with type keyword, while enums can be exported like normal functions
export type {
  ObjectExpression,
  PropertyNode,
  MemberExpressionData,
  IdentifierInfo,
  TParsedJSProperty,
  JSPropertyPosition,
  PeekOverlayExpressionIdentifierOptions,
  AssignmentExpressionData,
  JSVarProperty,
  JSFunctionProperty,
  CallExpressionData,
  MemberCallExpressionData,
};

export {
  isIdentifierNode,
  isVariableDeclarator,
  isObjectExpression,
  isLiteralNode,
  isPropertyNode,
  isPropertyAFunctionNode,
  isCallExpressionNode,
  getAST,
  extractIdentifierInfoFromCode,
  entityRefactorFromCode,
  extractExpressionsFromCode,
  getFunctionalParamsFromNode,
  isTypeOfFunction,
  parseJSObject,
  ECMA_VERSION,
  SourceType,
  NodeTypes,
  getTextArgumentAtPosition,
  getEnumArgumentAtPosition,
  getModalName,
  setModalName,
  setTextArgumentAtPosition,
  setEnumArgumentAtPosition,
  getFuncExpressionAtPosition,
  getFunction,
  replaceActionInQuery,
  setCallbackFunctionField,
  getActionBlocks,
  getFunctionBodyStatements,
  getMainAction,
  getFunctionName,
  setObjectAtPosition,
  getThenCatchBlocksFromQuery,
  setThenBlockInQuery,
  setCatchBlockInQuery,
  getFunctionArguments,
  getFunctionNameFromJsObjectExpression,
  getCallExpressions,
  canTranslateToUI,
  getFunctionParams,
  getQueryParam,
  setQueryParam,
  checkIfThenBlockExists,
  checkIfCatchBlockExists,
  checkIfArgumentExistAtPosition,
  isJSFunctionProperty,
  isFunctionPresent,
  PeekOverlayExpressionIdentifier,
  getMemberExpressionObjectFromProperty,
  addPropertiesToJSObjectCode,
};
