name: Close Labeler

on:
  pull_request:
    types:
      - closed
    branches:
      - release

jobs:
  apply:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.CLOSE_LABELER_GITHUB_TOKEN }}
          script: |
            console.log("PR Details", context.issue)

            let hasNextPage = true;
            let afterCursor = null;

            while (hasNextPage) {
              const result = await github.graphql(
                `
                  query($owner: String!, $name: String!, $prNum: Int!, $afterCursor: String) {
                    repository(owner: $owner, name: $name) {
                      pullRequest(number: $prNum) {
                        closingIssuesReferences(first: 50, after: $afterCursor) {
                          pageInfo {
                            hasNextPage
                            endCursor
                          }
                          nodes {
                            number
                            repository {
                              name
                              owner {
                                login
                              }
                            }
                            labels(first: 50) {
                              edges {
                                node {
                                  name
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                `,
                {
                  owner: context.issue.owner,
                  name: context.issue.repo,
                  prNum: context.issue.number,
                  afterCursor,
                },
              )

              const closingIssues = result?.repository?.pullRequest?.closingIssuesReferences
              if (!closingIssues?.nodes) {
                break
              }

              for (const node of closingIssues.nodes) {
                const shouldQA = node.labels.edges.find(edge => edge.node.name === "Enhancement" || edge.node.name === "Bug") != null
                if (!shouldQA) {
                  continue
                }
                console.log("Adding QA to", node.repository.owner.login, node.repository.name, node.number)
                await github.rest.issues.addLabels({
                  issue_number: node.number,
                  owner: node.repository.owner.login,
                  repo: node.repository.name,
                  labels: ["QA"],
                })
              }

              hasNextPage = closingIssues.pageInfo?.hasNextPage ?? false
              afterCursor = closingIssues.pageInfo?.endCursor ?? null
            }

            console.log("Fin")

